laurent22/joplin

- BUILD.md
I was getting an error on `yarn dist` which I solved with the command `npm install -g node-gyp`.
This was the error:
```
Error: /usr/local/Cellar/node/8.9.1/bin/node exited with code 1
Output:
$ node-pre-gyp install --fallback-to-build
Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.38
node-pre-gyp info using node@8.9.1 | darwin | x64
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/electron-v1.7-darwin-x64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/electron-v1.7-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to …
```
> Add node-gyp dependency to instructions

- BUILD.md
Notes about `npm install -g windows-build-tools` was in "Building the Electron application" section instead of "Building Electron application on Windows" thus it wasn't unequivocal.
> Clarify Windows build dependencies

- ElectronClient/app/app.js
- ElectronClient/app/gui/MainScreen.jsx
- ElectronClient/app/gui/Root.jsx
- ReactNativeClient/lib/models/Setting.js
Closes #183
Please find the image below. Note that I've made **Toggle sidebar** the first item in the Menubar since it made sense for it to be there. Let me know if you want to move it.
VSCode has removed some trailing white spaces, hope that's OK.
Signed-off-by: Abijeet <abijeetpatro@gmail.com>
> Adds support to toggle the sidebar.

- ElectronClient/app/app.js
Towards #183
**Off Topic** - Got this error a couple of times while pushing my code,
```
remote: /data/github/releases/deploy-b/vendor/gems/2.4.2/ruby/2.4.0/gems/statsd-ruby-0.3.0.github.3.38.gd478cc7/lib/github/statsd.rb:23:in `ip': getaddrinfo: Name or service not known (SocketError)
remote: 	from /data/github/releases/deploy-b/vendor/gems/2.4.2/ruby/2.4.0/gems/statsd-ruby-0.3.0.github.3.38.gd478cc7/lib/github/statsd.rb:23:in `initialize'
remote: 	from /data/github/releases/deploy-b/vendor/gems/2.4.2/ruby/2.4.0/gems/statsd-ruby-0.3.0.github.3.38.gd478cc7/lib/github/statsd.rb:106:in `new'
remote: 	from /data/github/releases/deploy-b/vendor/gems/2.4.2/ruby/2.4.0/gems/statsd-ruby-0.3.0.github.3.38.gd478cc7/lib/github/statsd.rb:106:in `add_shard'
remote: 	from …
```
> Add the toggle sidebar option to the View app menu bar.

- ReactNativeClient/lib/import-enex-md-gen.js
Hello,
This is an attempt to maintain monospace formatting during Evernote import for fonts like Courier, Menlo, etc. It is very useful for code snippets which are translated into MD in  &#768; or  &#768;  &#768;  &#768; sections as is necessary. The idea is to merge several lines in monospace font into single  &#768;  &#768;  &#768; section.
Here is an enex file for a test:
[Monospace test.zip](https://github.com/laurent22/joplin/files/1896485/Monospace.test.zip)
It would be nice to have an "Import option" where monospace merging can be disabled. I prepared an option for function enexXmlToMdArray. But it also requires changes in UI that I didn't dare to do yet.
Notes:
- ~~It doesn't add any new support for code blocks (this will require a different mechanism, but I may have a look next …
> Merge monospace text lines when importing from Evernote

- ReactNativeClient/lib/file-api-driver-webdav.js
Parse the d:status field for d:propstat sections within a d:multistatus response to a DAV PROPFIND because Nginx returns 404 statuses wrapped in an overall 207
Proposed fix for https://github.com/laurent22/joplin/issues/523
> Handle Nginx DAV PROPFIND responses correctly

- ElectronClient/app/gui/NoteText.jsx
This changes the behaviour so that loading a note does automatically
focus the note text/title only when a new note is being created.
This reduces accidental edits and is in line with other note taking
applications such as Simplenote, Evernote and Apple Notes.
> focus NoteText only when creating new notes

- ReactNativeClient/lib/synchronizer.js
This change displays the correct date/time format (the one specified in settings) for the sync time.
(See issue #421 for more details.)
P.S.: Once again, there's an extra commit for fixing a small whitespace error in the file.
>  use correct date/time format for sync time - fix for #421

- ReactNativeClient/android/app/build.gradle
- ReactNativeClient/android/app/src/main/AndroidManifest.xml
- ReactNativeClient/android/app/src/main/java/net/cozic/joplin/MainApplication.java
- ReactNativeClient/android/app/src/main/java/net/cozic/joplin/share/ShareActivity.java
- ReactNativeClient/android/app/src/main/java/net/cozic/joplin/share/ShareApplication.java
- ReactNativeClient/android/settings.gradle
- ReactNativeClient/lib/components/screens/note.js
- ReactNativeClient/lib/components/screens/notes.js
- ReactNativeClient/lib/components/shared/note-screen-shared.js
- ReactNativeClient/lib/reducer.js
- ReactNativeClient/package-lock.json
- ReactNativeClient/package.json
- ReactNativeClient/root.js
I mostly follow the procedure given in the readme of the [react-native-share-extension](https://github.com/alinz/react-native-share-extension). I also added to the react native side so that this will actually work. 
This currently doesn't work on ios because I don't have a development environment that supports developing for ios, but in principle someone that does just needs to follow the same instructions that I did (but for ios) and it'll be good to go.
Currently I only added support for sharing plain text (not images) because it seems that the underlying extension has issues actually passing around images.
I think the only potentially contentious change I've added is hooking into the AppState change events. This is done to force the note list to refresh when re-opening the app after …
> Add text sharing on android

- CliClient/app/command-ls.js
- ReactNativeClient/lib/BaseApplication.js
This change will allow the correct date/time to be shown when running the CLI app and when running the command directly (e.g.: `joplin ls -l`).
See also #729
> show correct date/time for cli command `ls`

- ReactNativeClient/android/app/src/main/AndroidManifest.xml
This change allows the app to be installed on an SD card.
Info on `android:installLocation`:
When your application is installed on the external storage:
- There is no effect on the application performance so long as the external storage is mounted on the device.
- The .apk file is saved on the external storage, but all private user data, databases, optimized .dex files, and extracted native code are saved on the internal device memory.
- The unique container in which your application is stored is encrypted with a randomly generated key that can be decrypted only by the device that originally installed it. Thus, an application installed on an SD card works for only one device.
- The user can move your application to the internal storage through the system settings.
P.S.: I also fixed a few …
> allow the app to be installed on external storage (SD card) 

- CliClient/app/command-e2ee.js
fixes #782
This fixes and adds the following use cases to print the clear text:
* `joplin e2ee decrypt "JEDsome_encryption_cipher_text_blocks"`
* `git show commithash:encrypted-notes-file.md | joplin e2ee decrypt`
* `cat encrypted-notes-file.md | joplin e2ee decrypt`
* `echo "JEDsome_encryption_cipher_text_blocks" | joplin e2ee decrypt`
> CLI: improve e2ee decrypt command

- install_ubuntu.sh
If no former version is present, the script fails since the rm commands do not succeed.
Added -f to rm in order to ignore non-existent files to be deleted.
> Fix ubuntu install script

- Tools/build-translation.js
shared folder :file_folder: is needed, so the encryption menu will be translated
> add shared folder

- Joplin_install_and_update.sh
Avoid an erroneous update and prevent installation icon only on gnome.
> Linux script install: implement previous updates

- BUILD.md
- readme/building_win32_tips.md
Maybe we can have a .md like this for the build instructions on Windows.
> Adding some tips for building and debugging Joplin on Windows

- ElectronClient/app/gui/MainScreen.jsx
- ElectronClient/app/gui/NoteText.jsx
- ElectronClient/app/gui/TagItem.jsx
- ElectronClient/app/gui/TagList.jsx
- ElectronClient/app/theme.js
- ReactNativeClient/lib/models/Tag.js
- ReactNativeClient/lib/reducer.js
Towards #469
Signed-off-by: Abijeet <abijeetpatro@gmail.com>
> Adds functionality to display tags under the open note.

- CliClient/tests/EnexToMd.js
- CliClient/tests/HtmlToMd.js
- ElectronClient/app/gui/NoteText.jsx
- ReactNativeClient/lib/MdToHtml.js
- ReactNativeClient/lib/string-utils.js
An example of a possible approach, to temporarily change the html in the webview to show the note title. Works, but there may be a more elegant fix.
> Show note title in pdf export (#890)

- CliClient/tests/services_InteropService.js
- ReactNativeClient/lib/models/BaseItem.js
- ReactNativeClient/lib/services/InteropService.js
- ReactNativeClient/lib/services/InteropService_Exporter_Json.js
> Patch to implement feature, exporting notes to JSON (#912, issues/912).

- ReactNativeClient/lib/shim-init-node.js
https://github.com/laurent22/joplin/blob/b30c65dd89d46c44d534e719725909575bce47e5/ReactNativeClient/lib/shim-init-node.js#L241
Url like 
> http://example.com/favicon.ico?ver=1.0 
will be changed to
> http://example.com/favicon.ico?ver=1.0?ver=1.0
Image from some website will fail to download.
testcase
> https://static.leiphone.com/uploads/new/images/20181112/5be958706ae86.png?imageView2/2/w/740
> Fix image fetching error in ClipperServer for URLs with query string.

- ReactNativeClient/root.js
When NAV_BACK from folder or tag to the Welcome page, show side menu too. Because people are mostly going to change to a different folder or tag,  and not just seeing the useless Welcome page at such situation.
People used to press NAV_BACK on Welcome page to exitApp. But as is often the case now, the side menu is shown on Welcome page, and one NAV_BACK action only hide the side menu, another NAV_BACK action is needed to exitApp. This logic is better to be changed to save the extra click:
>    When BACK button is pressed on Welcome page while side menu is shown, hide the side menu and also exitApp.
>    When BACK button is pressed on Welcome page while side menu is not shown, show the side menu.
> ReactNativeClient: A better NAV_BACK logic to change folder or tag.

- ElectronClient/app/gui/note-viewer/highlight/styles/atom-one-dark-reasonable.css
Self explanatory. I neglected to add this to my previous pull request, so the only person who had syntax highlighting was sadly me.
fixes #982
> Add missing syntax file for dark theme

- Joplin_install_and_update.sh
I've removed the creation of an unused VERSION file, which throws an error if the script is run from a non-writable directory.
The user is also warned when running the script as root, preventing unintended installation as root:root.
> Useless and error prone VERSION file removed & warn use of root

- ElectronClient/app/package.json
Upgrades sqlite3 to 4.0.4 and adds `install-app-deps` to `postinstall`. This seems to be a solution for failing build due to sqlite3.
> Fix failing Windows build

- CliClient/locales/nb_NO.po
- README.md
- docs/index.html
- docs/terminal/index.html
- readme/terminal.md
Completed the translation for Norwegian (bokmål) as well as renamed the locale to its [correct locale name](http://www.localeplanet.com/icu/nb-NO/index.html) in the documentation and .po file name.
If the renaming requires other changes in the source files, please comment and I'll revise the PR. 
Thanks for a great app.
-matsest
> Revise and complete Norwegian translation (no) and rename to correct locale: nb_NO

- Joplin_install_and_update.sh
The directory ~/.local/share/applications/ also exists in Kubuntu 18.04 so with this change the script also works in Kubuntu.
> Update to make it works in Kubuntu

- README.md
- readme/faq.md
I added some example external editor configs for popular editors to the FAQ. Having some trouble with this on my own I did not find this in the docs, but have found [questions](https://discourse.joplin.cozic.net/search?q=external%20editor) in the support forum. Not an open issue, but I think this could be useful for new users to quickly be able to configure and use this (IMO) underrated feature. In that regard, I also suggest adding it to the Feature list.
If this is either consider to verbose or any of the editor examples are wrong - feel free to contribute. Note: I do not have Windows myself, so those are not tested. Perhaps other examples should be included as well?
> [Documentation] Add example editor config to FAQ

- ElectronClient/app/ElectronAppWrapper.js
- ElectronClient/app/package.json
This was a weird one that I suspect will come up again when electron-builder is updated. For some reason the resources that are specified by `extraResources` in `package.json` are placed one level up from the app directory even though they initially reside in the app directory itself. Unfortunately this fix means that the icon is messed up when running joplin in debug mode.
I also added a desktop parameter into `package.json` this makes sure that the .desktop file generated by the appimage (if used) will have the correct icon name.
Fixes #251
> Fix window manager icon on linux

- ReactNativeClient/lib/string-utils.js
fix to issue https://github.com/laurent22/joplin/issues/1012. File URLs should work now.
> fixed file url issue

- ElectronClient/app/package-lock.json
- ElectronClient/app/package.json
- ReactNativeClient/lib/MdToHtml.js
- ReactNativeClient/package-lock.json
- ReactNativeClient/package.json
fixes #1050 
The real bug here was with [markdown-it-katex](https://github.com/waylonflinn/markdown-it-katex/issues) which hasn't been updated in 3 years and has 5 open pull requests, so it's unlikely to be fixed on that end.
It should be possible to use markdown-it-texmath as our rendering as well, but when I attempted that it had some errors rendering which didn't seem worthwhile to deal with.
So basically everything stays the same, except the behaviour is more intuitive.
On another note, there was some auto updates to package-lock.json by npm, is it okay to ignore these? I can remove it from the pull request if necessary.
> Prevent Katex $ symbol from working across multiple lines

- ElectronClient/app/theme.js
fixes #1106
This looks like a lot of changes but mostly it just moves a lot of the code into the `addExtraStyles` function.
Most notable is the changes to line 207-211 of theme.js
> Apply zoom and editorfont updates without needing to restart

- ElectronClient/app/gui/NotePropertiesDialog.jsx
It's a handy feature, but not not so important. 
I'm not sure when you guys will accept PR for new features again. 
Just keep it until you are not so busy.
Keep up the good work.
> Desktop: handle ESC key press to cancel the NotePropertiesDialog

- readme/welcome/1_welcome_to_joplin.md
I'm not sure about the "Joplin has three main columns" part. While it would be more correct to put articles in front of the names, I think they aren't necessary and it seems more visually clear to me this way.
(As a side note: the PR info says I should "prefix the title with the platform you are targetting [sic]" as either Desktop, Mobile or CLI. This change doesn't touch any code, though. Not sure about what to do here.)
> Docs: Suggesting some language improvements for the Welcome page

- ElectronClient/app/style.css
- ReactNativeClient/lib/MdToHtml.js
This applies some styling updates to the scrollbars. Currently the webview defaults are in use which look fine for the light theme (although the side bar with notebooks etc. is a little bit lacking). But with the dark theme it's a little bit breaking. 
This replaces the scrollbar with a much simpler visual scrollbar that matches the theme much better
Note: the scrollbar will darken/lighten on hover but I couldn't get a good screenshot of that
> Customization to the scrollbars

- Clipper/joplin-webclipper/manifest.json
Put "icons/32.png" in browser_action.default_icon is not enough, need to put it in icons["32"], too.
> Clipper: bugfix, joplin icon not show up in Firefox using 32px size.

- ReactNativeClient/lib/components/side-menu-content.js
- ReactNativeClient/root.js
Minor style update: set background colour (both light & dark theme) for iOS Safe Areas to respect iOS style guideline.
Dark theme:
[menu closed - iphone x](https://user-images.githubusercontent.com/17232523/52448073-05137b00-2b33-11e9-81a0-6ace21b2682a.png)
[menu open - iphone x](https://user-images.githubusercontent.com/17232523/52448074-05137b00-2b33-11e9-81b0-11ccb2da1728.png)
[menu closed - iphone 7](https://user-images.githubusercontent.com/17232523/52448818-5cb2e600-2b35-11e9-9aff-fde05eab0cda.png)
[menu open - iphone 7](https://user-images.githubusercontent.com/17232523/52448819-5cb2e600-2b35-11e9-8b77-d0ea8238564b.png)
Light theme:
[menu closed - iphone x](https://user-images.githubusercontent.com/17232523/52448076-05ac1180-2b33-11e9-97d1-a96314bde5f6.png)
[menu open- iphone …
> Mobile: Set background colour for iOS Safe Areas

- ElectronClient/app/style.css
- ReactNativeClient/lib/MdToHtml.js
I noticed that I had neglected to set a height for the horizontal scrollbars, and additionally there was a little white square that would appear in the bottom right corner when the horizontal scrollbar is active, this fixes that.
Before
After
> Fix little white corner between scrollbars

- ElectronClient/app/gui/MainScreen.jsx
- ElectronClient/app/gui/PromptDialog.jsx
- ElectronClient/app/gui/TagItem.jsx
- ElectronClient/app/gui/TagList.jsx
- ElectronClient/app/style.css
- ElectronClient/app/theme.js
This adds a new more functional (and attractive) dialogue for adding and removing tags from a note. To remove a tag you simply need to click on the tag twice from the tag dialogue.
fixes #1111 
and partially #471 
The only thing worth mentioning is that I used the autocomplete prop in PromptDialog, I couldn't figure out what this prop was for (perhaps a removed feature?) but it made sense to use it for keeping a list of all notes because that list is used for auto completing tags!
I hope this change fits with the current push to add polish to Joplin.
> New tag adding dialogue

- ElectronClient/app/app.js
Fix #934
On linux if you try to change the layout with Alt + Shift, the menu
will open instead
> Desktop: Fix alt key using

- ReactNativeClient/lib/components/note-body-viewer.js
Minor UI fix: set background color based on selected theme to note webview to avoid white background on scroll when dark theme is enabled.
Before:
After:
> Mobile: Set note webview background color

- ElectronClient/app/gui/SideBar.jsx
The delete dialog for notebooks and tags does not display the name of the item to be deleted.
This can lead to an undesired result.
closes #1245
The dialog now looks like this:
---
Please note that I do not know how to update the `.pot` and `.po` files. Is there a script to do this? I doubt this is a manual process.
> when deleting notebook or tag, display name

- CliClient/locales/pt_BR.po
Updated locale because unicode escapes were not  showing up correctly. Inserted unicode chars without escaping.
> Updated pt_BR locale to correct unicode char escapes.

- CliClient/locales/ca.po
- CliClient/locales/cs_CZ.po
- CliClient/locales/da_DK.po
- CliClient/locales/de_DE.po
- CliClient/locales/en_GB.po
- CliClient/locales/es_ES.po
- CliClient/locales/eu.po
- CliClient/locales/fr_FR.po
- CliClient/locales/gl_ES.po
- CliClient/locales/hr_HR.po
- CliClient/locales/it_IT.po
- CliClient/locales/ja_JP.po
- CliClient/locales/joplin.pot
- CliClient/locales/ko.po
- CliClient/locales/nb_NO.po
- CliClient/locales/nl_BE.po
- CliClient/locales/nl_NL.po
- CliClient/locales/pt_BR.po
- CliClient/locales/ro.po
- CliClient/locales/ru_RU.po
- CliClient/locales/sl_SI.po
- CliClient/locales/sv.po
- CliClient/locales/tr_TR.po
- CliClient/locales/zh_CN.po
- CliClient/locales/zh_TW.po
- ElectronClient/app/checkForUpdates.js
- ReactNativeClient/lib/components/screens/config.js
- update the version info string for mobiles to be consistent with the desktop app
- show version as `X.Y.Z` in update dialog
- update `.po` files (and `.pot`) so that the previous commit won't break translations
- small update to `de_DE.po`
Please don't forget to update the translations. The `build-translation.js` script doesn't work on my system out of the box. I would have to change the script, since I'm using MacPorts. Also I'd have to install pocount.
> version info changes

- Joplin_install_and_update.sh
Fairly simple pull since the mate and xfce environments also use desktop files, this writes desktop files for those environments. Additionally it adds a note if a file was not created.
> Add joplin.desktop file for xfce and mate desktops

- ElectronClient/app/gui/NoteText.jsx
I'm not sure why this was set to true before but in either case I wasn't getting any errors myself.
I think this should fix https://discourse.joplin.cozic.net/t/intermittent-hangs-on-debian/1944/4.
> Set blockScrolling to Infinity (fixes error message)

- Joplin_install_and_update.sh
> Replace curl with wget in installation script

- ElectronClient/app/ElectronAppWrapper.js
This change improves font rendering for the electron desktop client.
For subpixel rendering to work electron requires the background to be non-transparent.  
This has to be set as an option for the BrowserWindow, see https://github.com/electron/electron/pull/16459/files
> Desktop: fix sub pixel rendering

- ElectronClient/app/gui/Header.jsx
This makes sure the text in the search bar aligns with the texts of the buttons and makes for an overall more pleasant spacing. See screenshots below.
> Desktop: improve search bar text alignment

- ElectronClient/app/app.js
/ref https://discourse.joplin.cozic.net/t/another-detailed-features-put-preferences-in-the-right-menu/1854/
> macOS: make the menu more like a macOS menu

- ReactNativeClient/lib/reducer.js
This commit will fix #1383.
Tried several fixes, but I think this kind of quick-n-dirty fix is the most reasonable. Debugging shows that the root issue surrounds that the render method at NoteTest.jsx is run frequently, and a timing issue in the state can occur. Pausing on a break point actually "fixed" the issue.
> All: 1383 Clear selected Notes when switching Notebook

- ReactNativeClient/lib/MdToHtml.js
- ReactNativeClient/lib/models/Setting.js
This PR adds an option to settings to use the traditional line-break behavior.
It is marked as `Work In Progress` because of the following 2 items:
- I added the option under `General` because it's a general markdown setting. We can always move it to a different section.
- I used a separate variable `breaks_`, because I thought it made the code more readable. I can remove it and use the ternary operation directly. Please advise.
> add option to use soft breaks for markdown rendering

- Tools/build-translation.js
en_US is basically always at 100%, but since it is not necessary to translate the common words/sentences, it currently shows only 7%.
> build-translation.js: hack to show en_US as 100%

- ElectronClient/app/gui/MainScreen.jsx
This change is based on proposed design updates I posted in the forums. [This is the related thread](https://discourse.joplinapp.org/t/some-design-suggestions-is-this-worth-implementing/2212).
I'm posting this as a different PR because I think it's the only change that could behave different in other operating systems than the one tested (I tested on MacOS 10.13.6).
> Desktop: removed gaps between NoteList and vertical resizers.

- CliClient/package-lock.json
- CliClient/package.json
- ReactNativeClient/lib/shim-init-node.js
This PR is part 1 / 2 of what is needed to make joplin cli compatible with node 12.
Part 2 will be to update `sqlite3` to a version with node 12 support. Unfortunately [the fix for it](https://github.com/mapbox/node-sqlite3/commit/723de4ca89924d464454f37b469dd1e801830632) didn't make it into a stable version yet (see also: https://github.com/mapbox/node-sqlite3/issues/1138), so we still have to wait for that.
This is currently the last remaining blocker for Homebrew to make all node formulae compatible with the latest current node 12 release in https://github.com/Homebrew/homebrew-core/pull/39188.
In this PR the version of the joplin cli dependency `sharp` is bumped from `0.20.8` to `0.22.1` [for node compatibility](https://sharp.pixelplumbing.com/en/stable/changelog/#v0221-25th-april-2019 …
> CLI: update sharp (for node 12 compatibility)

- ElectronClient/app/app.js
After discussion within #1434 let's remove the separator between New Notebook and Close Window in the File Menu.
> Desktop (macOS): Remove separator between New Notebook and Close Window in File Menu

- CliClient/tests/models_BaseItem.js
- CliClient/tests/models_Note.js
- ReactNativeClient/lib/models/BaseItem.js
- Fix: Serialize now leaves an empty line on .md file if title is empty.
- Possible Fix in displayTitle: if there's no title, call Note.defaultTitle(item). This is so the NoteList doesn't display an empty block when note has no title. It's for display only; it doesn't modify the original note. _I'm not sure if this can have any unintended consequences_
unserialize() could also be fixed to prevent loss of the second line as described in #1468, but if serialize works ok, it's unnecessary.
> Lib: fixes #1468, prevents notes with no title to break after synchronize.

- README.md
Fairly self explanatory. There have been enough people on the forums having issues with this [see here](https://discourse.joplinapp.org/t/userstyle-css-does-not-seem-to-work-in-windows-10/2294).
Ideally we'd have a nicer (cross-platform) method of applying css, but this should be enough for now.
> Update readme to warn about restarting the editor for userstyle

- ElectronClient/app/gui/NoteText.jsx
If you go to create a new note, and press ctrl+z (undo), it loads the contents of the previously selected note. This was fixed for existing notes, but not for new notes. The reference issue is #355
> Desktop: Resets the undo manager when creating new notes. Fixes #355

- ReactNativeClient/android/app/src/main/AndroidManifest.xml
- ReactNativeClient/android/app/src/main/res/xml/network_security_config.xml
- readme/faq.md
This will enable connecting to servers with self-signed certificates on
android as per issue #680.
Users are required to install their generated root CA in android settings: https://support.google.com/nexus/answer/2844832?hl=en-GB
Implemented as per:
- https://android-developers.googleblog.com/2016/07/changes-to-trusted-certificate.html
- https://github.com/facebook/react-native/issues/20488
I've tested this on an emulator and my android device with a server running on certificates generated with [mkcert](https://github.com/FiloSottile/mkcert)
> Android: Allow User-added CAs

- CliClient/package-lock.json
- CliClient/package.json
Node 12 necessitated some changes in sqlite3. These are now done via v4.0.7, bump package.json.
> CLI: fix: bump sqlite3 to v4.0.7 for node12 support

- CONTRIBUTING.md
- Added some guidelines based on suggested ideas from [the forum](https://discourse.joplinapp.org/t/contributing-md-suggestions/2317/8)
- Moved some rules to bulleted lists (for quicker reading).
- When possible, moved the main idea of sentences to the beginning of the sentences (for example: "The _Joplin Forum_ is the...place for user support", instead of "For general support, software questions...go to the _Joplin Forum_")
> Github: updated Contributing.md

- ElectronClient/app/gui/NoteText.jsx
I'm adding the $quotes property to the Ace Mode dynamically. The code also modifies the getNextLineIndent() method for the Mode a line after my change, so I assume this is the correct place for the code. 
$quotes is undefined by default. Ace recently added this to [their markdown mode](https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/markdown.js). However, they don't add single quotes. I added single quotes they work in the current editor, so not to break any functionality.
I tested with [ { " ' ( `
@tessus can you test if this works? Ace documentation is either frustrating or non-existent! so I'm just adding this based on what you posted on #1426, and it magically works.
> Desktop: Fix for #1426, backticks added to auto-wrapping quotes.

- Joplin_install_and_update.sh
Addresses this [forum issue](https://discourse.joplinapp.org/t/how-to-open-appimage-in-linux-ubuntu-18-4-64bit/2419)
> Only delete the .desktop file if it will be replaced by the script

- ReactNativeClient/lib/models/Setting.js
For some reason the default sort order is title and descending. In a github or forum topic it was established that this was actually a mistake, so this change fixes this.
> default sort order for notebooks should be title and ascending

- ElectronClient/app/gui/Header.jsx
When you search for notes, and then click on a notebook or tag, you effectively go out of the search UI, but I fixed the following:
1. search input should reset to show you're out of the search (#1186)
2. the search query should reset, otherwise you'll still see highlighted matches in notes (#1354)
3. Unrequested bonus: you can know hit Escape to clear the field. This mimics the behavior of the local search field.
I'm using notesParentType, which is "Search" when you're searching, or "Folder" if you have a folder selected.
It's not optimal to do this in componentDidUpdate, but the options were:
- using componentWillReceiveProps, which is deprecated and causes other small issues.
- Mess with the global data handled by lib, which could affect the other apps and cause more issues than it …
> Desktop: Fixes #1186, #1354. Clears search when clicking on a notebook.

- ElectronClient/app/package-lock.json
- ElectronClient/app/package.json
- ReactNativeClient/lib/MdToHtml.js
[Discussion here](https://discourse.joplinapp.org/t/tables-with-merged-split-cells/1760/12)
> Update multimd-table and enable options

- ReactNativeClient/package.json
I forgot to bump the version of the table plugin when updating. One of the table options isn't supported in the older version, to my knowledge no one is using this option yet.
> Mobile: Bump version of multimd-tables for mobile

- ElectronClient/app/theme.js
#1594 @dincsi mentioned an issue with how font size is set in theme.js. This pull makes the code a bit better and adds a comment to explain the theme.js font behavior.
> Desktop: Clean up theme.js font settings

- Joplin_install_and_update.sh
- Icon softcoding path
- Icon directory
In reference to #1611
> CLI for Linux: Icon softcoding path and directory

- ElectronClient/app/gui/MainScreen.jsx
- ElectronClient/app/gui/PromptDialog.jsx
- ElectronClient/app/package-lock.json
- ElectronClient/app/package.json
I finally found a stable input that we can use for tags, [react-select](https://react-select.com/home)
It's very flexible which means we can change the behaviour however we like.
One thing I was sure about is deleting tags with backspace.
Currently the user cannot delete tags by pressing backspace while the cursor is next to an item. I intentionally disabled this to prevent users from accidentally deleting tags. Personally I would prefer to delete using backspace, so I thought I would reach out for opinions and see what others felt would be the most sane behavior.
edit: fixes #1535
> Desktop: Use the react-select library for tag input

- ElectronClient/app/app.js
- ElectronClient/app/gui/NoteText.jsx
- revert 7dee930
- add shortcut ``` cmd+` ``` / ``` ctrl+` ```
- add menu item for `Inline code`
> Backtick changes

- Tools/release-clipper.js
The file `joplin-webclipper-source.zip` will be in the `dist` directory of the webclipper.
As discussed earlier, I've finally modified the `release-clipper.js` script to create a source tarball for validation as required by the Mozilla add-on store.
Btw, not related to this PR, the `npm run build` command throws several warnings.
> release-clipper.js: create a zip file of the source (for validation)

- ReactNativeClient/lib/services/ExternalEditWatcher.js
Fixes the [gedit issue from the forums](https://discourse.joplinapp.org/t/bug-saving-notes-in-external-editor/2673/3)
I'm a bit wary adding in a change like this, but it doesn't seem to introduce any issues on my machine.
This was added based on a [chokidar issue](https://github.com/paulmillr/chokidar/issues/591) at some point I think chokidar will be fixed and this bit of code can be removed.
I tested this with gedit and gvim, it fixes the issue for both.
I think this also fixes #1614 but it might need more testing.
> Watch for rename events in the external editor and re-watch file

- ElectronClient/app/gui/NoteText.jsx
> fix: add override for ACE editor shortcut `Ctrl+K`

- Joplin_install_and_update.sh
For [reference](https://discourse.joplinapp.org/t/unable-to-install-on-linux-mint-19-cinnamon/2800/14)
> Add support for cinnamon to install script

- ReactNativeClient/lib/components/screens/note.js
I was finally able to get `react-native run-android` working, thus I tested the change accordingly.
see also #1745
> mobile: show correct time/date (as specified in settings) for note properties

- ElectronClient/app/gui/NoteText.jsx
- ElectronClient/app/theme.js
- ReactNativeClient/lib/models/Setting.js
This PR adds two themes to the desktop client: Solarized Light and Solarized Dark.
Solarized homepage: https://ethanschoonover.com/solarized/
I've tested the desktop client, but I couldn't get the android toolchain installed to test the mobile client.
For reference, this is the solarized color palette, in pseudo-css form:
```css
solarized {
Base03:  #002b36;  // dark background
Base02:  #073642;
Base01:  #586e75;
Base00:  #657b83;  // light text
Base0:   #839496;
Base1:   #93a1a1;  // dark text
Base2:   #eee8d5;
Base3:   #fdf6e3;  // light background
Yellow:  #b58900;
Orange:  #cb4b16;
Red:     #dc322f;
Magenta: #d33682;
Violet:  #6c71c4;
Blue:    #268bd2
Cyan:    #2aa198
Green:   #859900
}
```
> Desktop: Add solarized themes

- CliClient/locales/it_IT.po
Changed _cancel_ from "cancellare" to "**annullare**" (which is used more to express the cancelling operation) and _delete_ from "cancellare" to "**eliminare**". I think that doing this will help people understanding what is the main task of these option since they use the same verbs in the current translation.
I have also changed the word _directory_ to "**cartella**" since it's its name in italian on most OSs.
I think this translations are more focused on the general user which might not know the word _directory_ and might be afraid of accidentally deleting files.
> [Mobile/Desktop] Changed cancel, directory and delete translations (ITALIAN) 

- ElectronClient/app/theme.js
Following on from https://github.com/laurent22/joplin/pull/1733, this PR adds the `depthColor` property to the new Solarized Light and Dark themes.
They've basically been copied from the Light and Dark themes respectively, I think it looks pretty good:
These could probably be tuned better, but I'm no good with color so 🤷
> Desktop: add `depthColor` for solarized light and dark themes

- CliClient/tests/pathUtils.js
- ElectronClient/app/gui/NoteText.jsx
- README.md
- ReactNativeClient/lib/path-utils.js
- ReactNativeClient/lib/shim-init-node.js
Following on some discussion in [REF1](https://discourse.joplinapp.org/t/feature-request/1408/6) and [REF2]( https://discourse.joplinapp.org/t/file-paths-with-german-umlaut-do-not-work-for-me/793), I have tried to figure out an easy way to use fileURLs without entering the link syntax by hand.
To accomplish this, I have altered the drag and drop file behaviour in Joplin slightly. If drag and drop is performed while pressing the ALT-key, a fileURL is embedded in the note text, (the file is not embedded into the Joplin resources). This can be done with a single file or multiple files (just as in the standard drag and drop feature).
The fileURL syntax is `[NAME](file://FILEPATH)`
The FILEPATH complies with the format already used by Joplin (i.e. ‘+’ is escaped with Unicode, + sign escapes …
> Desktop: Create fileURLs via drag and drop

- CliClient/tests/enex_to_md/text_formatting.html
- CliClient/tests/enex_to_md/text_formatting.md
- CliClient/tests/enex_to_md/text_formatting_span_bold.html
- CliClient/tests/enex_to_md/text_formatting_span_bold.md
- ReactNativeClient/lib/import-enex-md-gen.js
Hi, I added a draft feature to detect some styles buried inside of span tags. Evernote did that very often to my notes. E.g. most of my bold text was saved as inline styles in span tags and not  as `<b>` or `<strong>` tags. This feature is far from perfect but I wanted to discuss things further before moving on. I read the contribution guidelines and tried to follow them but I didn't write a unit test yet. I will if it is necessary.
I am aware of the following issues:
* It detects either bold or italic or monospace - bold and italic should be supported i think. monospace and bold/italic should be ignored - the most likely case is people use monospace text to show code. I think it is not possible in MD to format stuff eg bold inside of \`code\` sections? Right?
* the string comparision …
> Desktop,Cli: enex_to_md: support bold formatting in span tags

- ElectronClient/app/gui/NoteText.jsx
fixes #1743
---
When a document is printed or exported to PDF, a header 1 is prepended to the document with the title (internally adding a `# Title`).
This also adds an additional entry to the TOC with the title of the document. This PR fixes this behavior. I've also added a helper function to change the appearance in the future.
> fix: better handling of adding the title to print and export to PDF

- ElectronClient/app/gui/PromptDialog.jsx
- ReactNativeClient/lib/TemplateUtils.js
Addresses [this topic](https://discourse.joplinapp.org/t/minor-issues-with-templates/3194) in the forum.
Note: I wasn't able to reproduce his second issue (sort order). But I put some sorting code in, hopefully that will fix it.
> Desktop: Change template prompt to sans and sort templates

- ElectronClient/app/gui/MainScreen.jsx
This makes the tag sorting function also ignore case.
In general tags are lowercase, sometimes that doesn't happen when they've been imported from enex. This keeps everything consistent. 
See [this comment](https://github.com/laurent22/joplin/pull/1806/files/c77f47ef514225540819bde18369af6819ae8175#r314447426) on some similar code.
> Desktop: Change localeCompare functiion for tags

- ReactNativeClient/lib/BaseApplication.js
- ReactNativeClient/lib/time-utils.js
[reference](https://discourse.joplinapp.org/t/1-0-165-timestamp-formatting-in-new-template/3219/7?u=calebjohn)
Example of template after switching the language around
> Set locale in time-utils

- Joplin_install_and_update.sh
$desktop was converted to lowercase, but matched against 'X-Cinnamon'
> Desktop: Fix Cinnamon Detection

- docs/e2ee/index.html
As per https://discourse.joplinapp.org/t/totally-confused-re-e2ee/3295, I tried to improve the explanation of the process to avoid multiple encryption keys.
> Update explanation of enabling E2EE

- .gitignore
- .vscode/settings.json
- ReactNativeClient/lib/components/global-style.js
- ReactNativeClient/lib/components/screens/note.js
- ReactNativeClient/lib/models/Setting.js
- ReactNativeClient/lib/shim-init-react.js
- ReactNativeClient/lib/shim.js
Enables user to select the font they want to use in the Joplin mobile editor. 
Partially addresses https://github.com/laurent22/joplin/issues/337.
I could add something similar for the rendered note font (i.e. the page before the editor).
> Custom mobile editor font

- ElectronClient/app/gui/NoteText.jsx
The new linter changed the string formatting a bit, but it still works.
fixes #1606 which was closed by the stale bot.
> Desktop: Code button now detects multiline

- CliClient/app/command-e2ee.js
#1656
Same idea as https://github.com/laurent22/joplin/pull/1936 except for the CLI instead of Desktop.
Successful flow:
https://gyazo.com/354ca9ea412ffe3756ee77938d544341
Flow with error (non-matching passwords):
https://gyazo.com/9adda69278e3631da33d9fb366815d04
> CLI: confirm encryption password

- README.md
Building can take a lot of time on some less performing computers (like mine) so an already compiled version can save a lot of time.
About the chaotic-aur:
https://lonewolf.pedrohlc.com/chaotic-aur/
http://lonewolf-builder.duckdns.org/chaotic-aur/x86_64/
> Add AUR repository

- ElectronClient/app/gui/Header.jsx
As per the previous discussions on the issue https://github.com/laurent22/joplin/issues/917, I've made the search bar for the desktop application a bit larger. In addition to this, I also added some margin before the search bar as I've always felt that the search bar is a bit too close to other items on the header.
@laurent22 Happy to hear your thoughts on this.
> Desktop: Larger search bar

- ElectronClient/app/gui/NoteText.jsx
addresses issue: https://github.com/laurent22/joplin/issues/1896
_editor visible, preview visible_
_editor visible, preview NOT visible_
_editor NOT visible, preview visible (NEW BEHAVIOR)_
> Desktop: hide some toolbar buttons when editor hidden

- ReactNativeClient/lib/components/CameraView.js
Added toggle switch to use front camera. React-native-camera by default uses back camera if the specified camera (front) is not found. Tested on Android and iOS(Simulator, no real images just blackscreens with the date attached).
> Mobile: Added Front Camera toggle when taking a picture with Joplin Camera

- ElectronClient/app/gui/SideBar.jsx
and rename buttons (delete, remove) and context menu (for tags)
fixes #1662 (partially, because I can't fix the upstream issue, unless we update Electron)
Please note that the reason for `Cancel` not being selected is an upstream issue. But this was already the case for the `delete note dialog` (see below).
Therefore I made everything more consistent.
> Desktop: set cancel as the default in dangerous operations

- ElectronClient/app/gui/MainScreen.jsx
- ElectronClient/app/style.css
Small upgrade to the import/export pages, per discussion in https://github.com/laurent22/joplin/issues/1862.
Here's how it looks while you're waiting for an export to complete:
> Desktop: Add loading animation to import/export

- Joplin_install_and_update.sh
The script is currently failing to generate icons (and the .desktop file).
This is caused by a minor naming mistake.
> Minor fix to install script

- Joplin_install_and_update.sh
After running the install script, Joplin is placed under "Other" in my applications menu.
This happens because the `Categories` value in `joplin.desktop` is not in [the FreeDesktop specification](https://standards.freedesktop.org/menu-spec/latest/apa.html).
This pull request fixes it, changing to the most suitable IMO: Office. Do feel free to pick other.
> Linux install script: Fix category

- ReactNativeClient/lib/renderers/MdToHtml/rules/link_open.js
This pull does 2 things.
1. Actually allows the user to set a markdown link title for resource URLs and internal links
e.g
`[internal link](:/51bee0f048994f81a7cbca4e7627ad13 "title")`
2. Display the stored resource title for resources on hover.
From what I can tell, this field is always the original filename, is that correct @laurent22 ? This will be useful because it will allow users to hover over a resource to get some additional info.
My other motivation for adding that is it will allow for joplin to display the filetype [instead of the resource icon](https://discourse.joplinapp.org/t/set-of-icons-for-attachments/2813) when filetypes are known. Users can do this manually using css, or if you're open to it, I can make a pull request that will make it a feature in Joplin.
> Desktop: Improved resource hover title

- ReactNativeClient/lib/components/screens/encryption-config.js
Issue: #1656
Same idea as #1936 except for Mobile
--
_Before_
_New UI:_
(Verified that it sets up encryption as normal if passwords match)
**Error cases**
_Errors if passwords don't match_
_Errors if either field is empty and you click "enable"_
> Mobile: confirm encryption password

- ElectronClient/app/app.js
If one closed the dev tools window, one could think that the Dev Tools are closed.
This is not the case. After the next action, the window opens again. This can be
confusing, therefore I added a checkmark to the menu item so that it is very clear.
> Desktop: add checkmark to menu item, if Dev Tools are on

- CliClient/tests/enex_to_md/text_formatting_span_italic.html
- CliClient/tests/enex_to_md/text_formatting_span_italic.md
- ReactNativeClient/lib/import-enex-md-gen.js
Hi, this should theoretically be a no-brainer. It is just an addition to the "span tags format conversion feature" you merged a couple of weeks ago (#1708). I also added a html and md pair test and it passes. Additionally I did a lot of testing with my old Evernote notes.
Anyway, I am experiencing an odd issue: Some tests don't pass and I think I didn't break them: 
```
Error converting file: mathjax_block.html
Error converting file: mathjax_inline.html
Error converting file: table_with_pipe.html
```
By any chance, are they currently broken or should they work?
Thanks
> Desktop, Cli: enex_to_md: support italic in span tags

- ReactNativeClient/lib/models/Setting.js
- ReactNativeClient/lib/renderers/MdToHtml.js
- readme/markdown.md
New plugin `Enable typographer support`.
> Desktop, Mobile: add typographer support

- ElectronClient/app/app.js
- ElectronClient/app/gui/MainScreen.jsx
- ElectronClient/app/gui/Root.jsx
- ElectronClient/app/gui/SideBar.jsx
- ReactNativeClient/lib/models/Setting.js
Here's my first feature request and pull request!
***
Related forum post: https://discourse.joplinapp.org/t/feature-idea-hide-note-list/3920
Related issue: https://github.com/laurent22/joplin/issues/1988
***
- new menu item: toggle note list visibility
- new toolbar button: to toggle note list visibility
- new feature: toggle actual note list visibility
- Is a toolbar button really needed?
- If yes, should we use another icon from the one used for toggle sidebar?
- Should we have a keyboard shortcut for that feature too? (toggle sidebar has one)
- Is there anything locale-wise (translations) I need to do about this new feature?
- **The part in `ReactNativeClient/lib/models/Setting.js` I added the setting in `ReactNativeClient` as well. Is it okay? I'm not sure about that change.** …
> Desktop: Add menu item to toggle note list #1988

- ReactNativeClient/lib/components/select-date-time-dialog.js
see https://discourse.joplinapp.org/t/alarm-does-not-display-the-date-in-the-system-format/4070?u=tessus
It now shows the date and time formats which are chosen in settings:
> Mobile: show alarm in correct date and time format

- ElectronClient/app/gui/NoteText.jsx
This fixes the Joplin->"other apps" half of
https://github.com/laurent22/joplin/issues/215.
> Desktop: Fill X primary selection from the editor on text selection

- ElectronClient/app/gui/NoteText.jsx
Fixes #1790.
This solution uses a simple print flag to reduce the chance of triggering the race condition. It's not as foolproof as an async lock, but I cannot reproduce the bug with the change added, and this check is much faster than a lock would be.
> Desktop: Fix #1790: Stop print command from resetting theme

- ReactNativeClient/lib/renderers/MdToHtml.js
> fix toc with special characters - finally

- CliClient/package-lock.json
- CliClient/package.json
This PR upgrades `sharp` to v0.23.2 for compatibility with `node` 13. This is needed to make the homebrew formula for `joplin` compatible with node 13 without manually patching it (see also #1471 for an older similar PR).
The test passes locally for me and I can still attach images via the CLI client.
Note: This will drop support for Node 6 in `sharp`, but it's EOL anyway (and you are requesting node 8+ too).
> CLI: update sharp tp v0.23.2 (for node 13 compatibility)

- ElectronClient/app/gui/NoteList.jsx
Bug fix for [#1570](https://github.com/laurent22/joplin/issues/1570).
Before the fix:
After the fix:
> Desktop: Prevent horizontal scrolling on Linux when a scrollbar is present in note list

- ElectronClient/app/gui/MainScreen.jsx
- ElectronClient/app/gui/NoteText.jsx
- ReactNativeClient/lib/models/Setting.js
This adds a new option to settings("Keyboard Mode"), and then sets the appropriate keyboard handler in the ace editor when it renders.
Options are:
- Vim
- Emacs
- Default
The "default" option is equivalent to the old keyboard behaviour, which (as far as I can tell) is informed by the OS the app is running on.
- A new option in the Appearance section (Keyboard Mode)
- When in Vim mode, a red block cursor, and vim-style keybindings
- When in Emacs mode, a green block cursor, and emacs-style keybindings
- When in default mode, keyboard behaves exactly as it did before, and nothing looks different
Vim Mode:
I'm not sure if these changes tread on any of the existing keyboard-shortcut functionality, and I expect that this feature will require some revision to add anything that's missing to the …
> Desktop: Add keyboard modes to editor (vim, emacs)

- ElectronClient/app/ElectronAppWrapper.js
A first, very simple commit that may help development of Joplin on differing environments.
When running in Developer mode (--env dev) the Chrome Dev Tools are always opened during preparation of the Renderer Process. The prevents use of other Node debugging tools.
This commit makes automatic opening of Dev Tools optional by checking for the --open-dev-tools flag in addition to --env dev.
> Desktop: Optional open dev tools in Developer Mode

- ReactNativeClient/lib/BaseApplication.js
To allow debuggers other than Chrome DevTools it may be necessary to pass command line arguments directly to Electron. Specifically [--remote-debugging-port](https://electronjs.org/docs/api/chrome-command-line-switches#--remote-debugging-portport). The cli argument parser implementation raises an exception against any unrecognized flag. This patch allows the flag and its argument to be ignored.
> Desktop: Allow Electron debugging flag 

- ReactNativeClient/lib/synchronizer.js
> Add warning message when user tries to upload a file 10MB or larger

- ReactNativeClient/lib/components/screens/notes.js
While analyzing this project via [lgtm](https://lgtm.com), I found this part of your code where the `title` variable is being used before its declaration. Since it was such a small fix of simply moving the variable declaration a couple lines up, I thought I'd open a quick PR for it. Feel free to disregard and close, if you don't like it, though. 👋
> Move variable declaration before its first use.

- ElectronClient/app/app.js
- ElectronClient/app/gui/NoteText.jsx
> NOTE: This is just a proposal. Apologies, I should've opened a thread in the forum but got a little carried away playing around with a solution here, so no pressure at all to take this one as-is. I've opened a thread now in case that's where you prefer to have the discussion: https://discourse.joplinapp.org/t/interested-in-supporting-custom-ace-tokens/4315
This PR adds support for the `highlight_mark` token specifically, and generally paves the way for additional custom tokens if we'd like to add more in the future. 
Here's the resulting html that's created when using the `==mark==` syntax:
This would play nicely with the proposed https://github.com/laurent22/joplin/pull/2099, which would allow for adding a custom style to associate with the custom token, for example:
> Desktop: Add highlight_mark token to Ace editor rules

- ElectronClient/app/app.js
see  https://discourse.joplinapp.org/t/icon-size-for-electron-about-window/4550?u=tessus
Icon in About window is blurry. This change fixes this.
> Desktop: better icon size for about window

- ElectronClient/app/app.js
- ElectronClient/app/gui/ConfigScreen.jsx
- README.md
- ReactNativeClient/lib/BaseApplication.js
- ReactNativeClient/lib/CssUtils.js
- ReactNativeClient/lib/layout-utils.js
- ReactNativeClient/lib/models/Setting.js
- ReactNativeClient/lib/shim-init-node.js
- ReactNativeClient/lib/shim.js
_Discussed in https://discourse.joplinapp.org/t/custom-stylessheets/384/12?u=devonzuegel_
This allows users to define custom Ace editor styles in `editor.css`, similar to how they can define custom styles for the rendered Markdown pane in `userstyle.css`.
For example, I've added this to my `~/.config/joplindev-desktop/editor.css`:
... which in this case italicizes and bolds the `emphasis` tokens in the Ace editor and puts an ugly orange background in place of the default blue sidebar color:
I'd be curious to get @laurent22's perspective though before I go further with this. Three things I'd want to improve if you are interested in this general concept before this is a real PR ready for review:
1. [FIXED] ~The naming I went with is not very elegant alongside the `userstyle.css` file. If I …
> Desktop: Allow for custom Joplin theme and Ace editor styles

- CliClient/locales/es_ES.po
- Delete hyphens after prefix "pre", to be compliant with Spanish prefixes rules
- Delete duplicated spaces
- Add translation for "Custom stylesheet for Joplin-wide app styles"
> Fixing errata in CliClient/locales/es_ES.po

- CliClient/app/command-config.js
Added three options to the `joplin config` command. These options are intended to be used with the command only , not with the CLI GUI.
- `joplin config --export [-v]`: This is the normal `joplin config` command, except modified to:
1. Write to stdout without any of the beautification done for the CLI Client `<name>=<value`
2. Write out secrets in plaintext
- `joplin config --import`: This reads settings from STDIN line by line in the format `<name>=<value>`
- `joplin config --import-file <file-path>`: Same as `joplin config --import`, but from a file.
This even seems to work with encryption, though that's more of a pleasant side effect.
Use cases:
- Bootstrapping a new machine. You could run these commands to create/update the profile before starting the Desktop app or CLI app.
- Could …
> CLI: Add --export, --import, and --import-file flags to joplin config

- ElectronClient/app/gui/ItemList.jsx
> Desktop: Fix Goto scrolling (#2122)

- ElectronClient/app/gui/MainScreen.jsx
- ElectronClient/app/gui/NoteList.jsx
- ElectronClient/app/gui/NoteText.jsx
- ElectronClient/app/gui/utils/NoteListUtils.js
~Also start up external editor on note double click.~
These changes enhance user experience by placing the actions where they feel natural.
> Desktop: Add external editor actions to the note context menu.

- ElectronClient/app/gui/NoteText.jsx
- ElectronClient/app/gui/TagList.jsx
- ReactNativeClient/lib/components/shared/reduxSharedMiddleware.js
Follow up to #893
Now using middleware to set the tags when a note is selected
This avoids the ugly code in the NoteTextComponent where we determine
if tags are to be fetched, identify if they have been modified, fetch
them  and then dispatch an action to update the store which might
again re-render the component.
Also implements style related fixes from #1000
Fixes: #469
- Proper margin between toolbars when,
> Desktop: Display selected tags under a note title

- ElectronClient/app/gui/NoteText.jsx
- ReactNativeClient/lib/models/Setting.js
This is a very simple fix, the only complexity was trying to understand the ace documentation :(
This was [requested on the forum](https://discourse.joplinapp.org/t/feature-un-request-back-tick-quote-balancing/2626/6)
> Desktop: Add option to disable auto-matching braces

- ElectronClient/app/app.js
- ElectronClient/app/gui/NoteText.jsx
- ElectronClient/app/gui/utils/NoteListUtils.js
Proposed fix for issue #2254 
The fix ensures the current note is used when it is not in the set of selected notes, which can happen when the user right-clicks on an unselected note in the note list.
> Desktop: Fix pdf export for current but unselected note.

- CliClient/tests/models_Folder.js
- ReactNativeClient/lib/BaseApplication.js
- ReactNativeClient/lib/folders-screen-utils.js
- ReactNativeClient/lib/models/Folder.js
If completed to-dos are not shown, they should not be included in the note counts.  This makes to-do list functionality better as you can have the count show only the remaining to-dos.
> Desktop: don't count completed to-dos in note counts when they are not shown

- CliClient/tests/reducer.js
- ReactNativeClient/lib/reducer.js
**Issue**
The issue was raised here:  [forum thread](https://discourse.joplinapp.org/t/deleting-a-note-sometimes-triggers-an-unnecessary-change-in-selection/4995)  
The issue is that in the note list, when a note is selected and another is deleted, the selection is changed.
In my opinion, it should not. The selection should only change if the **selected** note/s is deleted.
**Solution**
The change is implemented by adjusting the logic in the reducer's `handleItemDelete`.  As a result, this change addresses the same issue that exists for notes, notebooks and tags.
**Testing**
No unit tests existed for the reducer so new unit tests are created here. These unit tests only cover the functionality affected by this change.  Manual testing was done on the desktop client.
**Alternative solution** …
> Desktop: Maintain selection when non-selected note is deleted

- ElectronClient/app/gui/NotePropertiesDialog.jsx
My use case is that I will often complete a task by checking it off, then go back to add more notes at a later date.  This will change the modified date, but it's useful to be able to see when a task was first completed.  Fortunately Joplin already keeps track of this so it's a simple change to add it to the GUI.
> Desktop: show time completed in note properties

- ElectronClient/app/gui/NoteText.jsx
This fix is for a bug in the "show tags on note" feature (new feature, created in #2217, merged onto master but not yet released).
The bug causes notes to be shown with wrong tags.
To reproduce:
1. Create three notes, say `Note1`, `Note2`, `Note3`
2. Add tag `AAA` to `Note1`
3. Add tag `BBB` to `Note2`
4. Select `Note3` in the note list
5. Select `Note1` in the note list
6. Select `Note2` in the note list
Expected result: `Note2` is shown with tag `BBB`
Observed result: `Note2` is shown with tag `AAA`
The bug is because the function that compares tag lists only checks that the tag lists contain the same number of tags, and the timestamps for matching tags are the same. The fix is to ensure that all the tag ids match as well, ie it ensures the lists actually contain the same tags.
> Desktop: Fix for wrong tags shown on note

- README.md
Yandex Disk (cloud storage by Yandex) supports WebDAV access and is known to work with Joplin.
> Added 'Yandex Disk' to the list of WebDAV-compatible services known to work with Joplin.

- Joplin_install_and_update.sh
Just gives a 404 for me currently.
> Linux Installer: "-x86_64" is not part of the AppImage release name

- CliClient/locales/ru_RU.po
* fact errors corrected
* all non-ASCII symbols converted to ACSII to be correctly displayed even in console app (e.g. quotation marks, em dash, etc.)
* unified translation across the whole file:
* `geolocation` -> `географическое местоположение`
* `URL` ->`URL-адрес`
* `match` -> `соответствовать выражению`
* `folder` -> `каталог`
* `upload` -> `выгрузка`
* `download` -> `загрузка`
* `информация об использовании` -> `справочная информация`
* `shortcut` -> `сочетание клавиш`
* `item` -> `элемент`
* linguistic calques translated
* `release` -> `релиз` (calque) -> `выпуск`
* `log` -> `лог` (calque) -> `журнал`
* `tag` -> `тэг` (calque) -> `метка`
* `tray` - should it be translated to `лоток` or not?
* should non-translatable strings be included in this file? E.g. non-ANSI paper sizes like …
> ru_RU translation updated and unified

- Tools/package-lock.json
- Tools/package.json
The maintainer is no longer supporting any version of cryptiles before
v4.2.0 on npm; npm's older versions stop at 3.1.2 and a high security
vulnerability was thrown during a build on linux: https://npmjs.com/advisories/720
The maintainer still has 3.1.4 tagged in his repo and this commit
updates cryptiles to solve that issue without breaking compatibility
since it was primarily bug fixes for a code freeze.
EDIT: After talking a bit on here with both @laurent22 and @tessus and running basic tests on the app after building, it doesn't look like Request 2.88.0 breaks anything and they have dropped support for dependencies on Hawk and Cryptiles while also keeping the overall api the same.
> Updated Request to v2.88.0 to remove dependency on Outdated and Insecure Hawk and Cryptiles Dependencies

- ElectronClient/app/ElectronAppWrapper.js
- ElectronClient/app/app.js
This change fixes the following deprecation:
```
(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
```
> Desktop: fix deprecation of getName() in Electron

- ReactNativeClient/lib/reducer.js
Fixes #2371 
During investigation, also found the same type of bug affects search results, so fixed that too.
The search version of the bug is:
1. Start with default profile
2. Search for `Joplin`
3. Select multiple notes in the note list
4. Modify the search eg add a character to make it `Joplinx`
Expected result: Note list shows new results
Observed result: Entire Joplin window renders white
Tested fix manually on desktop
Did not reproduce bug or test fix on CLI or mobile.
> Fix hang when selecting tag when multiple notes are selected (also for search)

- BUILD.md
When i was trying to build the Electron Project, i was a bit confused about which commands to follow for building in the projects on my OS (Windows).
there was two headers,   **Building the Electron application** and   **Building the Electron application for windows**.
the former can lead a beginner to confusion because it seems to be "a generalized statement", unlike the latter that was more specific. 
In order to improve the developers experience, i had to change the former heading to **Building the Electron application for Linux and macOS** to help them understand easily.
> Change to the documentation: Edits build instructions to avoid confusion

- Joplin_install_and_update.sh
- version attribute inside `joplin.desktop` is `X-AppImage-Version` and not `X-AppImage-BuildId`
- format is `X-AppImage-Version=X.Y.Z"` so we need to change `cut` parameters (split on '=' and get 2nd value)
> Desktop: version attribute inside `joplin.desktop` is `X-AppImage-Version`

- ElectronClient/app/app.js
- ReactNativeClient/lib/joplin-database.js
Resolves #2280
Adds version information to profile error message
Add profile error message to log
Error message:
About box:
Log messages
> 2020-01-19 03:31:18: "Database was open successfully"
2020-01-19 03:31:18: "Checking for database schema update..."
2020-01-19 03:31:18: "Current database version", "28"
2020-01-19 03:31:18: "Cannot convert database from version 28 to 27"
Tested manually on
-  Electron (error msg, log msg, about box)
-  CliClient (error msg, log msg)
-  Mobile (error msg, but did not check log msg because not sure where to find it)
For further details see previous abandoned pull request #2313
> More info for "unknown profile version" error message

- CliClient/tests/reducer.js
- ElectronClient/app/gui/NoteList.jsx
- ElectronClient/app/gui/SideBar.jsx
- ReactNativeClient/lib/reducer.js
Please consider this PR for enhancing the "select all" function in Joplin.
As mentioned in [forum](https://discourse.joplinapp.org/t/desktop-select-all-in-the-note-list/5491)
- When focus is in the note list, "select all" selects all notes.
- When in the folder list, "select all" does nothing.
- When in the tag list, "select all" does nothing.
- The key combination "select all" is "Ctrl-A" or "Cmd-A"
For reference, the current behaviour is this:
Check 'select all' works:
If the note list is short, and "select all" is actioned below the last note, the application menus are selected. I would like to stop this too, but don't know where to catch it.  So leaving it as is for now.
> Desktop: Support "select all" in the note list

- CliClient/tests/models_Note.js
- ReactNativeClient/lib/models/Note.js
I'd like to say many thanks for the great product! I really like Joplin!
I enjoy sorting by created date for Notes, but unfortunately, when I duplicate a Note, it breaks the sorting. I found out that during duplication we reset only `id`. I'm not sure if it's appropriate, but I feel it might be reasonable to reset `created_time` and `updated_time` fields as well. I couldn't find a reason we need to carry over these fields to a duplicated Note. Might be I missed something, let me know if it's not a great idea resetting these fields.
1. Reset id, created_time, updated_time, user_created_time, user_updated_time fields when duplicate a `Note`
> Reset created and updated times for a duplicate Note

- ReactNativeClient/lib/BaseApplication.js
The change allows `--no-sandbox` flag at Joplin desktop app startup. This enables the users to optionally run the app without the electron sandbox as a workaround for the electron + AppImage package issue discussed in https://github.com/laurent22/joplin/issues/2246.
> Desktop: Ignore no-sandbox start flag at joplin startup

- ElectronClient/app/ElectronAppWrapper.js
The bug is described in details in https://github.com/laurent22/joplin/issues/2365. 
Currently, starting in tray is implemented by creating a hidden main window, and making it visible only if starting in tray is disabled. However, just after the creation of the window, a listener from the package `electron-window-state` is registered on the window. This listener makes the window visible again when restoring from a **maximized** window state as a side-effect. This can be replicated by setting the `isMaximized` property to `true` in `window-state-{dev,prod}.json` located in `~/.config/Joplin/`(Linux) or `%APPDATA%\Joplin\`(Windows).
This PR hides the window again after registering the listener, preventing the window from being shown.
> Desktop: Fix #2365 by ensuring the main window is hidden when Joplin starts

- CliClient/tests/models_Tag.js
- ElectronClient/app/app.js
- ElectronClient/app/gui/MainScreen.jsx
- ElectronClient/app/gui/NoteText.jsx
- ElectronClient/app/gui/utils/NoteListUtils.js
- ReactNativeClient/lib/models/Tag.js
Resolves #359 
When multiple notes are selected and add or remove tags is actioned
- the list of common tags is presented in the dialog
- the additions and deletions are applied to each selected note
When one note is selected and add or remove tags is actioned:
- behaviour is unchanged from current
Manual tests
Enhancement suggestion: When multiple notes are selected, the `add or remove tags` dialog only shows tags that are common to all selected notes. Tags that are on only some notes are not shown.  An enhancement might be to show these tags in the dialog too, perhaps in faded or broken boxes, and interactive.
> Desktop: Add `add or remove tags` for multiple notes.

- ReactNativeClient/lib/joplin-renderer/noteStyle.js
**"Desktop" for the Windows/macOS/Linux app (Electron app)**
- This change allows warping long lines in the view area of note editor.
- Reference of the issue #2170
> Desktop: fixes long lines warpped

- ElectronClient/app/gui/NoteText.jsx
Resolves #1014 
The existing behaviour is to insert a blank line before the new list item (if not creating a list item on a single empty line).  Is there a reason for this (is it intended)?
If the action is undone (Ctrl-Z) the new selected area is incorrect ie it is different to that previously selected. This seems to be a pre-existing issue.
> Desktop: Support list creation on multi-line selections

- ElectronClient/app/InteropServiceHelper.js
- ElectronClient/app/bridge.js
Fixes #2407
When a print is cancelled, Joplin shows an error box: "Could not print".
This PR ensures the error box is only shown in case of print **error**, and not when the print is **cancelled**.
The issue also found the "OK" button is missing from error dialogs on Linux.  This PR  ensures the button is shown on all platforms.
> Desktop: Do not show "could not print" warning dialog after cancelling print.

- ElectronClient/app/gui/NoteList.jsx
Please consider this PR to implement navigation in the note list using standard keys.
Currently using navigation keys in the note list does not work after the first key. This PR implements these functions for standard keys (Mac, Windows, Linux):
**Navigation**  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;**Key**
Up one line  &nbsp; &nbsp;&nbsp;&nbsp; &nbsp; `Up`&nbsp;&nbsp;&nbsp; (already supported)
Down one line  &nbsp;&nbsp; `Down`&nbsp;&nbsp;&nbsp; (already supported)
Up one page &nbsp;&nbsp;&nbsp;&nbsp; `Page Up`
Down one page `Page Down`
Start of list  &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; `Cmd+Up`, `Ctrl+Home`
End of list   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp; `Cmd+Down`, `Ctrl+End`
Manual testing in note list:
If the user has scrolled the selected item off the screen, …
> Desktop: Support scrolling in the note list using keys (eg page up, page down)

- CliClient/tests/markdownUtils.js
- ReactNativeClient/lib/markdownUtils.js
- ReactNativeClient/lib/models/BaseItem.js
Previously a title with brackets was escaped incorrectly. The brackets were replaced by underscores.
The following title `title [square] (round)` looked like this:
```
[title _square_ _round_](:/c54794f53e5e4b1aa558699e255d5f95)
```
Now it looks like this:
```
[title \[square\] (round)](:/c54794f53e5e4b1aa558699e255d5f95)
```
fixes #2085
> fix escaping of title when generating a markdown link

- CliClient/tests/services_InteropService.js
- CliClient/tests/services_InteropService_Exporter_Md.js
- ReactNativeClient/lib/services/InteropService_Exporter_Md.js
Fixes #2449
Fixes #2455
- The issue occurs because the export folder for the notebook does not exist when the note md file is saved. (`fs.writeFile` does not recursively create the path) 
- The solution is to ensure the folder exists when writing the note.
- Unit tests added.
- Tested on desktop (Linux) only.
> All: Fix markdown export

- ReactNativeClient/lib/BaseApplication.js
This is a small PR to fix a small GUI issue that is described below.
I haven't created an issue in github, but will describe it here.  (please let me know if this is not OK for small issues like this)
After removing a tag from a note, the note list does not always reflect the selection in sidebar.
1. Start with default profile
2. Add a tag `aaa` to two notes
3. Select tag `aaa` in side bar
4. Select a note and remove tag `aaa` from it
The tag `aaa` is still selected in the side bar
The untagged note is removed from the note list (as it is no longer has tag `aaa`)
The note list shows the remaining notes that have the tag
The tag `aaa` is still selected in the side bar
The note list is unchanged (and shows the note that no longer has the tag `aaa`)
The observed result is a problem, because …
> Desktop: Fix to update the note list if the selected tag is deleted.

- ElectronClient/app/gui/NotePropertiesDialog.jsx
Fixes #2470
Coordinates are now shown as `27° 43′ 31.79″ N 18° 1′ 27.48″ W`
I've used 2 decimal points. Let me know if it requires any adjustment.
> Desktop: Fix incorrect location format

- Clipper/joplin-webclipper/background.js
- Clipper/joplin-webclipper/content_scripts/index.js
- Clipper/joplin-webclipper/manifest.json
- Clipper/joplin-webclipper/popup/src/App.css
- Clipper/joplin-webclipper/popup/src/App.js
- Clipper/joplin-webclipper/popup/src/bridge.js
- Clipper/joplin-webclipper/popup/src/index.js
Related forum post:
- https://discourse.joplinapp.org/t/shortcut-hotkey-for-the-web-clipper/4877
Relevant docs:
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands
Not sure if you'll want to take this given the [discussion of a new webclipper](https://discourse.joplinapp.org/t/an-alternative-web-clipper-for-joplin/4904/), but the first bit was simple and already finished so I thought I'd open the PR. 
This change adds a command to the `manifest.json` for the web clipper which launches the webclipper rather than clicking on it. Because this is a WebExtensions feature and not something homegrown, users are able to change (or remove) the shortcut using native browser functionality.
It should theoretically be possible to take the default values and …
> Clipper: Add ability to launch clipper window with shortcut

- Joplin_install_and_update.sh
Version in the desktop file caused parsing errors. Also, force the app file to be loaded/reloaded.
> Desktop: Fix `.desktop` file & force refresh

- ReactNativeClient/lib/components/global-style.js
- ReactNativeClient/lib/models/Setting.js
A new theme with just the darker background '#000000': 
Practical for oled screens (pixel powered off), so less power consumption and easier for late night  reading
Requested in the forum:
https://discourse.joplinapp.org/t/black-oled-theme-for-mobile-version/2618
> Mobile: Adding Oled dark theme

- ElectronClient/app/package-lock.json
- ElectronClient/app/package.json
This is only a minor bump but several issues have been fixed since 7.1.9:
- Fixed an issue where sending complex objects over IPC could in some cases cause the renderer process to be terminated. electron/electron#21922
- Fixed crash with Date.toLocaleString for invalid locale and locale of the format aa@BB. electron/electron#21969
- Fixed flash plugin not working. electron/electron#22109
- Fixed issue where renderers could crash during GC when using the contextBridge module. electron/electron#22112
- Fixed netLog.stopLogging returning undefined instead of the path to the log. electron/electron#21988
- Fixed an edge case in checkbox logic on Windows. electron/electron#21860
- Fixed an issue where window.print() only worked once on a single BrowserWindow. electron/electron#21911
- Fixed an …
> Desktop: Update Electron to 7.1.12

- ElectronClient/app/gui/NoteText.jsx
Fixes #2240 
User entered spaces are being navigated and deleted in fours (as if they were tabs).  For example, after entering 4 spaces, the user is not able to backspace just one.
This fix ensures that the editor allows the user to interact with the text in whatever form it was entered -- tabs are treated like tabs, and spaces are treated like spaces.
> Desktop: Treat spaces as spaces in markdown editor.

- ReactNativeClient/package-lock.json
- ReactNativeClient/package.json
This gets rid of the following warning during compile time:
```
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
```
> update react-native-version-info to 1.0.1

- CliClient/locales/ja_JP.po
Fix an invalid sprintf format string I accidentally added in #2537
> Translation: Fix an sprintf format error in ja_JP.po

- ElectronClient/app.js
On macOS the menu item `Resources` never showed up under `Tools`.
follow-up to #2189
> fix Resources menu item

- CliClient/run_test.sh
When running the unit tests, various code for testing is copied to the `test-build` directory.
This PR ensures that files in `test-build` are removed if they don't belong.
This is important if you switch between branches. For example, if you create a new test script on a branch, it will not be removed when you run tests on another branch, resulting in failed tests and confusion.
> CLI: Ensure test-build does not contain unrelated files.

- CONTRIBUTING.md
Fix instruction to build unit tests.
`build.sh` no longer exists.
> Docs: Update unit test build instruction.

- ReactNativeClient/lib/models/Setting.js
This fixes an issue in themes list on desktop and mobile, the problem is due to a wrong platform identification 
The test condition on plateform is no more valid with the last modification in : ReactNativeClient/lib/shim.js :
-	if (shim.isReactNative()) return 'mobile';
+	if (shim.isReactNative()) return shim.mobilePlatform();
I tested it on desktop and Android and it work fine with this modification
> Fixed theme list issue in settings

- .eslintrc.js
- CliClient/tests/integration_SmartFilters.js
- CliClient/tests/test-utils.js
- ElectronClient/gui/NoteText.jsx
- ElectronClient/gui/SideBar.jsx
- ReactNativeClient/lib/BaseApplication.js
- ReactNativeClient/lib/BaseModel.js
- ReactNativeClient/lib/folders-screen-utils.js
- ReactNativeClient/lib/models/Note.js
- ReactNativeClient/lib/models/SmartFilter.js
- ReactNativeClient/lib/reducer.js
- ReactNativeClient/lib/registry.js
- ReactNativeClient/lib/reserved-ids.js
- ReactNativeClient/lib/services/DecryptionWorker.js
- ReactNativeClient/lib/services/SearchEngine.js
Resolves #262 for desktop
- `All notes` is a new selectable section at the top of the sidebar.
- Selecting `All notes` updates the note list to show all notes.
- When navigating to `All notes`, the currently selected note remains selected.
While in `All notes`:
- All note list functions are enabled as usual (eg create, delete, add tags, etc)
- Notes are sorted according to the `Sort notes by` user preference.
- The note toolbar shows the notebook to which a note belongs
- New notes are assigned to the last selected notebook
Example showing behaviour when `All notes` is selected:
Implemented as a smart filter.  The PR also proposes the introduction of automated integration testing for the backbone.
Manual tests:
This implementation does not deal with requests for showing sub-notebook notes …
> Desktop: Implement "show all notes"

- BUILD.md
Followup from the conversation here: https://github.com/laurent22/joplin/commit/1a96ee4c6b4169bbf4ecd084dbfd742a2be4a14f#r37445293
> Desktop: Add docs for auto-reloading the Electron client

- ReactNativeClient/android/app/src/main/res/xml/network_security_config.xml
**"Android" Joplin app**
This change allows the image with http-url to be rendered
Reference of issue #2496 
below block of code from network_security_config.xml file was  causing the problem
> Android: fixes http-url image render

- ElectronClient/gui/NoteText.jsx
fixes  #2573 
This PR fixes the bug where the selected text was not being converted into bold/italic text if followed or preceded by  a white space
@laurent22  @PackElend  @tessus 
-  `/[^\s]/` - to find the first occurrence(index position) of any character that is not a white space (line breaks, tabs, spaces, hard spaces) and store it in start
- ` /[^\s](?=[\s]*$)/`  Matches any character (that is not white space) and then asserts ((?=) is positive lookahead) that no other character up to the end of the string. 
- using substring to add the [spaces+markdown rule+selected text+markdown rule+ space]
-  the trim functionality was inspired when I was looking through Github editor, so if no text is followed after our selected text in the document we trim the end our newBody variable
> DESKTOP: Fixes the bug where selected text was not being converted into bold text. 

- .eslintrc.js
- ElectronClient/gui/NoteContentPropertiesDialog.tsx
- package-lock.json
- package.json
This PR Adds support for #2579 Rule of Hooks plugins by:
- Installing `eslint-plugin-react-hooks`
- adding the rules to `.eslintrc.js`
- fixes errors
**How to test**
run `npm run linter ./` in the root directory
**Expected result**
- No errors
> Add support for Rule of Hooks plugin (#2579)

- ElectronClient/gui/Header.jsx
Fixes #2615 
The state variable `showButtonLabels` is assigned in the function `componentDidUpdate()` which is called initially, and whenever resizing the window, etc.. But it isn't called called before rendering the component when pressing Back button from Options, which led to the variable being undefined. I think the reason is since there are no changes to the component, there isn't any reason to call the component. (If you resize the window, it gets called and button labels come back) Hence only `render()` is called.
A solution would be using `componentDidMount()` to determine if the state variable is undefined, and then assign the value. It's only called one (after the initial rendering) so there isn't a performance issue.
An alternative way is remembering the state, which is …
> Desktop: Fix undefined showButtonLabels

- ElectronClient/gui/NoteContentPropertiesDialog.tsx
Per @laurent22 comment [here](https://github.com/laurent22/joplin/pull/2444#issuecomment-593090403), if note body is empty the line count should display 0. The rest of the cases should remain unchanged.
> Desktop: Empty note body should have 0 line count

- ElectronClient/theme.js
Earlier in solarized Dark theme, code border colour was as such that code was not distinguishable prominently from normal text.
> DESKTOP:Code was not distinguishable from text

- ElectronClient/gui/NoteText.jsx
Fixes issue #2560 
This PR adds a toggling function for bold, italics and code elements in the Editor Toolbar.
As mentioned in the issue:
> You have a text `bla`, select it and click `Bold`. Then you get `**bla**`, you select `**bla**`, click `Bold` and get `bla`.
Added italics toggling for wrapping using underscores
> Desktop: Add toggling functionality for bold, italics and code in Editor Toolbar

- ElectronClient/app.js
**DESCRIPTION:**
This patch is a fix for the issue #2467 . Previously before this solution, the Edit menu items were not disabled on PREVIEW, this caused users to be able to use short cuts such as CTRL+B, CTRL+` on PREVIEW mode which is an unwanted behavior.
**HOW TO TEST**
Use the following test cases to confirm this solution::
- Add a note to a notebook and click the layout toggler to PREVIEW:
EXPECTED RESULT: 'copy', 'paste', 'cut', 'select all', 'bold', 'italic', 'link', 'code', 'insert Date Time', 'Start External Editing', 'show Local Search' should be **disabled**
- Add a note to a notebook and click the layout toggler to EDITOR:
EXPECTED RESULT: 'copy', 'paste', 'cut', 'select all', 'bold', 'italic', 'link', 'code', 'insert Date Time', 'Start External Editing', 'show Local Search' …
> Desktop: preview mode fix

- ReactNativeClient/android/app/src/main/java/net/cozic/joplin/MainApplication.java
Enables debugging for the android plugin which
`react-native-webview` uses. This method is mentioned in their guide
for the same.
https://github.com/react-native-community/react-native-webview/blob/master/docs/Debugging.md
Unfortunately the call requires API version >= 19 (After Kitkat),
which is fine because our testing may occur at a higher API level.
> [mobile] webview: Enable debugging on browser.

- ElectronClient/app.js
fixes #2608 
This PR causes the toggle editor layout shortcut and button (ctrl+l/cmd+l) to be disabled in an empty notebook (notebook without notes) just like the toggle editor layout icon. I still don't know if its done by design, but it doesn't seem right, so figured out i just solve it
**BEFORE**
**AFTER**
> Desktop: Disable Toggle Editor Layout Shortcut and Button in Empty Notebook

- CliClient/locales/zh_CN.po
"Editor"  should translate to :  "编辑器"
> Update zh_CN.po :  translate typo of "Editor" to "编辑器"

- CliClient/tests/models_Folder.js
- ElectronClient/gui/NoteText.jsx
- ReactNativeClient/lib/models/Folder.js
Fixes #2616 
Earlier, if the result of a search is a note inside a sub-notebook whose tree has been collapsed, the tree wouldn't expand when the In: Folder button was clicked.
> Desktop: Expand Tree on Search Result

- ElectronClient/gui/NoteText.jsx
Overrides Ace's `Editor.indent` function to insert indentation at start of line when editing Markdown list. Also resets numbered lists to `1.`.
Fixes #498. This PR does not implement "when caret is at start of line" part though. I'm accustomed to Dropbox Paper's behavior that pressing Tab indents a list item wherever caret is, and I thought that's more intuitive.
> Desktop: Markdown list indentation

- ElectronClient/gui/NoteList.jsx
This PR contains two enhancements to focus behaviour in the note list:
1. Delete a note from the note list (eg using `Delete` key or context-menu)
2. Use `Up` or `Down` key to select the next note
Expected: the next note is selected, the user can continue navigating with the keys
Actual: nothing, the note list does not respond to the navigation keys anymore
1. Select multiple notes in the note list (eg Ctrl-A, or using mouse)
2. Use `Up` or `Down` key to select the next note
Expected: the next note is selected, and the previous notes are deselected
Actual: nothing, the note list does not respond to navigation keys anymore
This fix also fixes another issue discussed in [forum](https://discourse.joplinapp.org/t/please-help-test-the-new-desktop-pre-release) as a side effect.
> Desktop: Enhance notelist focus behaviour

- ElectronClient/app.js
- ElectronClient/bridge.js
On certain OS it is not possible to copy the text in the About window.
This change allows to copy that info to the Clipboard.
Due to some shortfalls in Electron, it is not possible to set `defaultId` and `cancelId` to 0.
(Actually one can set them to 0, but the result is not what one would expect.)
Thus I had to move the default `OK` button to the left.
I also added a hack to position the `OK` button approximately in the middle of the dialog box (if the copyLabel is not longer than 14 characters).
> Desktop: add button to About box to copy Joplin's information to the clipboard

- CliClient/app/command-apidoc.js
- CliClient/tests/services_rest_Api.js
- ReactNativeClient/lib/services/rest/Api.js
Fixes #941 
**Before:**
**After:**
The issue as mentioned in #941 was that the tags were not updated. This was due to the fact that in `PUT` request method the tags were not explicitly set unlike how the `POST` request method was handled in the `action_notes` function. 
The fix I have given makes the necessary changes. I have also written unit tests for the code. Looking forward to any comments or suggestions!
> API: Fix tags update on updating a note

- build_tools_check.js
- package.json
closes #2631 
This script detects the OS of the user and checks to see if the necessary build tools / dependencies needed to successfully build the app are installed. if it is not installed it simply tries to install the tool, if it cannot i install it then it sends a warning message to the console to let the user know that he has to install these tools before proceeding. I learnt quite alot writing this script and i hope it is accepted, i'm very much open to improvements and new ideas if this is not okay.
> Enhancement: Build tools detecting script

- ReactNativeClient/lib/components/screens/config.js
This button is enabled in the Config screen, however it does nothing in iOS, so it should be removed.
fixes #2701
> Removed export debug report button in iOS

- ReactNativeClient/lib/components/screens/note.js
(Mobile) Fixes sidebar not automatically closes on an error. Added a function which will close the sidebar if there is an error. And also closes #2715 .
> added a new close function to close sidebar for an error and  fixes #2715

- ReactNativeClient/lib/components/screen-header.js
- ReactNativeClient/lib/reducer.js
closes #2721 
I added an option to select all notes at a time. I added a button that will appear when the user selects any note and then they can click on them to select all notes of that particular screen. This way they can easily manipulate multiple notes.
Tests:
1. I tested manually that the icon is only appearing on the screen when users choose any note and nowhere else. And also checked configuration and other pages, just to be sure.
2. I checked that when user clicks on select all button, only the notes of that page are getting selected and no other notes. I confirmed this by logging the changing values in the reducer.
3. I checked that after selecting all the notes, deleting, duplicating and all the other options are working.
4. I checked that after selecting all the options if we …
> added feature of select all and closes #2721

- CliClient/tests/models_Folder.js
- CliClient/tests/models_Note.js
- ElectronClient/gui/NoteList.jsx
- ReactNativeClient/lib/models/Folder.js
> Desktop: Batch delete for Notebooks added

- ElectronClient/gui/Header.jsx
Fixes #2700 
Refer following screen recording for demonstration:
It looks like search box is too wide but it also needs space for `Usage` link so that's why it is.
> Desktop: Fix button label wrapping

- ReactNativeClient/lib/components/screens/note.js
fix partial of #2286
according to https://github.com/facebook/react-native/issues/23117#issuecomment-456702379
wrap Input with ScrollView did the trick
test fine on real device
> Mobile: show scrollbar in editor mode

- CliClient/tests/integration_ShowAllNotes.js
- ReactNativeClient/lib/reducer.js
This PR fixes a couple of small update bugs in the All Notes list.  Tests added.
To reproduce:
1. Create two folders (`A` and `B`) with a note `N` in folder `A`
2. Selected folder `B` in sidebar
3. Select `All notes` in sidebar
4. Duplicate note `N`
Expected: the new duplicate note appears in the `All notes` note list
Actual: nothing. The note is duplicated but does not appear.
To reproduce:
1. Create two folders (`A` and `B`) with a note `N` in folder `A`
2. Select `All notes` in Sidebar
3. Drag note `N` to folder `B` in sidebar
Expected: the note remains visible in the `All notes` note list
Actual: the note disappears from the note list.
> Desktop: Fix `All notes` note list update bugs.

- CliClient/tests/models_BaseItem.js
- ReactNativeClient/lib/models/BaseItem.js
During unserialization, note timestamps are returned as strings.  This is inconsistent with their format defined in the database, which says they are meant to be integers.  This PR fixes the inconsistency.
> All: Fix format of note timestamps

- ElectronClient/gui/NoteText.jsx
**Disclaimer**: This is my first pull request. 
**Description**
Generally, menubar items (e.g. *File*, *Edit*, *View*) can be easily accessed by using `Alt + (the first character of menubar item name)` shortcut like e.g. `Alt + F` for *File*, `Alt + E` for *Edit* and it usually works. Except for the *Edit* menubar item. When you are not editing a note, `Alt + E` shortcut works, but when you do, 'Looks good!' message pops up like in the screenshot below.
**Screenshot**
**Cause**
In node module 'brace' there is a builtin keybinding `Alt + E` that is written in the *index.js* file.
``` 
name: "goToNextError",
bindKey: bindKey("Alt-E", "F4"),
exec: function(editor) {
config.loadModule("ace/ext/error_marker", function(module) {
module.showErrorMarker(editor, 1);
});
},
scrollIntoView: …
```
> Fixed menubar (Edit, Alt+E) shortcut problem while editing a note

- ReactNativeClient/lib/components/global-style.js
closes #2859 
@PackElend  please label me
New Images:
> Mobile: fixed css error in code block in oled theme in mobiles and closes #2859

- readme/build_troubleshooting.md
Building React native app on macOS caused error : `/joplin/ReactNativeClient/ios/Pods/Target Support Files/Pods-Joplin/Pods-Joplin.debug.xcconfig: unable to open file (in target "Joplin" in project "Joplin") (in target 'Joplin' from project 'Joplin')` for me so I decided to update the troubleshooting section with the fix if someone else would be stuck.
> Update macOS troubleshooting for IOS build 

- ReactNativeClient/lib/components/screens/dropbox-login.js
closes #2843 
I fixed the issue of text overlapping and added the case of the dropbox sync page in note list component. 
@PackElend  please label me.
> Mobile: fixed overlapping text in dropbox sync page

- CliClient/tests/ArrayUtils.js
- CliClient/tests/StringUtils.js
- ElectronClient/plugins/GotoAnything.jsx
- ReactNativeClient/lib/ArrayUtils.js
- ReactNativeClient/lib/string-utils.js
Closes #2683 
Using `/` prefix followed by a search query now shows list of notes which matches the query in their bodies. I had to add a new state variable `highlightKeywords` to prevent body search keywords getting highlighted in the titles.
I've also edited the help text. Hope that's not an issue for translation?
> Desktop: Go To Anything by body

- CliClient/locales/vi.po
> Vietnamese Translation

- ElectronClient/plugins/GotoAnything.jsx
Issue fixed [Closing of Goto Anything modal](https://discourse.joplinapp.org/t/closing-of-modal-when-clicked-outside-of-it/7480/7)
> Desktop: Close `Goto Anything` modal on outside click

- ReactNativeClient/lib/components/screens/config.js
In mobile: 
Export profile path text field's text is not visible in the dark theme, because it was set to black color.
Before:
After:
@PackElend  please label my PR.
> Mobile: fixed the issue of export path text not visible in dark theme

- ElectronClient/InteropServiceHelper.js
The previous behavior was to have an empty name. I've kept it like that (to get the PR up quicker) but eventually I'd like to find a way to also have a friendly filename for jex exports.
> Return empty default for exports with no note ids (jex for example)

- Joplin_install_and_update.sh
Stumbled into this when trying to install Joplin on elementary OS. Tested this fix on my own system and it works as expected.
> Desktop: Support icon install on elementary OS

- Joplin_install_and_update.sh
If user home directory is configured to anything other than `/home/${USER}`, `Exec` command in desktop entry points to non-existing file and desktop entry is not considered valid, thus does not appear in list of application. Standard way to get home directory is using `${HOME}` environment variable. This could also be possible root cause of https://discourse.joplinapp.org/t/joplin-not-installing-completely/5669/2
> Desktop: Fix Linux install script to add support for non-default home dir

- ElectronClient/plugins/GotoAnything.jsx
Fixes #3028
Issue was caused by the Go To Anything modal inheriting onClick behaviour from its parent: Dialog modal layer. 
This PR adds a condition to check if the element which dispatched the onClick event is the same element which the onClick event handler was originally attached to. Therefore only clicking on the dialog modal layer will close the modal. Other events are discarded.
> Desktop: Fix Go To Anything closing when clicking inside the modal

- ElectronClient/gui/PromptDialog.jsx
fixes #2799 and more such issue. 
This pull request changes the state of `ok` button to disabled in the `PromptDialog.jsx` whenever the input value in the dialog box is null or empty and i have tested this feature in various cases (New Notebook, Inserting a template) in which it disables the 'ok' button and the screenshots, GIF are shown below.
- New Notebook 
- Insert Template
***
- New Notebook
**after adding title**
- Insert Template
> Desktop: Disable ok button at empty input

- ReactNativeClient/root.js
> Mobile: Fixes #2853: Fix white corners on switching themes in iOS

- ReactNativeClient/lib/components/global-style.js
- ReactNativeClient/lib/components/screens/NoteTagsDialog.js
- ReactNativeClient/lib/components/screens/config.js
- ReactNativeClient/lib/components/screens/dropbox-login.js
- ReactNativeClient/lib/components/screens/encryption-config.js
- ReactNativeClient/lib/components/screens/folder.js
- ReactNativeClient/lib/components/screens/note.js
- ReactNativeClient/lib/components/screens/search.js
Fixes #2798 
Keyboard Appearance switches based on the Theme.
The appearance is configured in global-styles.js.
> Mobile: Fixes #2798: Switch keyboard appearance with theme

- Joplin_install_and_update.sh
LXDE uses Freedesktop as well. Tested this in Lubuntu.
> Linux: Add LXDE to installer as it works fine there

- ReactNativeClient/lib/components/global-style.js
> Mobile: Fixes #3098: Table rendering issue in dark themes

- ReactNativeClient/lib/joplin-renderer/MdToHtml/rules/katex.js
Fixes #3078
When we export a note `InteropService()` render a note in HTML file in temp directory then using that HTML file PDF get exported, Now I figured out that HTML file requires a `katex.css` which is already exported by plugin and `katex.css` requires the fonts included in fonts directory which is not exported by plugin so we need to export the fonts directory also along with `katex.css` now I added the fonts in `katex.js` so they also will be exported. Now everything working fine!
@PackElend Can you label me please? Thank you!
> Desktop: Fixed KaTeX font issue in exported PDF

- ElectronClient/app.js
This change aligns Joplin's behavior with all other apps that have shortcuts for `Zoom In`.
It therefore improves the user experience.
/ref
- https://discourse.joplinapp.org/t/please-help-test-the-new-desktop-pre-release/6445/2?u=tessus
- https://github.com/laurent22/joplin/pull/2165#issuecomment-593106648
> Desktop: add + to access 'Zoom In', allows to use the numpad

- CliClient/tests/models_BaseItem.js
- ReactNativeClient/lib/models/BaseItem.js
Geolocation data changes format through serialization between number and string.  It means that the clients on either end of a sync hold the same data but in different formats.  It is expected that it would be identical on both clients.
The database specifies the format of geo data as NUMBER. However the app seems to use it as formatted string.
One solution is to modify the database so the format is specified as STRING. However this would require a database migration upon upgrade, I'm not sure how simple that would be for a base data type.
Alternatively, though not ideal, here we propose to make an exception for geo data in the BaseItem serialization methods so that the database specification is ignored, and the format is maintained as string throughout serialization / unserialization.
> All: Fix format of geolocation data

- ElectronClient/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx
I noticed that texts are not properly saved when using IME (input method editor) on TinyMCE. Calling `onChangeHandler` on `compositionend` event fixes the problem.
(Steps to reproduce: 1. Input some text using IME. 2. Switch to another note. 3. Switch to the original note, and you see that the text was not saved)
> Desktop: Handle compositionend event in TinyMCE

- ReactNativeClient/lib/components/screens/config.js
Fixed issue: https://github.com/laurent22/joplin/issues/3010
**EISDIR** stands for "Error, Is Directory". This means that NPM is trying to do something to a _file_ but it is a _directory_. In our case app is trying to copy the files from PluginAssets directory but it didn't find any files in that directory so `fsDriver().copy()` is trying to copy the blank directory which causes this error. Now I fixed it by skipping PluginAssets directory while exporting.
@PackElend can you please label me, thank you!
> Android: Fixed Export Profile Error

- ElectronClient/gui/NotePropertiesDialog.jsx
> Desktop: Fixes #3131: Long URL in Note Info Dialog

- ReactNativeClient/lib/components/screen-header.js
closes #2875 
I fixed the issue and now only the limited characters of the title are shown, which is the ideal case.
@PackElend  please label my PR.
> Mobile: Fixed notebook text overflow

- ReactNativeClient/lib/components/Dropdown.js
- ReactNativeClient/lib/components/screen-header.js
**Before:**
**After:** 
fixes #2987
> Mobile : Disabled the header items when no note is selected

- CliClient/app/app-gui.js
- ReactNativeClient/lib/models/Setting.js
Implements: #2110 
This PR makes it possible to configure pane sizes of note list, notebook list, and note areas in the terminal app. I made use of the discussions of this closed PR: #2613 (it deserves some credit, I guess). 
This implementation of configurable layouts requires the users to restart the CLI app to see the changes. I have indicated this in the properties' descriptions. 
Please review and tell me if the PR needs anything more. :)
@PackElend label me, please!
> CLI: Implemented configurable layout for terminal

- ElectronClient/app.js
- ElectronClient/plugins/GotoAnything.jsx
> Desktop: Fix focus on GotoAnything and Layout Switching

- CliClient/tests/models_Folder.js
- ElectronClient/gui/MainScreen.jsx
- ReactNativeClient/lib/models/Folder.js
fixes #3052 
I tried to test all kind of edge cases.
> Desktop: Fixed order of notebooks in moveToNotebook dialog

- CliClient/locales/de_DE.po
There was one too many full stops. Changed it to one.
> Minor typo in German translation

- ElectronClient/gui/style/theme/aritimDark.js
> Desktop: Changing bold-text preview color for Aritim-dark theme

- ReactNativeClient/lib/reducer.js
handleHistory calls have been moved out of the switch statement.
> Remove redundant handleHistory call.

- readme/faq.md
This updates the sublime text and VSCode commands to add options which
make them wait before closing. This is borrowed from how you set a
different editor for git commit messages, described by github here:
https://help.github.com/en/github/using-git/associating-text-editors-with-git
Fixes #2425
> Update the faq for VSCode and Sublime

- ElectronClient/plugins/GotoAnything.jsx
fix #3171. When matching text for highlighting, use diacritics-removed keywords to match diacritics-removed body.
FYI: I find anohter way to remove diacritics:
```
function removeDiacritics(str) {
return str
.normalize('NFD')
.replace(/[\u0300-\u036f]/g, '');
}
```
Should we replace the origin implementation in `string-utils.js` with this implementation?
> Desktop: fix #3171: add support for matching text with diacritics for GotoAnything 

- CliClient/tests/services_SearchEngine.js
- ReactNativeClient/lib/services/SearchEngine.js
fix #3153.  Code review discussion before seen in #3154.
While typing East Asian charactors, the `SearchEngine` return a basic search result, which doesn't contain `fields`, and this break the code of highlighing process. Fix this bug add a `processBasicSearchResults_`  function to make the basic search result object consistent.
> Desktop: fix #3153: make GotoAnyting work with East Asian charactors

- readme/gsod2020/ideas.md
Joplin has 4 panes: side bar, notes list, code and view. Change joplin in a way that these parts can be different windows. Thus it is possible to put these windows on different screens for more space and better overview.
> New Idea: Separate Windows For Panes

- ElectronClient/gui/NoteEditor/NoteBody/AceEditor/AceEditor.tsx
fixes #3337 
This fixes a regression I accidentally introduced with the code mirror change. As you can see it's a silly typo. I promise that I didn't subtly break the aceeditor in an effort to get people to switch over to the beta codemirror editor...
> Desktop: Actually apply theme for ace editor

- Joplin_install_and_update.sh
The Linux Install and Update Script currently doesn't have an option to download Pre-Release Versions. This is addressed in this Pull request.
> Desktop: Add argument to include Pre-Release Versions for Linux Install Script

- ReactNativeClient/lib/components/screens/note.js
> Mobile: check for provisional note instead of empty note id

- README.md
This PR fixes the sponsors table layout in the GitHub README.md
The table is currently displayed correctly only on https://joplinapp.org/
> Fix sponsors table layout in the GitHub README.md

- ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/utils/useListIdent.ts
- ReactNativeClient/lib/markdownUtils.js
- previously getLineSpan was included line text as a token (dumb oversight)
- the regex was updated to include a space after a OL element (was missing for some reason)
This is a codemirror specific bug, it was an oversight in the logic I implemented.
gif demonstrating the bug courtesy of @tessus
> Desktop: fix getLineSpan logic and list token regex logic

- ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/utils/useListIdent.ts
This just checks the current mode while pressing enter and disables the auto-indent for html outside of code blocks. The unfortunate consequence of this is that an indent inserted by the user will not be followed, although I'm not sure if that's really a big issue. 
[Reference from the forum]
> Desktop: Remove auto-indent for in note html/xml

- .eslintignore
- .gitignore
- ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/Editor.tsx
- ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/codemirror.d.ts
I was originally planning on adding more type information to the codemirror interactions using [this third party package](https://www.npmjs.com/package/@types/codemirror) but unfortunately codemirror [isn't made to work well with strict typing](https://discuss.codemirror.net/t/basic-codemirror-configuration-in-typescript-project/2047/2) and it seems that we would need to make the code fairly convoluted to get it working.
Based on the recommendations of the codemirror maintainer I decided to leave the typing alone and just fix this one issue.
Ultimately I think Joplin should switch to codemirror 6 (several years from now) and typing support should be better then.
> Desktop: Change codemirror to user import syntax

- ReactNativeClient/lib/themes/dark.js
This PR changes it back to the previous color.
> Desktop, Mobile: fix link color for dark theme

- Tools/gulp/utils.js
The [latest commit](https://github.com/laurent22/joplin/commit/5143870d3b3132d15e6d8ecc83b284f1d36a4ce2) broke development on linux. This was because it was trying to mkdir when the directory already exists
```
[13:43:49] Finished 'compileScripts' after 18 ms
[13:43:49] Finished 'compilePackageInfo' after 18 ms
[13:43:49] 'copyPluginAssets' errored after 19 ms
[13:43:49] Error: EEXIST: file already exists, mkdir '/home/caleb/programming/github/joplin/ElectronClient/tools/../gui/note-viewer/pluginAssets'
```
This fix replaces the call to `mkdir` with [`ensureDir`](https://github.com/jprichardson/node-fs-extra/blob/HEAD/docs/ensureDir.md) Which first checks if a directory exists and creates it if it doesn't.
> Development: Use ensureDir instead of mkdir in utils

- README.md
Yandex.disk recently removed file upload support from WebDAV.
https://ru.stackoverflow.com/questions/1043523/После-загрузки-файла-на-Яндекс-Диск-по-webdav-происходят-паузы-по-60-секунд-на-к
https://qna.habr.com/q/677787
So this makes Yandex.disk unusable at the moment.
Here's a similar issue, please see recent comments: https://github.com/PhilippC/keepass2android/issues/506
I've personally tried, and cannot even access to Yandex.disk at the moment through WebDAV.
This PR simply removes yandex.disk line from the ReadMe.
Thanks,
> Yandex disk removed from supported WEBDAV clients

- ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx
- ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/Editor.tsx
- ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/utils/index.ts
[reference](https://discourse.joplinapp.org/t/codemirror-issues/9392)
This fixes issue number 2 highlighted by t0dd.
The method I found to reliably reproduce this issue is:
1. Move Joplin to one side of the screen (so it's width is only half the display width)
2. Collapse the note list and the sidebar
3. Click into the codemirror editor, the cursor won't be aligned with text
After manually calling refresh (as I do in this code) or performing an action such as a window resize or entering text, the cursor will go to the correct location.
I was only able to reliably reproduce this with one note, I think because it's particularly long, but I'm not sure exactly.
> Desktop: Manually refresh codemirror whenever the parent div size changes

- ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx
- ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/Editor.tsx
To do this I took the default keymap and removed any keys that didn't seem useful. I'm not claiming that this is the perfect list of supported functions, so I'm open to any input @laurent22 @tessus 
Below is the keymap as it exists before this change
Left: "goCharLeft"
Right: "goCharRight"
Up: "goLineUp"
Down: "goLineDown"
End: "goLineEnd"
Home: "goLineStartSmart"
PageUp: "goPageUp"
PageDown: "goPageDown"
Delete: "delCharAfter"
Backspace: "delCharBefore"
Shift-Backspace: "delCharBefore"
Tab: "defaultTab"
Shift-Tab: "indentAuto"
Enter: "newlineAndIndent"
Insert: "toggleOverwrite"
Esc: "singleSelection"
Ctrl-A: "selectAll"
Ctrl-D: "deleteLine"
Ctrl-Z: "undo"
Shift-Ctrl-Z: "redo"
Ctrl-Y: "redo"
Ctrl-Home: "goDocStart"
Ctrl-End: "goDocEnd"
Ctrl-Up: "goLineUp"
Ctrl-Down: "goLineDown" …
> Desktop: Remove cancelled keys in favour of explicit keymaps

- ElectronClient/gui/NoteContentPropertiesDialog.tsx
I and others (according to some quick googling of feature requests) use Joplin to capture web articles to "read later" (a bit in the way Firefox's Pocket plugin is used). For that purpose, it's nice to see how long of a read a given article is.
Using the lower end of the average reading time (200 words per minute), I have added a label to the note properties dialog, because that's where we're already computing word and line counts. 
If the reading time is less than one minute, it is displayed as "< 1 min"; for anything else it is rounded up to the next integer.
In its current form it's very much a "minimum viable product"; I could certainly see making the "words per minute" number something configurable, so that a fast reader can set it to 300, or a slow reader to 150. But that can go …
> Desktop: Add approximate reading time to note statistics

- .gitignore
- CliClient/package-lock.json
- CliClient/package.json
- CliClient/tests/file_api_driver.js
- CliClient/tests/test-utils.js
- ElectronClient/package-lock.json
- ElectronClient/package.json
- ReactNativeClient/lib/BaseApplication.js
- ReactNativeClient/lib/SyncTargetAmazonS3.js
- ReactNativeClient/lib/file-api-driver-amazon-s3.js
- ReactNativeClient/lib/file-api.js
- ReactNativeClient/lib/models/Setting.js
- ReactNativeClient/package-lock.json
- ReactNativeClient/package.json
Adds syncing with AWS bucket, requires read/write access to the whole bucket. DO NOT share bucket with any thing else, it will erase them. 
I am able to get it to sync with my s3 bucket over the electron app with resources and E2EE enabled, but tests are failing. I'm making a PR it here in case someone can help me figure out what is causing the fails. Also I haven't had much experience with React Native and can use someone to help me test that.
1. signup for AWS account, if you need one
2. create an S3 bucket, make sure to default to `Block all public access` if you don't want your notes available to public: https://s3.console.aws.amazon.com/
3. You should create an AWS User just for joplin to keep: https://console.aws.amazon.com/iam/home?region=us-east-1#/users
For extra access control, …
> Add AWS S3 sync

- ReactNativeClient/lib/components/shared/side-menu-shared.js
This PR brings back alphabetical sorting of the tags in the desktop app side-menu as it was removed during refactoring in #2572.
> Desktop: Sort tags alphabetically in side-menu

- ReactNativeClient/lib/synchronizer.js
After the memory leak has been fixed it makes no sense to keep the existing 10mb max resource size limit.
I propose increasing it to 100mb, wait for a while to see if it causes any issues and if not remove it.
> Mobile: increase max resource size to 100mb

- ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx
- ElectronClient/gui/NoteSearchBar.jsx
[reference](https://discourse.joplinapp.org/t/1-0-227-regressions/10156/5)
Before I was manually setting split view which was particularly annoying for users who had disabled the split view. This is how I should have implemented it originally.
Before merging this I'd like to get some community feedback about the current behaviour.
> Desktop: Toggle Editor rather than setting split mode on search

- ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/utils/useListIdent.ts
This looks like a lot of changes but it's just because diff get's confused when I added a wrapper call to `cm.overlay` which batches updates for slightly better performance.
The main change here is that I disabled the smart `insertListElement` code when there are multiple cursors. It just becomes too difficult to track the correct behaviour.
I also mixed in a couple of fixes to this file that I noticed, namely the whitespace regex I updated in a different pull was being used 3 times and I didn't update for all of them. It's all good now though.
> Desktop: Codemirror clean up list indent code

- ReactNativeClient/android/app/src/main/AndroidManifest.xml
Raised on the forum: https://discourse.joplinapp.org/t/android-share-app-orientation/9677
> Android: remove hardcoded portrait screen orientation for share activity

- Joplin_install_and_update.sh
Appends  `&& update-desktop-database ~/.local/share/icons` in addition to `~/.local/share/applications`.  
Checked on Budgie 20.04 LTS.
@Tiger862000 Does this work for you on Pop!_OS?
> Desktop: Resolves #3529: Fix AppImage Icon

- CliClient/package-lock.json
- CliClient/package.json
- ElectronClient/package-lock.json
- ElectronClient/package.json
- ReactNativeClient/lib/joplin-renderer/package.json
- ReactNativeClient/package-lock.json
- ReactNativeClient/package.json
I want to use bra-ket notation to write some notes about quantum stuff. Joplin's current Katex dependency is 0.11.1, which does not support this notation. Katex 0.12.0 (the current stable release) does support this notation, so I propose to update Joplin's dependency to the new version.
> Update Katex to v0.12.0

- ElectronClient/gui/NoteToolbar/NoteToolbar.tsx
fixes #3569
Defining the `tooltip` property here, it is then propagated to the ToolbarButton component that will use it to define the html title of the tag while keeping the truncated version as content.
```js
const tooltip = this.props.tooltip ? this.props.tooltip : title;
```
https://github.com/laurent22/joplin/blob/dev/ElectronClient/gui/ToolbarButton.jsx#L11
> Desktop: Fixes #3569: Show full folder name in mouse-over pop-up text

- CliClient/tests/file_api_driver.js
- ReactNativeClient/lib/file-api-driver-amazon-s3.js
Fixes #3591.
Use timestamp instead of Date for updated_time, which caused the basic delta to always think there's a change.
> Windows/MacOS fix sync fetching for AWS S3

- ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/utils/useEditorSearch.ts
Only scroll to search matches when the user changes the search or explicitly changes the search index
https://discourse.joplinapp.org/t/codemirror-feedback/10397
The main functional change here is that the `scrollIntoView` will only be called if the keyword is the first in a multiple word search (this happens on the global search) and either the keyword has changed or the user has explicitly changed the index.
I also made some changes to the `highlightSearch` function because I noticed that it was creating an array and only adding one element to it :laughing:
> Desktop: Add scrollTo option to editor search highlighter

- ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx
- ElectronClient/index.html
fixes #3603
I basically just copied the loading code from tinyMCE.tsx. `loadScript` is taken without changes and `loadScripts` is modified to work with codemirror themes. I'm not exactly sure if this was the best way to handle it so please let me know if there needs to be any fundamental changes.
> Desktop: Move codemiror css into Codemirror.tsx

- ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx
I only implemented this for codemirror but the change can easily be backported to Ace.
fixes #3631
I ended up implementing this as an effect in the editor because I couldn't see a clean solution that would be possible inside of the command system. 
One thing that I wasn't sure about when implementing this is if my solution here is guaranteed to only trigger when the user presses Ctrl-L, I did some testing and it seemed okay. @laurent22  I can add a guard with `usePrevious` if you think that this will sometimes unnecessarily focus the editor.
> Desktop: Focus the editor whenever the user toggles the visible panes

- ReactNativeClient/lib/onedrive-api.js
Bug reported in the [forum](InvalidAuthenticationToken). The Bug has been introduced in the [pr for onedrive for business](https://github.com/laurent22/joplin/pull/3433). The Bug happened because of missing error handling when requesting the account properties. Sorry for that :-(. It should work now. 
The Bug can be reproduced by the following: 
1. Set the value for sync.3.context in the "settings" table in the sqlite database to ""
2. Change the access token in the JSON text for sync.3.auth in the "settings" table so that the token is invalid (just change one character) 
3. start joplin and sync to onedrive
> Fixes InvalidAuthenticationToken for OneDrive

- ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx
- ElectronClient/index.html
[reference](https://discourse.joplinapp.org/t/bug-cursor-jumps-in-codemirror/10713)
I couldn't pinpoint the exact cause of failure on this one, but it seems like codemirror doesn't like it when the css is lazy loaded. I think there is probably some form of race condition happening while it is initializing. 
I figured the simplest solution would be to load the 8.5KB codemirror.css file in index.html. If that is too slow we could probably change this to add only the exact css needed in index.html and lazy load the rest of the file, but I don't think that's really worth the complexity.
> Desktop: Load codemirror css in index.html

- ReactNativeClient/lib/services/keychain/KeychainServiceDriver.node.ts
Issue https://github.com/laurent22/joplin/issues/3711
This patch replaces the 'isLinux' check by a more restrictive version
which fixes the false positive in BSD systems. This was causing Joplin
not to load due to the lack of X11 in headless mode.
> Fix keytar library being loaded up in FreeBSD.

- CliClient/tests/filterParser.js
- CliClient/tests/services_SearchFilter.js
- ReactNativeClient/lib/services/searchengine/filterParser.ts
This doesn't work now. We need to trim the quotes.
```
tag:"space travel"
```
> Desktop: Fix bug with quotes

- CliClient/tests/filterParser.js
- CliClient/tests/services_SearchFuzzy.js
- ElectronClient/plugins/GotoAnything.jsx
- ReactNativeClient/lib/services/searchengine/SearchEngine.js
- ReactNativeClient/lib/services/searchengine/filterParser.ts
We need to remove the upper limit of 3 when looking for fuzzy matches.
Spellfix will by default only give relevant matches.
If there is a limit of 3, then wild card searches like abc* will only give 3 words with that prefix.
> Desktop: Fix wildcard search

- ElectronClient/package.json
This Pull Request fixes an issue with missing Joplin icon in AppImage build (fixes #3720). It turned out that omitting the file name in "icon" parameter in `package.json` file, leads to generating correct directory structure with the use of all icons resolutions available (and not only the faulty `0x0` directory).
> Desktop: Fixes #3720: Fix icons path in AppImage build

- ElectronClient/gui/ItemList.jsx
- ElectronClient/gui/NoteList/NoteList.tsx
Fixes laurent22/joplin#3628
The note dragging was not taking into account the scroll distance.
This caused the notes to be dragged to a different location than the mouse.
This scroll offset should fix that issue.
This fix was moved to ui_update branch instead of dev branch.
[Original pull request](https://github.com/laurent22/joplin/pull/3643) on dev branch
> Desktop: Fixes #3628: Add scroll offset for dragging notes (ui_update branch)

- ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/Editor.tsx
fixes #3749 #3750
Based on what @meznak discovered, I've manually added the Joplin list handling to emacs mode. Previously emacs mode overwrote the the Tab and Enter keys to do it's own default behaviour (which was the basic behaviour), but I think the expected behaviour will be for the editing to be consistent across all modes. I don't think we need to overwrite emacs mode further than what I did here because we didn't really edit any of the other default keys.
> Desktop: Use joplin list handling in emacs mode

- ReactNativeClient/lib/BaseApplication.js
Fix bug reported here. 
https://discourse.joplinapp.org/t/creating-a-note-after-backward-redirection-places-it-in-a-wrong-notebook/11057
> Steps to reproduce:
>
>    I use Go to anything to go to the note in notebook A.
I use backward button to go back to the note in notebook B.
I create a new note.
>
>Behavior:
The note is created in notebook A.
>
>Expected behavior:
The note should be created in notebook B.
We have to update activeFolderId when using the backward/forward button.
> Desktop: Set activeFolderId correctly

- ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/Editor.tsx
This PR adds commonly used languages to the Markdown renderer to avoid having them with low contrast.
Example:
> Desktop: Add frequently used languages to markdown renderer

- ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/utils/useJoplinMode.ts
fixes #3791 
This does 2 things
1. It disables katex blocks inside of code blocks
2. Adds stricter rules around when katex blocks are opened and closed
> Desktop: Add stricter rules for katex blocks

- ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx
- ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/Editor.tsx
- ReactNativeClient/lib/BaseApplication.js
replaces #3622 
This solves 3 issues that were present with searching.
1. As discussed in #3622 we don't want to search on every keystroke so this fixes that (CodeMirror.tsx)
2. There was a race condition where sometimes the editor component wouldn't be ready by the time a search takes place, this adds a new property to the editor component that has the editor search as soon as it's ready. (Editor.tsx)
3. There was a recently introduced bug that didn't allow the search markers to be cleared once the search bar was empty (BaseApplication.js)
> Desktop: Fix missed highlighting when using the global search

- ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx
Fixes #3793 
I chose these colors by taking the defaults and adjusting the lightness until the contrast was high enough
> Desktop: Adjust the codemirror code block colors for the dark theme

- CliClient/locales/ko.po
This PR fixes a trivial typo in Korean translation(ko.po)
Signed-off-by: Ji-Hyeon Gim <potatogim@potatogim.net>
> All: Translation: Fix typo in ko.po

- .eslintignore
- .gitignore
- ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/Editor.tsx
- ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/utils/useKeymap.ts
- ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/utils/useListIdent.ts
This was [requested on the forum](https://discourse.joplinapp.org/t/vim-mode-o-o-key-functionality-changed/11225) and [here](https://discourse.joplinapp.org/t/can-no-longer-alt-arrows-to-move-lines-up-down-in-vim-mode/11226)
Changes:
add swapLine(Up/Down)
have `o` use the more complex list indent
enable sync initializing from vim (and maybe emacs)
I also moved the keyMap stuff into it's own file because it was getting kinda large.
> Desktop: Extend functionality of codemirror vim

- ReactNativeClient/lib/services/searchengine/SearchEngine.js
Motivated by 
https://github.com/laurent22/joplin/pull/3777#issuecomment-696491859
The fuzzy score shouldn't vary so much that it decides the sorting rather than BM25.
> Desktop: Keep fuzzy scores between 0 and 2

- CliClient/locales/pl_PL.po
This completes (for now) polish translation.
There were some additional (no longer used?) or outdated strings so I have re-generated `.po` files via `Tools/build-translation.js`.
> Polish translation update

- ElectronClient/gui/SideBar/SideBar.tsx
Added Thunderbird count for desktop client
It's described in this comment https://github.com/laurent22/joplin/pull/2006#issuecomment-552319524.
Also there is closed PR with this feature https://github.com/laurent22/joplin/pull/2965.
And more discussions about it can be found in this forum thread https://discourse.joplinapp.org/t/feature-request-count-the-notes-with-checked-checkbox/7545/7
> Desktop: Added Thunderbird count

- ReactNativeClient/lib/services/interop/InteropService_Exporter_Html.ts
I was receiving the following error when exporting a pdf on v1.3.2
```
main-html.js:49 Error: Error: ENOENT: no such file or directory, lstat '/home/caleb/programming/github/joplin/ElectronClient/lib/gui/note-viewer/pluginAssets/katex/katex.css'. Path: /home/caleb/programming/github/joplin/ElectronClient/lib/gui/note-viewer/pluginAssets/katex/katex.css
at FsDriverNode.fsErrorToJsError_ (/home/caleb/programming/github/joplin/ElectronClient/lib/fs-driver-node.js:9)
at FsDriverNode.copy (/home/caleb/programming/github/joplin/ElectronClient/lib/fs-driver-node.js:168)
```
It was simply because the line I edited was only navigating up 2 directories, when it needs to navigate up 3. Adding another call to `dirname` gets the correct file path and exports normally.
> Fix export of pluginAssets when exporting to html/pdf

- ElectronClient/app.ts
Make the tray menu consistent with the app. The app uses Quit, so should the tray.
> Tray: Exit -> Quit

- README.md
Hello,
I suggest you a PR to update the documentation and the readme. I would like to mention there an arch linux package to install the latest pre-release (cli and desktop).
> doc: add archlinux package for pre-release in docs

- CliClient/tests/services_rest_Api.ts
- ReactNativeClient/lib/SyncTargetAmazonS3.js
- ReactNativeClient/lib/models/Setting.ts
Hi all,
I have added support a custom S3 URL so you can use your own S3 provider instead of AWS. (https://github.com/laurent22/joplin/issues/3691)
I have added a URL option in the S3 Synchronization Settings page which defaults to `https://s3.amazonaws.com/` and added support in `SyncTargetAmazonS3.ts` for custom endpoints.
I have used this with AWS S3 and MinIO.
> All: Resolves #3691: Added support for a custom S3 URL

- ReactNativeClient/lib/import-enex-md-gen.js
- Desktop:  Added strikethrough markdown codes
I am assuming the `~~` Markdown tags for strikethrough are a relatively recent addition because the import from Evernote replaces them with `(` and `)` as  start and end markers.
This PR is a naive change to simply replace the `(` and `)` with `~~` and `~~`.
It does the trick for importing to Markdown, but still has the same limitations for some edge cases, for example it will be ignored if there is trailing space before the closing `~~`. This also happens for other tags such as bold/italic, so there needs to be a more general fix for importing format tags.
> Import <strike>,<s> tags (strikethrough) from Evernote

- ReactNativeClient/lib/services/searchengine/SearchEngine.js
We shouldn't use basic search when the filters like "tag" have a value in languages like Korean.
Otherwise, queries like these won't work.
tag:여보세요
Bug reported here: https://discourse.joplinapp.org/t/search-tag-in-asian-laguage-doesnt-work-properly/11285
> All: Fix filters when language is in Korean

- ElectronClient/checkForUpdates.js
Electron docs for `dialog.showMessageBox`: https://www.electronjs.org/docs/api/dialog#dialogshowmessageboxbrowserwindow-options
- In the message, fix a comma splice (grammar error) and remove some unnecessary words.
- Split the message into `message` and `detail` parts.
- Use specific verbs for the button labels. This follows the UI guidelines of major operating systems, including macOS and Windows. (`cancelId` was added while testing out different button labels that Electron might not automatically recognize as a cancel button. I think the `cancelId` is worth keeping to ensure the Esc key still works if the label is changed in the future.)
Old update dialog box as seen in v1.0.241:
New update dialog box with this change, with long release notes:
New update dialog box with short release …
> Desktop: Make “update is available” dialog box easier to use

- readme/api/get_started/plugins.md
Previous link to Development Mode page was 404'ing.
> Update plugins.md - broken link in docs

- packages/app-desktop/gui/KeymapConfig/styles/index.ts
- packages/lib/services/KeymapService.ts
String.fromCharCode expects unicode charcodes as an argument; e.keyCode returns javascript keycodes.
Javascript keycodes and unicode charcodes are not the same thing!
Therefore I used an array to map keycodes. This seems to be the only way to make this work properly.
I also changed the width of the shortcut recorder input field to 200px, since certain key combinations are cut off, because they don't fit in the field.
> Desktop: fix issues with shortcut editor

- README.md
- packages/lib/TemplateUtils.js
In certain situations it is useful to reference the beginning of the week.
Unfortunately the current system does not allow to do that, not even with a custom datetime format.
I've also added the 2 new template variables to the documentation.
| Variable | Description | Example |
| --- | --- | --- |
| `{{bowm}}` | Date of the beginning of the week (when week starts on Monday) based on the settings format | |
| `{{bows}}` | Date of the beginning of the week (when week starts on Sunday) based on the settings format | |
> Desktop: add {{bowm}} and {{bows}} - Beginning Of Week (Monday/Sunday)

- packages/app-desktop/gui/NoteEditor/utils/useDropHandler.ts
[This microsoft forum](https://answers.microsoft.com/en-us/msoffice/forum/msoffice_outlook-mso_windows8-mso_2016/drag-and-drop-works-however-deletes-email-can-we/865f60c3-7980-4465-8a19-4d60b0ae5aba) exchange says that the behaviour of drag and drop can be changed adjusting the dropEffect value.
It seems that before dropEffect was "none" and this might have been messing with outlook. 
I don't have outlook so I wasn't able to actually test this, but I did test dragging and dropping from the filesystem and it doesn't seem to affect it (I think most programs were interpreting `none` as `copy` anyway).
> Desktop: Attempt to fix outlook delete on drop

- Joplin_install_and_update.sh
Changed a single line of code to allow installation of the Desktop app when using [i3wm](https://i3wm.org/). 
Essentially the issue was that, without this fix, the Joplin desktop app would not be installed to ~/.local/share/applications. This would not allow the user to launch it using things like [Rofi](https://github.com/davatorium/rofi).
I've tested this on i3wm on Arch and it works great.
> Desktop: Added i3wm as a Desktop option, fixing an install issue

- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/Editor.tsx
- packages/app-desktop/gui/NoteEditor/utils/useDropHandler.ts
Follow up to #4031 
Based on [user feedback](https://discourse.joplinapp.org/t/drag-and-drop-behaviour/10546/31?u=calebjohn) the previous pull didn't work.
I went in and had a closer look at the [forum post](https://answers.microsoft.com/en-us/msoffice/forum/msoffice_outlook-mso_windows8-mso_2016/drag-and-drop-works-however-deletes-email-can-we/865f60c3-7980-4465-8a19-4d60b0ae5aba?page=1) I based the fix off of. And I took a closer look at the [documentation for dropEffect](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/dropEffect) specifically where it says
> Within event handlers for dragenter and dragover events, dropEffect should be modified if a different action is desired than the action that the user is requesting.
So it seems that the previous pull request did …
> Desktop: Attempt to fix Outlook drag and drop #2

- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx
This is done by adding a constant padding to the right hand side of the codemirror editor.
Before long lines could get pushed around when the scroll bar appeared.
Compare
->
And the new behavior
->
> Desktop: Prevent lines from shifting in Markdown Editor when Scrollbar appears

- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useCursorUtils.ts
This PR fixed [#3917](https://github.com/laurent22/joplin/issues/3917). Increasing number will be added to the front of each line in markdown editor, if users select multiple lines and use numbered list. My solution is to detect whether the user is trying to add a numbered list by checking if string1 starts with number. If it is, add increasing number to each selected line accordingly. Please let me know if it is a good solution or I need to do something further. Thank you in advance!
> Desktop: Fixes #3917: Fixed numbered list bug in markdown editor

- packages/app-mobile/android/app/src/main/AndroidManifest.xml
Maybe fixes #4122
There was a change in storage access permissions in Android 10. This PR should restore the old behaviour according to this document: https://developer.android.com/training/data-storage/use-cases#opt-out-scoped-storage
I do not have any devices running Android 10 so can't test if this really helps. Does not seem to break anything though.
> Android: Try to fix external storage access on Android 10

- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx
[ref](https://discourse.joplinapp.org/t/pre-release-v1-5-is-available-with-support-for-media-players-updated-20-12-20/12885/7?u=calebjohn)
I'm not sure when I introduced this typo, but I should have double checked that the menu commands work before the final merge. Sorry about that.
> Desktop: Fix typo when passing generic editor commands to the editor

- Joplin_install_and_update.sh
It's been awhile since the appimage format changed and this bit of code stopped working. That same change made this version matching unnecessary so there's no reason to keep it in. There won't be any change from the user perspective (aside from the error that would appear while running the update script will be gone).
We actually don't need to call the desktop file `appimagekit-joplin.desktop` any more either, but I don't think it's worth changing.
> Linux: Remove the appimage version from installer script

- packages/app-desktop/gui/ResourceScreen.tsx
Update to add case insensitive sorting to _Tools->Note Attachments..._
See - [Discourse](https://discourse.joplinapp.org/t/a-feature-request/13486/5?u=daeraxa) for original discussion and analysis of the issue.
The Note Attachments tool is taking case into account when sorting which is only really a problem for the _Title_ column (see image, _Title_ is sorted asc. and lowercase starting filenames are appearing below the end of the uppercase ones. This only really affects user experience and ease of reviewing when using the tool.
The idea is to add case insensitivity to the sorting so that 'x' will immediately follow 'X' etc.
I'm new to this so please be gentle if I've made a horrible mistake, please let me know what I can do to review/test/fix.
> Desktop: Add case insensitive sorting for Note Attachments tool

- README.md
Add Synology WebDAV Server to WebDAV-compatible service list.
> Add Synology WebDAV Server to WebDAV-compatible services

- packages/app-cli/tests/models_Note.ts
- packages/app-mobile/android/app/build.gradle
- packages/lib/models/Note.js
- packages/lib/models/Setting.ts
This is a feature that I needed and I think it could be useful for some people. This change creates a setting item and added title natural sorting logics to both after loading from database and when sorting is called.
It is still preliminary, e.g. I still need to figure out how to sort after the setting is saved. For now, one needs to click the notebook to tigger sorting.
> All: Support natural sorting by title

- packages/app-mobile/index.js
- packages/app-mobile/package-lock.json
- packages/app-mobile/package.json
- packages/app-mobile/utils/fs-driver-rn.js
This fixes a problem with the S3 synchronization code using the
shim.fsDriver().writeBinaryFile() which is not implemented in
fs-driver-rn.js (React Native).
Tested with AVD Android 10.0 target.
> Mobile: Fixes #4268: Fix downloading resource files from S3 with RN

- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useCursorUtils.ts
fixes #4317
This is caused by a bug with CodeMirror that doesn't take zoom into account when dealing with coordinates.
> Desktop: Insert spellcheck replacement at correct location when the window is zoomed

- packages/plugins/ToggleSideBars/src/index.ts
- packages/plugins/ToggleSideBars/src/manifest.json
The plugin didn't do anything, except log a message.
I thought I should fix it so that it does what it was supposed to. ;-) Hahaha.
Do we add prefix for such PRs with `Plugins: `?
> actually toggle something ;-)

- packages/lib/file-api-driver-onedrive.js
Quick fix for #4313
Onedrive currently gives always an "Resync required" error when making a delta request to a specific directory but not when making a request to the root. I will open an issue later at the Onedrive api docs and when it is working again we can revert the changes of this pr again as it is more efficient to make the request to the folder than filtering the delta response to only get the changes for the joplin folder. But it is definitely much better to filter the request than making a full resync each time.
> - All: Resolves #4313: Quick onedrive delta fix

- packages/lib/services/CommandService.ts
- packages/lib/services/commands/ToolbarButtonUtils.ts
fixes #4338 #4340 #4339
There is some [discussion here](https://github.com/laurent22/joplin/pull/4303#discussion_r555277583).
@laurent22 the fix I've introduced here is to keep the focus code as a special case (which it always needed because of commands like `textLink`) and extended the `isEditorCommand` function to cover all editor commands that do not start with `editor.`.
I understand if you think this is an ugly solution (although it is an extension of what we were doing previously). And I'm open to having a discussion about what would be a cleaner way to deal with this.
> Desktop: Fix Error: Cannot execute a command without a runtime

- Joplin_install_and_update.sh
Many sway users set $XDG_CURRENT_DESKTOP to sway. This could be detected to properly install the icon.
> Desktop Linux: Add support for the sway desktop environment

- packages/app-mobile/components/screens/Note.tsx
The PickerResponse object does not have a `fileName` field ([see the doc](https://github.com/rnmods/react-native-document-picker#result)) so an attached resource may end up with an empty title and a broken extension on Android where the url might look like `content://com.android.providers.downloads.documents/document/123`
> Mobile: When attaching a file to a note set correct title and extension

- Dockerfile.server
With the change in this file, the build is currently failing with the following:
```
Step 20/31 : COPY --chown=$user:$user packages/fork-htmlparser2 ./packages/fork-htmlparser2
---> Using cache
---> 27c3a2786a88
Step 21/31 : RUN npm run bootstrap
---> Running in 57794bc04013
> root@ bootstrap /home/joplin
> lerna bootstrap --no-ci
sh: 1: lerna: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! root@ bootstrap: `lerna bootstrap --no-ci`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the root@ bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
npm ERR! A complete log of this run can …
```
> Server: fix Docker build

- Joplin_install_and_update.sh
I added a long comment for context on the change. Ultimately, I don't know enough about the freedesktop standard (and all the different DE implementations) to remove the current system of checking desktops manually. 
fixes #4364
> Desktop: Change the Desktop check in the linux update script

- BUILD.md
- readme/build_troubleshooting.md
Added workarounds for the build issues I experienced several days back:
- `node-pre-gyp` sometimes calls an invalid URL and needs Python to build `node-sqlite3` from source
- `npm install` can be extremely fussy. `npm cache clean --force` doesn't help, so just nuking the directory and rebuilding it can make `npm` behave. (`npm rebuild` may be another alternative.)
> Workarounds for Linux build errors

- packages/tools/locales/zh_TW.po
improve terms and some typo in zh_TW.po
This translation from repo was cloned in 2021/02/01
> Update zh_TW translation

- BUILD.md
Hey, This is my first Pull Request. Looking forward to contributing to Joplin's codebase.
I think 'rsync' is pre-installed on mac os and there is same link for node 10+ and rsync (for mac and linux).
So I just added rsync to dependencies command.
> Docs: Update in Build.md

- packages/app-desktop/gui/note-viewer/index.html
This fixes a bug that has been reported on the forum a few times. [This is one example](https://discourse.joplinapp.org/t/a-markdown-outline-sidebar-plugin-for-joplin/13364/60?u=calebjohn) that I think will be fixed by this PR. I know there are others, but I can't find them.
To test this, create an anchor link that will jump you somewhere else in the note. Click on it, then scroll back to the link. Clicking again will do nothing before this pull, and will correctly jump after.
> Reset window hash to allowing clicking an anchor link more than once

- packages/lib/components/shared/note-screen-shared.js
I have changed the field name used when attaching files previously here: https://github.com/laurent22/joplin/pull/4373.
But I forgot that the same code is used for sharing:
https://github.com/laurent22/joplin/blob/a6b866cbe1362e0a6254774aec398c149592826c/packages/lib/components/shared/note-screen-shared.js#L232-L237
So the above PR fixed attaching files but broke sharing. This PR fixes that.
> Mobile: Fix incorrect field name when attaching a resource from share

- packages/lib/components/shared/reduxSharedMiddleware.js
> All: Refresh note tags when a note is moved to another folder

- packages/app-desktop/gui/NoteSearchBar.jsx
It has been for a while a cumbersome task of mine to clear the search text area when focusing it (i.e., `⌘F`). This aims to fix that. It only applies to the Desktop app. I have not found any open issue for it. Perhaps I was looking at the wrong place, but I have not found any tests for this GUI part.
I've made two small videos showing the change.
Before 👇 
https://user-images.githubusercontent.com/9095073/108766397-06af1080-754d-11eb-830a-5802726f2ba9.mov
After 👇 
https://user-images.githubusercontent.com/9095073/108766417-0c0c5b00-754d-11eb-9862-628e3adba4e2.mov
> Select search text input when focusing it

- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useJoplinMode.ts
- Make closing `$` regex tolerant to punctuation characters directly after `$`
Closes #4554
> Desktop: Resolves #4554: Improve mathmode syntax highlighting

- packages/tools/locales/fr_FR.po
> Fix typo in "ortograph(e|ique)

- packages/app-mobile/android/build.gradle
As per https://github.com/facebook/react-native#-requirements
> React Native apps may target iOS 11.0 and Android 5.0 (API 21) or newer
Resolves https://github.com/laurent22/joplin/issues/4585
> Android: Set min android version to 5 / sdk 21

- packages/app-mobile/package-lock.json
- packages/app-mobile/package.json
I have made a change in `react-native-share` https://github.com/react-native-share/react-native-share/pull/968. This PR is to use this change for Joplin.
This may help with sharing attachments from Joplin to other apps on Android 11. I say "may" because in my tests with emulator it resolved issues with sharing to some apps, but there was at least one app for which this change made no apparent difference.
Might be that the target needs to support Android 11 too.
> Mobile: Upgrade react-native-share

- packages/app-mobile/root.tsx
The issue was reported on the forum here https://discourse.joplinapp.org/t/items-shared-to-android-not-saved/12321/17
When the app is in the background and the user triggers a quick action, in some cases the listener that is set here
https://github.com/laurent22/joplin/blob/ccbc329cbf806e9b6db6d37f8c837629ee6c3a60/packages/app-mobile/setUpQuickActions.ts#L52
is not being called. I suspect that Android creates a new activity but then react-native attaches the existing JS context to it, but this is just a guess. In any case moving quick actions set up to `componentDidMount` fixes it as this method is always called.
For iOS I left everything as it was, since I have no way to ensure this change does not break anything there.
> Android quick actions fix

- docs/desktop/index.html
On the website the "menu" link in the top doesn't do anything, as the menu is made permanent, so commenting that will help!
resolves #4560
> Removed the Menu tag.

- packages/lib/shim-init-node.js
(Sorry for the catchy title, couldn't help myself.)
Due to a typo Keep-Alive wasn't sent so each time http connection has to be re-established from scratch).
I have tested this with a server in my local network using plain http and got these results:
* Before the change
```
21:10:38: CommandService::execute: synchronize false
...
21:13:34: Sync: finished: Synchronisation finished [1614978638697]
```
almost exactly 3 minutes
* After the change
```
21:21:15: CommandService::execute: synchronize false
...
21:23:19: Sync: finished: Synchronisation finished [1614979275473]
```
~2 minutes, so 30% speedup. For https I expect the effect would be even greater. Not too bad for a one-symbol change.
Total synced volume was 188,621,312 bytes, items:
```
main-html.js:48 21:23:19: Operations completed: …
```
> Desktop: Speed up WebDAV/Nextcloud sync by ~30% (or even more)

- packages/app-mobile/components/screens/notes.js
Reported on the forum https://discourse.joplinapp.org/t/items-shared-to-android-not-saved/12321/41
I have added some extra logging and found that a shared note was not saved because NoteScreenComponent's back handler was not called, and this is where the note is saved.
Instead I saw that Note**s**ScreenComponent's back handler was being called because it was registered later.
I think this is what's happening:
* NotesScreenComponents mounts, the execution gets to
```
await this.refreshNotes();
```
and suspends
* Then shareHandler starts and opens a new note screen, NoteScreenComponent mounts and its back handler is registered
* Eventually the execution of `NotesScreenComponent.componenDidMount` from step 1 is resumed and its back handler is registered last.
* Now when the user goes back …
> Mobile: fix items shared to android not saved

- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useJoplinMode.ts
This disables math highlighting when katex rendering is turned off.
I intend to make a few more changes to the markdown parser here but I'm just getting re-acquainted with it now.
> Toggle math highlighting in editor

- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useJoplinMode.ts
Followup to #4554 
This makes the situational highlighting of inline katex identical to the renderer as far as I can tell.
I didn't change block highlighting because it's a bit tricky with the CodeMirror parser and users aren't likely to accidentally use semi-valid katex block syntax.
> Bring editor katex highlight in line with renderer

- packages/app-desktop/tools/compile-package-info.js
- packages/lib/versionInfo.ts
We are no longer building releases from master.
Travis CI runs from a detached HEAD state, which makes it impossible to tell the branch.
I still think that it is imoprtant to show the branch in the About window.
It helps narrowing down issues should people compile from their own branch and it helps developers to see on which branch they are running.
This change only changes the name of the branch to `dev` in a detached state.
> remove branch name in detached head state

- Joplin_install_and_update.sh
Electron framework has a problem due to kernel params in Debian 10 Buster.
This is a (temporary (I hope)) patch to disable sandboxing in the .desktop file for that distro.
> Linux Install: SUID sandbox helper install patch

- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx
- packages/app-desktop/gui/NoteTextViewer.tsx
Resolves https://github.com/laurent22/joplin/issues/2810
Am familiarizing myself with the Joplin codebase and thought of this simple fix for the linked issue. It doesn't seem as if anyone is working on the issue at the moment, so I decided to submit a PR. Apologies if this PR is stepping on anyone's toes.
Decided to make the change where the editor handles the `"editor.focus"` command - every other approach seemed like it would require a lot more code.
I only pushed the fix to the `CodeMirror` component because I read on some other issues that Joplin isn't using the other editors.
Here is a short GIF displaying the behaviour from this PR:
> Desktop: Resolves #2810, Ctrl+Shift+B focuses on viewer when editor is not visible

- readme/gsoc2021/ideas.md
README: GSOC 2021 : Project Ideas: Paste Special :  
There is a typo in the spelling of the Paste Special Project Idea in this Documentation.
Previously it was written as : eadch, and I have changed it into : each
> Readme : GSOC 2021 : Project Ideas : Fixed a Typo in the Paste Special Section

- packages/renderer/MdToHtml/rules/mermaid.ts
The white space in the mermaid markup is removed during parsing by TinyMCE if it's not in one of [these](https://github.com/tinymce/tinymce/blob/ad61fbbe14ce58174ef7c8635c368696c61c18fd/modules/tinymce/src/core/main/ts/api/html/Schema.ts#L471) tags and that caused mermaid to throw a syntax error.
Simply changing the wrapper tag from `div` to `pre` preserves all the newlines, without affecting any other functionality.
Here's the split view (unchanged by this PR):
Here's the broken WYSIWYG view:
And here's the fixed diagram:
> Desktop: Fixes: #4612: Fix mermaid diagrams in WYSIWYG editor

- packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx
The problem was with the table button remaining focused after closing the table
> Desktop: Fixes #4398: Wrong background color for toolbar table button

- packages/app-desktop/gui/ConfigScreen/controls/plugins/useOnInstallHandler.test.ts
- packages/app-desktop/gui/ConfigScreen/controls/plugins/useOnInstallHandler.ts
Fixes #4683. 
The problem was that the plugin's setting were reset to defaults after an update, but the "enabled" flag was not preserved.
> Desktop: Fixes #4683: Updating a disabled plugin enables it

- packages/app-desktop/style.css
Fixed the broken calendar styling as mentioned in issue : #4397  
Attaching Before- After pictures:
> Desktop: Fixes #4397: Fixed Broken Calendar Styling

- packages/app-desktop/gui/ConfigScreen/controls/plugins/useOnInstallHandler.test.ts
- packages/app-desktop/gui/ConfigScreen/controls/plugins/useOnInstallHandler.ts
Fixes #4723 
When plugins are installed not through the GUI, the corresponding `PluginSetting` is only created when a setting is changed (plugin is disabled for example). So when the `useOnInstallHandler` hooks tries to get the enabled flag during an update, so that it can save it, the setting might still be undefined.
> Desktop: Fixes #4723: Plugin Update error when plugin was installed manually

- packages/app-mobile/components/NoteBodyViewer/NoteBodyViewer.tsx
Suggesting a fix for the the flashes of white occurring when opening notes on mobile, most visible with dark themes.
Tested on iOS.
This PR does not target desktop which also received two valuable reports as comments to the ticket:
- [OS X](https://github.com/laurent22/joplin/issues/4450#issuecomment-780287026) by @Jegber
- [Windows](https://github.com/laurent22/joplin/issues/4450#issuecomment-787198109) by @jleighton
> Mobile: Fixes #4450: Background flashes white when opening notes in the iOS app

- packages/app-desktop/app.ts
- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx
- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useJoplinMode.ts
- packages/lib/markdownUtils.ts
- packages/lib/models/Setting.ts
This adds forced monospace for Tables, Code blocks and Checkboxes in the CodeMirror editor. 
This was briefly [discussed on the forum](https://discourse.joplinapp.org/t/plugin-rich-markdown/15053/71)
For checkboxes and code blocks, I piggy back on the CodeMirror highlighting and add the monospace class.
For tables I couldn't do that. Instead table check for a valid header, and then enter table mode. This just means that all lines following the valid header will be monospace until a line is reached that does not contain a '|' character.
I also enforce monospace on any line that begins with a '|', the assumption being that those lines are likely going to become a part of a table, and it's better to start writing in monospace rather than snapping to monospace once the header is finished. …
> Desktop: Add monospace enforcement for certain elements

- packages/lib/shim-init-node.js
This is a follow up to https://github.com/laurent22/joplin/pull/4625
I ran a test on Windows 8:
* Version 1.7.11 - no Keep-Alive
```
22:56:40: Preparing scheduled sync
...
23:03:08: Operations completed:
```
~6.5 minutes
* Dev build with Keep-Alive
```
21:33:49: Preparing scheduled sync
...
21:37:13: Operations completed
```
~3 minutes
The sync was pretty fast as the server was on the same network and did not have https. As with Linux, I expect the difference to be much higher with https enabled.
> Desktop: Set keep-alive for WebDAV/Nextcloud sync

- packages/app-cli/tests/support/plugins/toc/src/index.ts
- readme/api/tutorials/toc_plugin.md
Change joplin.workspace.onNoteContentChange to joplin.workspace.onNoteChange as the former is deprecated.
Change joplin.views.panels.create() to joplin.views.panels.create('panel_1') as it needs an string id now.
Change joplin.views.createWebviewPanel() to joplin.views.panels.create('panel_1') as the former dosn't exist anymore.
> Doc: Update toc_plugin.md

- .eslintignore
- .gitignore
- packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx
- packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/utils/getCopyableContent.test.ts
- packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/utils/getCopyableContent.ts
Fixes part of #4602. For background please read https://github.com/laurent22/joplin/issues/4602#issuecomment-803774665.
The `?t=` was actually needed to update the image when it changes in the editor. Reference -> 
https://github.com/laurent22/joplin/blob/656673ed57bd0d3a010a4d28f6852c01a0e64730/packages/lib/models/Note.ts#L164-L166
So, the best solution I could think of is removing the timestamps manually while copying (if they exist) in image tags.
I couldn't write the unit tests because I couldn't find other unit tests related to TinyMCE editor. Can someone please tell where are those written?
I tested the changes from my end and they seem to work perfectly but I would also request other members to also test the changes manually once.
1. Import an image in the joplin editor.
2. Copy …
> Desktop: Partially fixes #4602: Remove timestamp while copying images

- packages/lib/themes/solarizedDark.ts
I have made a few changes to the Solarized Dark theme based on the colours and guidelines [here](https://ethanschoonover.com/solarized/) (suggested by @jurf). 
To test it, I just ran the desktop app and checked that the colours, especially for hovered and currently selected items were what I intended them to be. 
This is a preview of how it looks:
> Desktop: Fixes #3887: Adjusted Solarized Dark colours to better fit theme

- Joplin_install_and_update.sh
The `--show-progress` flag was introduced in wget 1.16 (2014). CentOS 7 only has wget 1.14.
> Desktop: Resolves #4733: restore installer compatibility with older wget versions

- packages/app-desktop/gui/NotePropertiesDialog.jsx
This is a quick but not long-term fix to the issue [#4658](https://github.com/laurent22/joplin/issues/4658).
@roman-r-m @laurent22 @CalebJohn 
- Added a copy button next to the **ID** field.
- Prevented showing the default context menu when right-clicking on the **ID** value.
```
const { clipboard } = require('electron');
.
.
.
clipboard.writeText(value);
```
This is by no means the best way to implement the functionality and there should be some sort of abstraction that hides away the details of electron clipboard object. I very much encourage people who have more knowledge to modify this. However, in the meantime, this is the quickest way to do it.
- Add a tooltip to the copy button for a better user experience.
- Add a small dialog that indicates the text has been copied successfully.
> Desktop: Fixes #4658: Added a copy button and prevented showing default context menu

- packages/app-mobile/root.tsx
Fixes #4743
Noticed that if I log `BaseSyncTarget` in `root.tsx` just before calling `reg.scheduleSync` and from inside `reg.scheduleSync` at the very first line, these are 2 different things:
* In root it's an object:
```
[object Object]
```
* In reg it's a function:
```
function BaseSyncTarget(db) {
var options = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : null;
_classCallCheck(this, BaseSyncTarget);
this.synchronizer_ = null;
this.initState_ = null;
this.logger_ = null;
this.db_ = db;
this.options_ = options;
}
```
WTF Javascript???
Changing the import fixes it, and I don't even want to know why.
> Mobile: make sync icon spin again

- packages/app-mobile/components/screens/Note.tsx
This PR doesn't have test units. It's a one-line-code UI bug fix that prevents keyboard on iOS (iPhone in particular) from covering the last line of note.
I did the following manual test on iPhone 12, iPhone 11 Pro Max, iPhone SE:
1. Create a new note
2. Type multiple lines of text (enough to fill one page)
3. Try to scroll to the bottom of the note when editing, making sure that the last line is visible & editable
> iOS: Fixes #3607: keyboards won't cover last line of note

- .eslintignore
- .gitignore
- packages/app-mobile/components/NoteBodyViewer/hooks/useOnResourceLongPress.ts
- packages/app-mobile/package-lock.json
- packages/app-mobile/package.json
- packages/app-mobile/root.tsx
- packages/app-mobile/utils/ShareUtils.ts
This is prompted by this bug report on the forum: https://discourse.joplinapp.org/t/android-lost-access-to-resources/15716/4
The issue here is a combination of 2 older bugs I've fixed before: https://github.com/laurent22/joplin/pull/4557 & https://github.com/laurent22/joplin/pull/4373 and a quirk in how Joplin handles deletion.
* Because of one of the above bugs, a resource ended up stored in Joplin with an empty title.
* When the user shared the resource, Joplin tried to copy the resource to give it the original name (taken from the title), but since the title was empty the copy failed.
https://github.com/laurent22/joplin/blob/ccbc329cbf806e9b6db6d37f8c837629ee6c3a60/packages/app-mobile/components/NoteBodyViewer/hooks/useOnResourceLongPress.ts#L27-L32
* For some reason RN copy …
> Android: Fix sharing items from Joplin

- packages/app-desktop/gui/ClipperConfigScreen.jsx
- packages/lib/BaseApplication.ts
- packages/lib/services/EncryptionService.ts
It came up a few times that there wasn't a way to renew the token. Now there is. ;-)
> Desktop: add an option to renew the API token

- packages/app-cli/tests/reducer.js
- packages/lib/reducer.ts
Prevent Goto anything from changing notebooks when 'All Notes' is selected.
Fixes #4697
1. Click on `All Notes` .
2. open goto anything.
3. Now search for a note from a different notebook. 
4. `All notes` stays selected and just the note is switched.
Here's a video showing UI interaction after the changes.
Works as usual when All Notes isn't selected and do not change notebooks when it is.
https://user-images.githubusercontent.com/17108695/112754381-7b1c1a00-8ff9-11eb-9a00-086f80394976.mp4
> Desktop: Fixes #4697: Prevent Goto anything from changing notebooks

- packages/app-cli/tests/support/plugins/dialog/src/index.ts
- packages/app-desktop/services/plugins/hooks/useSubmitHandler.ts
Resolves #4766 by preventing the onSubmit function to be called (if exists) when ENTER key is pressed while a textarea is active. 
I've tested this by adding a 4th dialog to the demo dialogs plugin that has just a text area and indeed pressing ENTER whilst it's focused didn't submit. However, the rest of the forms submitted on ENTER normally. *(Including the text area one when textarea not in focus)*
I'm not sure how to "properly" add a feature test to this. Not sure if it's even possible as I couldn't find any existing tests for plugin system at all. 
I haven't worked with unit tests in a way that interacts with UI before frankly so lmk if there's anything I missed!
> Desktop: Resolves #4766: ENTER key no longer submits dialogs when a textarea is focused.

- packages/app-desktop/gui/NoteEditor/utils/useMessageHandler.ts
This PR fixes the issue #4043. Currently, clicking on any File-links containing German Umlauts (on platform: windows) gives an error in the console. Most likely, the issue is with electron's `shell.openExternal()`, although the issue is fixed by using the `shell.openPath()` which opens the given local file with German Umlauts(and other special characters as well like Chinese etc.) correctly.
```
**Tests without umlaut:**
<h:/test.txt> not rendered as link
<file://h:/test.txt> ok
[local file](h:/test.txt) ok
[local file](file://h:/test.txt) ok
**Test with umlaut:**
<h:/test_with_umlaut_ä.txt> not rendered as link
<file://h:/test_with_umlaut_ä.txt> Working
<file://h:/test_with_umlaut_%C3%A4.txt>  Working (ä changed with %C3%A4 for UTF-8 encoding)
[local file with umlaut with …
```
> Desktop: Fixes #4043: Update 'useMessageHandler.ts' to allow File-Links with German Umlauts 

- packages/app-cli/tests/models_Note.ts
- packages/lib/models/Note.ts
When duplicating a note, the tags are not duplicated, or is this behavior intended?
> All: improvement #3985 #3157: Also duplicate the tags when the note is duplicated

- packages/app-desktop/gui/NoteEditor/utils/useDropHandler.ts
https://discourse.joplinapp.org/t/cursor-moved-to-the-top-undo-history-removed/16837/6
It looks like there's a case where the dataTransfer element of the drop event is null (see the attached forum post). I don't know what causes this situation, but it makes sense to guard against it like we do for files later on in the function.
> Desktop: Check if dataTransfer is non-null on drop

- README.md
- packages/app-desktop/index.html
- packages/app-desktop/services/plugins/UserWebviewIndex.html
- readme/api/references/plugin_theming.md
This change links the Roboto, Icomoon, and Font-Awesome stylesheets into the index.html used by all plugins.
This makes the fonts available to all plugins, w/out the plugin needed to package and ship the font.
I tested manually by comparing the presentation of Joplin with the Favorites and Outline plugins installed. Without this change, Outline displays incorrectly. With it, both plugins have the correct presentation.
> Desktop: Fixes #4754: Roboto font in plugins

- packages/app-desktop/gui/SearchBar/SearchBar.tsx
Fixes #4736.
Adds a check for an empty query string in the input onChange handler for the searchbar. 
If the query is empty, the search exits and displays all the notes in the current notebook. Focus is retained on the searchbar.
- Select the searchbar present in the Note List 
- Type something to get a few results
- Clear the input
- The complete list of notes in the notebook should be visible
Unaware of how to add any automated tests for this currently but the manual testing probably suffices for this. Here is a demonstration of the manual tests, before and after the fix : 
**Before :** 
**After :**
> Desktop : Resolves #4736 Note list is empty if search field is cleared.

- packages/lib/WebDavApi.js
Fixes https://github.com/laurent22/joplin/issues/4706 and maybe other sync failures too.
The issue reported on Android but I think it makes sense to disable caching everywhere as we need to get the latest data from the server when syncing.
> All: Disable WebDAV response caching

- packages/app-desktop/index.html
- packages/renderer/noteStyle.ts
Resolves #3991 
- Added simple CSS line `unicode-bidi: plaintext;` to both CodeMirror styling and noteStyle file which defines how notes look on all platforms.
This was suggested by someone over at MarkdownIt repo:  https://github.com/markdown-it/markdown-it/issues/635#issuecomment-582064491 
It automatically decides whether a line should be RTL or LTR depending on the content. It's still pretty annoying/buggy when you mix RTL with LTR in the same line though so I wouldn't recommend doing that.
This obviously can't be unit tested, so Screenshots will have to do!
> **^ Notice on mobile, the editor ALREADY looks fine,**
> Mobile, Desktop: Fixes #3991: Added RTL support for CodeMirror and Preview.

- packages/app-desktop/gui/ResizableLayout/utils/useLayoutItemSizes.test.ts
- packages/app-desktop/gui/ResizableLayout/utils/validateLayout.ts
Fixes #4529.
The problem was that the `updateItemSize` function didn't handle non-visible items at all. It should only count items as fixed size, which are visible and it should only make visible items flexible.
To achieve this, for each item I had to find out whether it is last visible item in it's parent. For this, I loop through the sibling items in reverse order and on the first visible one check whether it's the current item. If not we break, if yes we continue looping to find out whether all siblings have a fixed size. This is a bit less efficient than how it was, but it works.
I've also included a test case in the existing test file for useLayoutItemSizes.
Steps to test manually:
---
You can use my kanban mockup plugin to quickly have a plugin panel for testing. Here's the jpl …
> Desktop: Fixes #4529: Ghost panel and resizing issues

- .eslintignore
- .gitignore
- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useCursorUtils.test.ts
- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useCursorUtils.ts
Before 
After Fix
Steps:
1. Copy paste following content to joplin
item1  
item2  
item3  
a paragraph
2. Take cursor to beggining of document and press `shift+down arrow` thrice to select 1st 3 lines.
3. Toggle list using editor toolbar.
> Desktop: Resolves #4813 : skip empty lines while converting selection to list 

- packages/generator-joplin/generators/app/utils.js
- packages/generator-joplin/generators/app/utils.test.js
If the local ignore file has CR LF as line ending, previously equal lines from the template and local ignorefile where duplicated.
> generator-joplin: Fix handle CRLF on mergeIgnoreFile

- readme/faq.md
Since these questions have already appeared several times in the forum, I would like to include them in the FAQ section.
> Add sync status to FAQ

- packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx
- packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/utils/useContextMenu.ts
- packages/app-desktop/gui/NoteEditor/utils/contextMenu.ts
- packages/app-desktop/gui/NoteEditor/utils/useMessageHandler.ts
Fixes: #4891 
A function `openItemById` is created inside `app-desktop/gui/NoteEditor/utils/contextMenu.ts` just to avoid duplicate code. The `useMessageHandler` hook and  `menuItems`  both use the `openItemById` function so that the user gets the same experience on `ctrl+click` or `right-click+open` a link.
Manually tested both on markdown editor and the TinyMCE editor( with note-links, resource-links; performing both the operations: `ctrl+click` and ` right-click+open` ).
Sorry ( again ), I couldn't find a way to write a unit test for it. Maybe it is possible to add a test, but I think it would be very ( very) complex ( so need some guide ).
> Desktop: Fixes #4891: Solve "Resource Id not provided" error

- README.md
I use OpenSUSE Tumbleweed as my Linux distribution with KDE Plasma as my desktop environment and I couldn't get notifications to work even after following the instructions on README (installing `notify-osd`) and checking the `node-notifier` library. After investigating using debug mode I discovered that `libnotify-tools` was the right repository to get the `notify-send` tool to actually make it work. I hope that changing this line of code could get Linux users to fix this error easier on their distro. BTW I removed the part about `growl` because it is a retired project specific to old MacOS.
> Documentation: Improved Linux notifications instruction

- packages/app-desktop/gui/ResizableLayout/ResizableLayout.tsx
- packages/app-desktop/gui/ResizableLayout/utils/useLayoutItemSizes.test.ts
- packages/app-desktop/gui/ResizableLayout/utils/useLayoutItemSizes.ts
Fixes #4864 (specifically the issue [raised in this comment](https://github.com/laurent22/joplin/issues/4864#issuecomment-843288171), the original seems to have been fixed already).
The problem was that the layout logic had no way to handle maximum sizes, so if a panel was too big it simply overflowed and could even push other panes completely off-screen (see recordings below).
My fix is to add a extra logic to `useLayoutItemSizes()`, which
1. keeps track of the minimum space that should be reserved, such that all panels are visible (using the `minWidth`/`minHeight` props or `40px` per pane if not defined)
2. if the panes with definite size don't leave enough room, makes the largest one smaller
3. calculates a maximum possible size for each pane
The calculated max size is then passed to …
> Desktop: Fixes panels overflowing window

- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useCursorUtils.test.ts
- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useCursorUtils.ts
These changes are related to/have a minor conflict with PR #4832. Please let me know how I can help get that PR merged, then I can rebase and add some additional test cases. I would also be happy to port the testing changes over to my branch and add test cases.
Here is what I found through manual testing (the expected behavior is the behavior after this patch):
_Note_: **Case C** and **Case D** were working and continue to work, just wanted to test all the code paths.
1. Create new note
1. Enter text
```
1. item1
2. item2
3. item3
```
1. Drag select all 3 lines
1. Press numbered list
```
4. 1. item1
5. 2. item2
6. 3. item3
```
```
item1
item2
item3
```
1. Create new note
1. Enter text
```
1. item1
2. item2
3. item3
```
1. Ctrl+A
1. Press numbered list
```
2. 1. item1
item2
3. 3. item3
``` …
> Desktop: Fixes #4877: Incorrect list renumbering

- .eslintignore
- .gitignore
- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx
- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/Editor.tsx
- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useJoplinCommands.ts
- packages/lib/services/plugins/api/JoplinCommands.ts
I was helping @tessus with something and it came up that this could be useful. And actually with the wording I think the previous behaviour was a bit confusing/wrong.
> Desktop: Support executing codemirror commands when using execCommand

- packages/app-mobile/components/screens/search.js
- packages/lib/BaseApplication.ts
- packages/lib/services/rest/routes/search.ts
- packages/lib/services/rest/utils/defaultLoadOptions.ts
- packages/lib/services/searchengine/SearchEngineUtils.test.ts
- packages/lib/services/searchengine/SearchEngineUtils.ts
As discussed I have made a fix for the error #5007 The API search filtered all notes when showCompletedTodos is set to false.
I have added the option `applyUserSettings` to the `defaultLoadOptions`, as this is only used in the API/routes. I hope this is OK. 
Or is it better to set this only for `routes`?
> All: Fixes #5007: Items are filtered in the API search

- packages/app-mobile/android/app/src/main/java/net/cozic/joplin/MainApplication.java
- packages/app-mobile/android/app/src/main/java/net/cozic/joplin/textinput/TextInputPackage.java
Resolves https://github.com/laurent22/joplin/issues/4216
Resolves https://github.com/laurent22/joplin/issues/2287
---
Related RN issue (one of): https://github.com/facebook/react-native/issues/29911
This is more of a workaround than a proper fix, I think, but judging by the lack of activity on the above issue it won't be fixed anytime soon.
I tested it and it seems to work without any negative side-effects. Maybe one side effect is that when you switch to edit mode you can't select text by dragging before tapping once to focus the editor. But this hasn't worked before anyway.
Just don't ask me to explain why it works.
> Android: Focus note editor where tapped instead of scrolling to the end

- packages/lib/services/searchengine/SearchEngineUtils.test.ts
- packages/lib/services/searchengine/SearchEngineUtils.ts
It's kind of a shame, but I put a bug in the last fix #5007.  
If is_todo or todo_completed where added automatically, the wrong one was removed in the results.
I had not noticed this because I had always tested it in combination, so I have now added a test for the fields `id`, `is_todo` and `todo_completed`.
> All: Fixes: Wrong field removed in API search

- .eslintignore
- .gitignore
- packages/app-desktop/app.ts
- packages/app-desktop/gui/MainScreen/MainScreen.tsx
- packages/app-desktop/gui/MainScreen/commands/showPrompt.ts
- packages/app-desktop/gui/menuCommandNames.ts
Adds a command to show the prompt and get the user input so that it can be used by plugins.
> Desktop: Expose prompt to plugins as a command

- Joplin_install_and_update.sh
Use --no-sandbox option for Linux Mint LDME 4 Debbie as well.
Linux Mint LDME 4 Debbie is based on Debian 10 and therefore the same hack with --no-sandbox is requried.
Resolves #5105
> Desktop: Fix Linux Installer for LDME4 Debbie

- packages/lib/services/plugins/api/JoplinViewsDialogs.ts
Just fixed a small typo in the comments.
> Docs: Fix a typo in JoplinViewsDialogs.ts comments

- .eslintignore
- .gitignore
- README.md
- packages/lib/services/searchengine/filterParser.test.ts
- packages/lib/services/searchengine/filterParser.ts
If a `:` is used in the search, the word before it is interpreted as a search filter, even if this filter does not exist.
The search `https://github.com` throws an error `Invalid filter: https`.
The search `https://github.com` is not parsed as a filter `https`, insteand a phrase word search is performed.
The whole thing could also be avoided by searching with semicolons `"https://github.com"`.
But from a user-friendliness point of view, I think the optimisation is an advantage.
> All: Resolves #3871 Interpret only valid search filters

- packages/lib/services/plugins/api/types.ts
This fix is only relevant to plugins. The correct signature is demonstrated in the [documentation][1] for CodeMirror content scripts, but not correctly typed in the code. The signature in the code matches the one used in the [documentation][2] for MarkdownIt content scripts, but that documentation uses `webviewApi.postMessage` (without documenting how to get that value) instead of `context.postMessage`. Using the documented API for CodeMirror content scripts creates a type error without the fix in this PR.
[1]: https://github.com/laurent22/joplin/blob/5ee2ffe174369d23db4eaaa23e353e8b3b08bb71/packages/lib/services/plugins/api/types.ts#L613
[2]: https://github.com/laurent22/joplin/blob/5ee2ffe174369d23db4eaaa23e353e8b3b08bb71/packages/lib/services/plugins/api/types.ts#L508
> Fix type of PostMessageHandler

- Dockerfile.server
- packages/tools/buildServerDocker.ts
A small PR that adds labels for the docker image,  so that with docker inspect can determine which version is being used. 
`docker inspect d36f462df14e`
> Server: Improvement image labels

- packages/lib/themes/light.ts
When using the iOS simulator the format without commas would trigger a warning and block rendering of the log because of it. This matches the other examples in the file so I don't expect any trouble across platforms or any unintended side effects.
> All: Update light.ts colorWarn to valid format for iOS

- packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx
See also the feature request at https://github.com/tinymce/tinymce/issues/6700. I later realized that Joplin has its own `lists.js` plugin, so I implemented it there.
Tested manually on Linux (KDE), it works.
Open questions:
> Desktop: Add keyboard shortcuts for inserting lists

- readme/download.md
https://discourse.joplinapp.org/t/poll-what-should-joplin-tagline-be/18487/31
Note: 
- I changed the headline to "Downloading Joplin..." to make it clear that something was happening. Should probably be "Download Joplin" if the download doesn't start immediately.
- I added a placeholder for **[Joplin for Mac]** that I would want to be replaced with the OS you are downloading on
- I think the "Joplin App for Desktop" section should stay, even when you are able to auto download. That shows the user that Joplin is available on multiple OSs.
> Documentation: Update download.md

- packages/lib/Synchronizer.ts
A very minor bugfix/cleanup
Looks like a leftover from before resource conflicts were added. When the local item is a resource, the action cannot possibly be `itemConflict` but must be `resourceConflict` instead.
> Remove unused condition in synchronizer

- packages/app-cli/tests/support/plugins/dialog/src/index.ts
- packages/app-desktop/gui/MainScreen/MainScreen.tsx
- packages/app-desktop/services/plugins/UserWebview.tsx
- packages/app-desktop/services/plugins/UserWebviewDialog.tsx
- packages/lib/services/plugins/WebviewController.ts
- packages/lib/services/plugins/api/JoplinViewsDialogs.ts
This SHOULD add to the Dialogs API 3 new properties: 
- `useCustomSizing`
- `customWidth`
- `customHeight`
When `useCustomSizing` is set to false, which is the default value, the dialog sizing is automatically determined the same way as it used to. However, when it's true, the values of `customWidth` and `customHeight` are used instead to assign the values. 
The point of this change is that I'd be able to do something like: 
```js
await joplin.views.dialogs.useCustomSizing(true);
await joplin.views.dialogs.setCustomWidth('75vw');
await joplin.views.dialogs.setCustomHeight('80vw');
```
This will enable dialogs to be created with dynamic sizing.
> NOTE the units used, `vw` and `vh` and NOT absolute pixels. Although pixels can still be used, the power of this change is being able to use `vw` …
> Desktop: Add ability to provide custom sizing for dialogs.

- packages/app-cli/tests/support/plugins/dialog/src/index.ts
Simply fix a typo in the sample dialog.
> Desktop: Fix wrong variable name

- packages/server/README.md
- packages/tools/buildServerDocker.ts
Add docker tags for major, minor and beta version
- `latest` are always the most recent released version
- `beta` are always the most recent beta released version
- Major versions, such as `2`, `2-beta`
- Specific minor versions, such as `2.1`, `2.2`, `2.3-beta`
- Specific patch versions, such as `2.0.4`, `2.2.8-beta`
Is the content of the docker hub page updated automatically?
> Server: Add docker major, minor and beta version tags

- packages/app-mobile/components/side-menu-content.js
Back with a simple fix that is now confirmed working.
This changes the icon spin direction to match desktop. I confirmed this works on iOS.
@roman-r-m could you check on Android?
> Mobile: Update Sync icon spin direction on mobile Fixes #4588

- packages/app-desktop/gui/utils/NoteListUtils.ts
- packages/lib/services/commands/MenuUtils.ts
The `enabledCondition` was simply ignored completely when adding buttons to the NoteListContextMenu. I've added the needed condition to only append commands that are enabled according to commandService's `isEnabled`.
I noticed that the code in NoteListUtils apprently is outdated ? Like it doesn't use any of the CommandService stuff about comnmandEnabled and when clauses but simply does the checks manually. I focused my changes on the plugins part and left the others.
I've tested this in my own plugin via having a command that only works with `inConflictFolder` and the button indeed now only shows for notes inside the Conflict Folder. Not the outside.  I'm not sure if unit tests are needed for this change.
> Desktop: Added enabled check before adding to NoteListContextMenu list.

- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx
- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useJoplinMode.ts
Fixes #5297 
I started out just testing if we could separate the inline and block code styles, and accidentally implemented it and added proper background colours for the code blocks.
I tested this by mucking around with the number of backticks used, and the spacing  between them. But ultimately, this is based on the CodeMirror markdown mode variables, so it should be fairly safe, unless there is an upstream bug.
> Desktop: Resolves #5297: Add css classes for code in the markdown view

- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx
- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useJoplinMode.ts
Followup to fix an issue introduced in #5314
Instead of applying the code block class to the line itself, this changes it to create a CodeMirror background element. This is the correct way to apply line backgrounds in CodeMirror, but I had a brain fart the other day. 
I've tested this by selecting a code block, as well as searching withing a code block. Should be good now!
> Desktop: Place code-block background in the back

- Joplin_install_and_update.sh
Fixes #5240 
The lsb_release module is used to detect certain platforms that need the `--no-sandbox` flag. This isn't needed for most platforms, and some platforms (notably openSUSE) don't have the lsb_release binary and don't need it.
> Desktop: Linux: Remove dependency on lsb_release from install script

- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx
[ref](https://github.com/laurent22/joplin/pull/5314#issuecomment-900256897)
I was worried it would be hard to read without the padding, but it looks fine to me.
> Desktop: Removes markdown inline code padding

- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx
fixes #5327 
When changing notebooks, or when entering the editor from settings the order that css is loaded changes in which case this bug wouldn't manifest.
> Add more specific classes for CodeMirror elements

- packages/app-cli/tests/support/plugins/dialog/src/index.ts
- packages/app-desktop/gui/MainScreen/MainScreen.tsx
- packages/app-desktop/services/plugins/UserWebview.tsx
- packages/app-desktop/services/plugins/UserWebviewDialog.tsx
- packages/lib/services/plugins/WebviewController.ts
- packages/lib/services/plugins/api/JoplinViewsDialogs.ts
I've realized my issue. I assumed that UserWebview was only used by dialogs which was fatal haha. Even when testing I only tested plugins that had dialogs in them and completely forgot that there's other UI elements that shared the same Webview file.
The issue was that `vw` and `vh` are relative to the browser dimensions and not it's parents. This is perfectly fine for dialogs as they're indeed relative to the window but when it comes to panels, those MUST be sized relative to their parent or else they'd have really large dimensions as we saw in Note Tabs plugins.
So a possible fix would be to simply apply the `vw` and `vh` stuff ONLY for dialogs but the rest of UI must still use `100%`. This was achieved by simply moving over the code to `UserWebviewDialog` instead of `UserWebview`
I've …
> Desktop: Resolves #5288: Added back fitContent without breaking panels.

- Dockerfile.server
> Server: Don't bother installing vim in the server docker image since its not needed to run

- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx
- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useJoplinMode.ts
I realized that the current naming will be confusing for users of the CSS who might try to change other aspects of the code block. So now it's split in two and the background element clearly has the background class.
> Desktop: Split code block class in two

- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx
fixes #5364 
This issue turned out to be related to a couple small issues with inline code when the editor isn't in spellcheck mode. Unfortunately, I forgot to toggle the spellcheck mode when initially testing this, so a few things were missed. 
Searching also broken 
Before:
After:
Selection could have looked better
Before:
After:
And vim mode
Before:
After:
> Desktop: Resolves #5364: Disable inline code background in vim mode

- Dockerfile.server
The issue is that node:12 (which uses buildpack-deps:buster) uses quite old libs, among them glibc ..
Now a bunch of the node deps can pull down prebuild libs (especially this was an issue with sqlite) ..
But on armv7 (ie raspberry pi devices) these prebuilt libraries do not exist, and building them from source
requires newer libraries.
Also to instal sqlite from source python seems to be needed.
Also took the opportunity to apply some best practices and merged the layers for the apt installs and cleaned the caches afterwards.
---
This may be a bit of a controversial switch to use node-build, but unfortunately there doesn't seem to be official ubuntu based node base images to use instead of node:12 .. so this may need to be it .. alternate thoughts are welcome :)
> Server: Switch to node:16-bullseye and add python to the image to support building on non amd64 platforms

- Joplin_install_and_update.sh
Minor fix for bash installer script: Debian10+ bash script install breaks on single bracket regex match attempt `[ $DISTVER =~ Debian1. ]`, results in `--no-sandbox` not added to launcher. Changed to double bracket for successful regex match.
> Desktop: fixes Debian version check breakage in installer script due to regex match brackets

- .github/workflows/github-actions-main.yml
- packages/tools/buildServerDocker.ts
- packages/tools/tool-utils.ts
Needs #5202 merged first to actually succeed building on those platforms
- extend execCommand2 to also support streaming stderr (newer docker builds output to stderr, so its a bit silent and hard to see what's going on)
- Switch up the docker build script to build multi-platform images, currently supporting amd64, armv7 and arm64
> Server: Enable multi platform builds

- packages/lib/reducer.test.js
- packages/lib/reducer.ts
This small patch suppresses unnecessary redundant `selectedNoteIds` events from a NOTE_UPDATE_ALL action.
It also fixes the symptom reported in #5447. But, it's not the main cause of the issue. 
The details are described in the issue.
> All: Fix #5447: onNoteSelectionChange() is triggered twice after a search

- Joplin_install_and_update.sh
This should make everyone nervous, in all circumstances: `rm -rf $var` 
This is always safer: `rm -rf "$var"`
Similarly for the other cases.
> Desktop: Properly quote variables in installer

- packages/lib/services/searchengine/SearchFilter.test.js
- packages/lib/services/searchengine/filterParser.ts
If a filter is written in quotation marks, the search term that follows it is also incorrectly evaluated as a filter of the same type and not as a search term.
> All: Resolves #5444 Misinterpreted search term after filter in quotation marks

- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useKeymap.ts
This is usually set by default in CodeMirror on macOS. This change just adds it back.
/ref https://discourse.joplinapp.org/t/command-backspace-to-delete-line-macos/20285?u=tessus
> macOS: add CM shortcut delWrappedLineLeft

- packages/lib/BaseApplication.ts
This change allows users to run the app together with chromedriver. The flag is passed by chromedriver and can't be suppressed there. In #2084 a related flag was ignored.
> ignore the user-data-dir flag

- packages/tools/locales/fr_FR.po
- Added remaining missing translations
- Corrected some translations
- Replaced some characters by better Unicode alternatives such as:
- ... → … (U+2026)
- A → À (U+00C0)
- " :" → " :" (non-breaking space: U+00A0)
- \- → ‑ (non-Breaking Hyphen: U+2011)
> Update French translation

- readme/spec/server_sharing.md
Line 17 had " This" tacked onto the back like someone started writing something or removed something and left remnants. This simply removes that extra word.
> Remove orphaned word on Line 17 of server_sharing.md

- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx
- packages/app-desktop/gui/NoteTextViewer.tsx
- packages/app-desktop/gui/note-viewer/index.html
Issue https://github.com/laurent22/joplin/issues/2810 was resolved by PR https://github.com/laurent22/joplin/pull/4537 -- Cmd-Shift-B now puts focus on the iframe hosting the note body / rendered Markdown
However, this focus doesn't correctly capture keyboard input -- using the up / down arrows to scroll fails
This PR uses IPC to request the container focus on an invisible anchor inserted at the top of the rendered Markdown. With focus on this contained element, the keyboard input works and arrow keys scroll.
The content's scrollTop is noted before and restored after focus (otherwise, the content would be scrolled to the top).
I have play-tested using hotkeys to
* repeatedly move focus among list, title, and body; arrow keys work in body
* focus to list, arrow down to select another note, …
> via IPC, have webview insert and focus on a dummy element at top of content

- .eslintignore
- .gitignore
- packages/app-cli/tests/MdToHtml.ts
- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx
- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/index.ts
- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useScrollHandler.ts
- packages/app-desktop/gui/NoteEditor/utils/useMarkupToHtml.ts
- packages/app-desktop/gui/NoteTextViewer.tsx
- packages/app-desktop/gui/note-viewer/index.html
- packages/app-desktop/gui/utils/SyncScrollMap.ts
- packages/renderer/MdToHtml.ts
- packages/renderer/MdToHtml/rules/source_map.ts
This PR provides the synchronous scroll capability between Markdown Editor and Viewer.
It's based on [CalebJohn's branch](https://github.com/CalebJohn/joplin/tree/sync-scroll), and the following features are added.
- Bi-directional sync-scroll (viewer <-> editor)
- Performance improvements:
- The mapping between line and scroll position is cached.
- Efficiently observing rendering updates to keep scroll consistency
- Some cleanups
Related forum topics and github issue:
- [[Feature request] Better synchronized scrolling in desktop app](https://discourse.joplinapp.org/t/feature-request-better-synchronized-scrolling-in-desktop-app/3609)
- [Syncing Split View (Markdown/Preview)](https://discourse.joplinapp.org/t/syncing-split-view-markdown-preview/12131)
- [When scrolling, the two sides are …
> Desktop: Fix #2242: Sync-Scroll for Markdown Editor and Viewer

- packages/lib/JoplinServerApi.ts
- packages/lib/Synchronizer.ts
- packages/lib/file-api-driver-joplinServer.ts
- packages/lib/file-api.ts
- packages/lib/services/synchronizer/LockHandler.ts
- packages/lib/services/synchronizer/MigrationHandler.ts
- packages/lib/services/synchronizer/synchronizer_LockHandler.test.ts
- packages/lib/services/synchronizer/synchronizer_MigrationHandler.test.ts
- packages/lib/testing/test-utils-synchronizer.ts
- packages/server/package.json
- packages/server/src/db.ts
- packages/server/src/models/KeyValueModel.ts
- packages/server/src/models/LockModel.test.ts
- packages/server/src/models/LockModel.ts
- packages/server/src/models/factory.ts
- packages/server/src/routes/api/debug.ts
- packages/server/src/routes/api/locks.ts
- packages/server/src/routes/routes.ts
- packages/server/src/utils/errors.ts
This is to speed up synchronisation and reduce database load, by reducing the number of lock requests and by avoiding many SQL "LIKE" queries (which were needed to retrieve all the locks of a user). Performance improvement should be significant on databases that have many items.
For now, the lock backend is the database, but it could potentially be moved to any key/value store to reduce the db load further.
**With native lock 325ms - 2 requests**
2021-11-02 10:50:53: App: POST /api/locks (8ms)
2021-11-02 10:50:53: App: DELETE /api/locks/1_3_9fda9b06bde6435cb06ffcb2ebf8be3c (6ms)
**With regular 430ms - 4 requests**
2021-11-02 10:49:59: App: GET /api/items/root:/locks/*:/children (2ms)
2021-11-02 10:49:59: App: PUT /api/items/root:/locks/1_3_9fda9b06bde6435cb06ffcb2ebf8be3c.json:/content …
> Server: Add support for built-in sync locks

- packages/app-desktop/gui/note-viewer/index.html
When intra-Note Search Bar is displayed, switching a note sometimes causes flickering. This is more likely to happen with large notes or notes with images. It sometimes happens in "Welcome to Joplin!" note as well (show in the next comment).
This commit fixes the above symptom.
Additionally, related to the above symptom, a fault-prone code is found in the Markdown Viewer (note-viewer/index.html). It is also fixed.
- When Note Search Bar is enabled, some top level `div` elements (that is, `joplin-container-pluginAssetsContainer`, `joplin-container-markScriptContainer` and `joplin-container-content`) are affected. They should not be touched.
- `rendered-md` div element can be unintentionally recreated. If its reference were used, it would be problematic. (But, I don't know whether concrete …
> Desktop: Fixes flickering with local Note Search Bar

- packages/app-desktop/gui/NoteEditor/NoteEditor.tsx
This PR fixes #5582.
The cause of the bug is `hasChanged` flag of a note is not cleared after the note is saved. So, when sync-ed, a note in Editor is considered as *being edited* and is not updated.
> Fix Desktop: Synced note is not updated in display #5582

- packages/app-desktop/gui/note-viewer/index.html
This PR fixes and improves the previous PR #5496 on the issue [#4827 "Laggy Scrolling in Viewer"](https://github.com/laurent22/joplin/issues/4827#issuecomment-925593345).
Bug Fix:
- In the previous PR, page-wise wheel scrolling was not supported. It can be configured in OS setting (ex. in Win10, at Control Panel > Mouse > Wheel > Vertical > Vertical Scrolling, select `One screen at a time`). If it was set, scrolling was very slow.
- This PR fix the bug.
Improvements:
- Since workaround for laggy scroll is only needed if zoom factor is not 1, native scroll functionality (including smooth scrolling) is used when zoom factor is 1, for safety.
- For non-1 zoom factor, compact and standalone custom smooth scrolling is implemented, for user's comfort.
By integrating this PR, user's UX is the …
> Desktop: Resolves #4827,#5652: Fix and improve laggy scroll fix

- packages/app-desktop/gui/utils/SyncScrollMap.ts
Sync-scroll didn't consider notes markup-ed in html.
By this fix, notes markup-ed in html are supported. 
Limitation:
- The new sync-scroll feature (recently introduced) is not enabled for html-markup notes, and  the old sync-scroll is used. Because they don't have mapping information between source code lines and html elements.
> Desktop: Fix #5694: Sync-scroll supports notes markuped in html

- packages/app-mobile/android/app/src/main/AndroidManifest.xml
This changes the [`android:launchMode`](https://developer.android.com/guide/topics/manifest/activity-element#lmode) of the Android app from `singleTop` to `singleTask`, which I suspect is more appropriate for Joplin:
> `singleTop`: If an instance of the activity already exists at the top of the target task, the system routes the intent to that instance through a call to its `onNewIntent()` method, rather than creating a new instance of the activity.
> `singleTask`: The system creates the activity at the root of a new task and routes the intent to it. However, if an instance of the activity already exists, the system routes the intent to existing instance through a call to its `onNewIntent()` method, rather than creating a new one.
In other words, the current behavior is that two instances …
> Mobile (Android): Makes it impossible to have multiple instances of the app open

- BUILD.md
Closes #5742 
Added `build-essential` as a dependency.
`npm install` fails on fresh install of Ubuntu 20.04 without `build-essential`.
> Updated dependencies for Linux

- packages/app-mobile/package-lock.json
- packages/app-mobile/package.json
- packages/app-mobile/services/AlarmServiceDriver.android.ts
Fixes https://github.com/laurent22/joplin/issues/5216
There was a bug in the library in how alarms are stored to the database. On some devices they were saved in such a way that they could not be read later.
> [Android] Fix alarms

- packages/server/src/services/EmailService.ts
Even when `config.mailer.authUser` and `config.mailer.authPassword` are empty, joplin server still configures the `auth` option on the `SMTPTransport`.
This pull request, changes this behavior by only setting the auth option when  both config.mailer.authUser and config.mailer.authPassword have a value (and are thus set using the environment variables). This allows the EmailService to be used when no authentication to the SMTP server is required.
> Server: Resolves #5790: Do not set the auth option when authUser or authPassword is set

- .github/workflows/github-actions-main.yml
As per https://github.blog/changelog/2021-10-19-github-actions-the-windows-2016-runner-image-will-be-removed-from-github-hosted-runners-on-march-15-2022/
> Tools: Use windows-latest to build desktop app on CI

- docker-compose.db-dev.yml
- docker-compose.server-dev.yml
- docker-compose.server.yml
I'm not sure if sticking to a specific minor version of postgres has more upsides than downsides.
https://www.postgresql.org/support/versioning/:
We always recommend that all users run the latest available minor release for whatever major version is in use.
Major versions usually change the internal format of system tables and data files. These changes are often complex, so we do not maintain backward compatibility of all stored data. A dump/reload of the database or use of the pg_upgrade module is required for major upgrades. We also recommend reading the upgrading section of the major version you are planning to upgrade to. You can upgrade from one major version to another without upgrading to intervening versions, but we recommend reading the release notes of all intervening major …
> All: Use latest minor release of postgres 13 in docker-compose examples

- packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx
This fixes the editor flashing issue mentioned in #5311 (editor goes white when opening notes in dark mode).
https://user-images.githubusercontent.com/2179547/143656642-bf99d2e5-001e-4cac-84c5-e2bc2e574bfd.mp4
https://user-images.githubusercontent.com/2179547/143656640-4cb7cb03-ecd0-46d0-af80-62d323cb3b13.mp4
> Desktop: TinyMCE flashing white when switching notes/editor

- packages/app-desktop/gui/NoteListControls/NoteListControls.tsx
Relates to addition of note sorting in https://github.com/laurent22/joplin/pull/5437/
Noticed that the border radius of the new buttons (5px) was off compared to the original two & the search box (3px) so have amended the values to remain consistent with the rest of the theme.
> Desktop: Changed note sort buttons to 3px radius 

- packages/app-desktop/gui/note-viewer/lib.js
- packages/lib/renderers/webviewLib.js
fix by @jg1969
I've tested the fix on Desktop. Running `npm run buildInjectedJs` did not create any files in the `app-mobile` dir.
This fix is for flowchart diagrams. Links already work for `graph` diagrams.
fixes #5801
> All: fixes #5801: links in flowchart Mermaid diagrams

- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/Editor.tsx
This PR fixes #5872, 'Markdown search no longer scrolls to result'.
The cause of the bug is that excessive negating of scroll events was performed. Concretely, scroll events caused by local searches were ignored, and their positions were reverted. Some other programmatic scrolling caused by CodeMirror was also affected. For example, page up/down didn't work in most cases.
This PR fixes the excessive negating.
> Desktop: Fix #5872: Markdown search no longer scrolls to result 

- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useScrollHandler.ts
This PR fixes a comment of sync-scroll so as to replace an old URL to its new one.
> Desktop: Fix sync-scroll comment to refer a correct URL

- README.md
The Flathub package sources can be found [here](https://github.com/flathub/net.cozic.joplin_desktop). Please consider officially distributing via Flatpak to all Linux distributions.
> Add inofficial Flatpak to installation instructions

- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useEditorSearch.ts
This PR fixes the issue #5549: Desktop: Doesn't jump to the local search result if its count is one.
The cause of the bug is that scrolling to the specified local search result is enabled only if a keyword is changed or a search result index is changed. If the search result count is one, there is no chance that an index is changed.
To fix the bug, scrolling should be enabled if the search result count is 1.
Implementation Note:
- Since the search result count is unknown when the condition is judged, a dummy condition (index is zero) is used.
> Desktop: Fixes #5549: Cannot jump if local search count is one

- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx
- packages/app-desktop/plugins/GotoAnything.tsx
- packages/lib/services/style/themeToCss.test.ts
- packages/lib/themes/aritimDark.ts
- packages/lib/themes/dark.ts
- packages/lib/themes/dracula.ts
- packages/lib/themes/light.ts
- packages/lib/themes/nord.ts
- packages/lib/themes/oledDark.ts
- packages/lib/themes/solarizedDark.ts
- packages/lib/themes/solarizedLight.ts
- packages/lib/themes/type.ts
- packages/renderer/defaultNoteStyle.js
- packages/renderer/noteStyle.ts
Current version assign strong tag and cm-strong element with a specific color (color: ${theme.colorBright};) which entangle the renderers' behaviors.
- For the Markdown-it side it makes `**==Emphasis Text==**` and `==**Emphasis Text**==` rendered differently.
- For the CodeMirror side: it makes customization more [convoluted](https://discourse.joplinapp.org/t/plugin-markdown-table-colorize/21195/27) because cm-strong does not inherit it's parent style.
Unless there is a specific reason that i don't know of, when it comes to css it is better to achieve the same effect with as less code as possible so we should trust that cm-strong will inherit the correct color from it's parent.
I didn't found the same issue with italic.
> Desktop: Remove cm-strong css color specification

- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useEditorSearch.ts
- packages/app-desktop/gui/NoteEditor/utils/useNoteSearchBar.ts
This PR fixes issue #5850.
Implemented features:
- When a local search is executed, the current highlighted search result is selected (with a cursor move).
- After the local search bar is closed, Markdown Editor is focused.
> Desktop: Fix #5850: Focuses an editor after local search is closed

- readme/spec/e2ee.md
Noticed that the path to EncryptionService references a js file rather than a ts file in a location that no longer exists.
At the same time updated the permalink for the strong encryption link from the older "wrong" location js file to the current location ts file.
> Docs: Update e2ee spec paths and links

- Joplin_install_and_update.sh
Since this commit (https://github.com/KDE/plasma-workspace/commit/ebd2acd98ecdb9d115b01bd01f532390376152f7),
Plasma Desktop will check "X-GNOME-SingleWindow" property to determine
whether to show "Open New Window" action in the context menu of a task.
Joplin cannot launch a new instance or open a new window, so add the
property and set it to true to hide the action.
> Desktop: Add "X-GNOME-SingleWindow=true" to the desktop file

- README.md
Attempting to synchronise without `GetObject` partially succeeds: it pushes changes into S3 but fails at the next step when it tries to fetch.
> Documentation: Default S3 permissions require 'GetObject'

- packages/app-desktop/app.ts
Fix issue from forums (https://discourse.joplinapp.org/t/built-app-doesnt-start/22884/) where the built app was failing:
```
Uncaught Error: Cannot find module '../lib/eventManager'
Require stack:
- /tmp/.mount_JoplinD3eYGv/resources/app.asar/app.js
- /tmp/.mount_JoplinD3eYGv/resources/app.asar/index.html
at Module._resolveFilename (internal/modules/cjs/loader.js:892)
at Function.o._resolveFilename (electron/js2c/renderer_init.js:29)
at Module._load (internal/modules/cjs/loader.js:737)
at Function.f._load (electron/js2c/asar_bundle.js:5)
at Function.o._load (electron/js2c/renderer_init.js:29)
at Module.require (internal/modules/cjs/loader.js:964)
at require (internal/modules/cjs/helpers.js:88)
at Object.<anonymous> (app.ts:65)
at Object.<anonymous> (app.ts:601)
at Module._compile …
```
> Desktop: fix built application - eventManager path

- README.md
Nowadays AWS does not support policy type IDENTITY_POLICY anymore, so policy provided in `README.md` can't be created as-is.
So I'm proposing this change to make everyone's life easier :)
> Remove unsupported AWS IAM policy statement

- packages/app-desktop/gui/SearchBar/SearchBar.tsx
The search icon in the Desktop app is overflowing from the SearchBox as mentioned in #5916.
So, I added min-width to 30px, so the input box can't get smaller then 30px.
https://user-images.githubusercontent.com/71817691/148622196-7f7a477e-d2cd-4953-9c88-7c7df16108d9.mp4
> Desktop: Resolves #5916: Fix Search Icon OverFlow

- packages/generator-joplin/generators/app/templates/package_TEMPLATE.json
Using this field in package.json restricts `npm pack` and `npm publish` to only
include the publish directory and LICENSE, README.md and not the rest of
the extraneous files, which I believe is the desired (desire-able) behavior. 
Example of `npm pack` output on my plugin before this is patch is present:
```
❯ npm pack                                                                                                                          22:46:38
npm notice
npm notice 📦  joplin-plugin-auto-alarm@1.0.7-rc5
npm notice === Tarball Contents ===
npm notice 2.1kB   .config/joplin-plugin-helpers/.github/workflows/ci.yml
npm notice 1.3kB   .config/joplin-plugin-helpers/.pre-commit-config.yaml
npm notice 308B    .config/joplin-plugin-helpers/bin/symlink-helpers
npm notice 821B …
```
> Use "files" key in plugin package.json template to restrict npm pack to only include publish folder

- packages/app-desktop/app.ts
- packages/lib/models/Setting.ts
Currently the wording in settings has been leading people to believe that the applications will be automatically updated.
In reality all that is done is checking for available updates.
Thus the new wording is: `Automatically check for updates`
~~For some reason this check was disabled on Linux, because during experiments with real auto-updates yielded negative results on Linux.
But since the current code only checks for updates, there is no reason to not allow this on Linux.~~
~~Laurent, as to the impact this change has on Linux (since I promised I will let you know): it allows people to enable the auto-check on Linux.~~
I have tested the change on macOS and Linux. According to the code there is no change that is Windows specific, so I am sure it has no impact on Windows.
> Desktop: fix wording in settings

- packages/lib/SyncTargetAmazonS3.js
- packages/lib/commands/synchronize.ts
- packages/lib/components/shared/side-menu-shared.js
Shows an error message when syncing if the S3 region is not set
Also shows a message if you try to check sync config in settings:
I also turn a few error log from `info` to `error`.
This should fix #5875
> Desktop: Fixes #5875: Show error on sync if S3 region is not set

- packages/lib/onedrive-api.ts
When a user selects onedrive as sync target, onedrive currently tries to automatically sign in the user. The problem however is that the autologin procedure from onedrive is weird - it seems when a user is signed in to a personal and a business account, onedrive always picks the business account. But even if this were not the case, a user might still want to choose a different account than used in a previous browser session (on a work pc you might be logged in to your business account in the browser, but you might still want to use your personal account for joplin). This has been reported a couple of times on the forum: 
https://discourse.joplinapp.org/t/how-can-i-choose-which-onedrive-account-to-auth-on-win10/9016/6
https://discourse.joplinapp.org/t/option-to-re-authenticate-with-onedrive …
> All: Don't automatically sign it to onedrive

- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useScrollHandler.ts
This PR fixes #5918. That is, it suppresses unexpected scroll jumps when images are rendered in Markdown Editor. The symptom may happen if CodeMirror.refresh() is called while Markdown Editor is scrolling.
This PR mitigates the symptom of Rich Markdown 0.8.1 or before. The details are described in #5918.
Implementation Notes:
- The scroll position variable used for restoring when resized is updated more frequently.
- Resizing CodeMirror's `refresh` event are distinguished from refreshing `refresh` events as possible.
> Desktop: Fix #5918: Scroll jumps when images are rendered in Markdown Editor

- packages/app-desktop/gui/TagItem.jsx
- packages/app-desktop/gui/TagList.tsx
- packages/lib/theme.ts
Tags in Tag Bar at the bottom of Note Editor become clickable. The behavior is the same with clicking a tag in Sidebar.
This feature is requested here:
- [Clicking on Tags like on Notebooks - Features - Joplin Forum](https://discourse.joplinapp.org/t/clicking-on-tags-like-on-notebooks/11670)
- [Suggestion - Tag label - Click to display notes sharing that tag - Features - Joplin Forum](https://discourse.joplinapp.org/t/suggestion-tag-label-click-to-display-notes-sharing-that-tag/7880)
> Desktop: Clickable tags in Tag Bar

- packages/lib/services/plugins/api/JoplinCommands.ts
Fixes #5975
The links were broken, looks like one changed the file location of `editorCommandDeclarations.ts` and forgot to update the js-docs.
No worries, I god this 💪 😃
> Docs: fixes #5975: update editorCommandDeclarations link

- Joplin_install_and_update.sh
X-GNOME-SingleWindow was upstreamed to be an XDG spec with the name
"SingleMainWindow" in
https://gitlab.freedesktop.org/xdg/xdg-specs/-/merge_requests/53.
This prevents Desktop Environments such as KDE and Gnome
to not display the menu item to open in a new window in apps that
don't support that.
> Desktop: Linux: Prevent Desktop Environments to launch a new window

- packages/app-desktop/gui/PromptDialog.jsx
When the Add Tag Prompt is open, some white space are left at the bottom due to ```height: height - paddingTop,```.
which  is used in root and cause the hight to become smaller than the original.
After Removing:
> Desktop: Fix White space in the bottom of Add Tag Prompt

- readme/markdown.md
A new user on his first day might lose 3 hours trying to enable, say, the Fountain plugin, after seeing it's actually *not* in the plugins list. What is called "plugins" here, are actually *markdown plugins*, completely different from the main type of plugins. To enable a markdown plugin, user should not search for it in the "plugins" section of the options, but go to the "markdown" section of the options, and just tick the right box.
> Clarify where to go to enable markdown plugins

- packages/app-desktop/gui/SearchBar/SearchBar.tsx
Resolves [#5953](https://github.com/laurent22/joplin/issues/5953)
> [Reported by atomlib on discord](https://discord.com/channels/610762468960239627/610762468960239629/927461889053712384):
> 
> > Typically when I place cursor inside the Search… field to type something, these buttons on the right disappear to make space for the input. After I remove input focus from the Search… field, they reappear again.
> 
> > However, if I go to View → Change application layout while I had input focus in the Search… field, the buttons do not reappear on focus being lost. They will appear only if I place the cursor inside the field and remove the focus from the input field.
I found out that the searchBar gets remounted every time pages like layoutEditor or settings are loaded.
I have added necessary hook …
> Desktop: Fix issue #5953: search bar focus

- packages/app-desktop/services/sortOrder/PerFolderSortOrderService.ts
This fixes the bug #5968; When a notebook with its own sort order is selected and the app exits, the default (shared) sort order is lost at the next startup of the app.
The cause of the bug is that the initial notebook is not tracked. So, at the first time that notebook is switched, the cleanup of the last notebook is not performed.
> Desktop: Fix #5968: Default sort order lost on exit

- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx
- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/Editor.tsx
- packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useScrollHandler.ts
- packages/app-desktop/gui/note-viewer/index.html
This PR  fixes the regression bug #5981 happens in v2.6.10.
To preserve Editor's scroll positions when the editor layout changes, the following are implemented:
- When heights of lines in CodeMirror are changed, Editor's scroll positions are restored.
- Uncertain scroll positions are ignored in Editor.
- When Viewer is resized, its scroll position is sent to Editor. (The reverse is not necessary.)
The details are described in #5981.
> Desktop: Fix #5981: Scroll positions are not preserved when layout changes in v2.6.10

- packages/app-cli/tests/md_to_html/image_with_alt_title.html
- packages/app-cli/tests/md_to_html/image_with_alt_title.md
- packages/renderer/MdToHtml/rules/image.ts
- Desktop: Fixes #5803 : Added alt text in images' html
Fixes #5803 : After adding images in Joplin the HTML was not showing alt text. 
For testing I added an image with alt text as nature-image.jpg.
> Desktop: Fixes alt text not appearing in html

- packages/app-desktop/gui/note-viewer/index.html
This PR fixes #6042: Scroll position is not remembered when a note is switched.
The detail is described there.
> Desktop: [Regression] Fix #6042: Scroll position is not remembered.

- Dockerfile.server
Through the use of multi-stage builds[1], the (uncompressed) size of the final image is reduced from 2.42GB to 1.23GB.
Additionally, the current base image that is used for running Joplin Server is swapped out for the slim version of the official NodeJS image. The init tool Tini[2] is used to work around NodeJS' PID 1 issue[3].
Fixes #5397.
@tessus @laurent22 FYI, I accidentally ended up closing #5939 when I tried to resolve its merge conflicts.
[1] https://docs.docker.com/develop/develop-images/multistage-build/
[2] https://github.com/krallin/tini#why-tini
[3] https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#handling-kernel-signals
> Server: Use multi-stage builds and smaller base image

- BUILD.md
Updated command and pre-requisite for installing Windows Build Tools.
`windows-build-tools` is now deprecated since Node 16: ["Please note that the official Node.js for Windows installer can now automatically install the required tools."](https://github.com/felixrieseberg/windows-build-tools#readme)
> Desktop: Fixes #5947: Incorrect build instruction in documentation

- readme/rich_text_editor.md
Based on fairly frequently asked questions and topics (linked) - proposing addition of a section saying that Markdown does not support lists within tables even though the rich text editor allows them to be created.
https://github.com/laurent22/joplin/issues/6071
https://github.com/laurent22/joplin/issues/6056
https://github.com/laurent22/joplin/issues/5575
https://discourse.joplinapp.org/t/feature-request-checkboxes-inside-a-table/23289
https://discourse.joplinapp.org/t/lists-within-a-table-list-shortcut/21859
> Docs: Add rich text editor limitation - lists within tables

- packages/lib/models/Setting.ts
- packages/lib/models/dateTimeFormats.test.ts
I would like to add an additional time format in the settings. This format is the format also used by Dropbox when I scan documents so I can have one date formatting for all my documents.
> All: Add Additional Time Format

- packages/app-desktop/gui/MenuBar.tsx
fixes #6108 
We already have `Import` as a menu item. We also don't say in the sub menu: `Import JEX`, `Import MD`, etc.
So we should use the following instead: `From other applications...` or `Other applications...` (because `from` is implied by the word `import` (as is `to` by `export`)).
But I can change the menu item name, if necessary.
`Importing from ....` is only necessary if we put this item under help. It makes less sense when having a submenuitem under `Import >`.
> Desktop: Fixes #6108: add additional export menu item

- packages/app-mobile/components/screens/Note.tsx
Fix for https://github.com/laurent22/joplin/issues/5482
Removes code related to `enableMultilineTitle` and `titleTextInput_contentSizeChange` as no longer required if titles can no longer have changeable heights.
Checked with Android simulator in both regular and beta editors - can no longer create carriage returns/new lines in title lines. Don't currently have ability to compile for iOS but this was previously not enabled for iOS anyway so not expecting any behaviour changes.
> Mobile: Fixes #5482: Removes title multiline and contentsize related code to prevent multiline titles

- readme/gsoc2022/ideas.md
Add settings sync idea to GSoC ideas - discussed previously:
> The plugin ecosystem at this point is starting to become fairly essential to the way that people use Joplin so having to mirror settings over 2 or more devices can start to become a chore - particularly things like notebook sorting orders let alone the myriad of plugin settings.
> So basically an option to sync the settings (and the client info with it would be a bonus) rather than having to keep doing the same setup multiple times.
> Docs: GSoC 2022 - Add settings sync idea

- README.md
Docs update to remove "unsupported methods" and replace it with a link to the community supported wiki page.
See:
https://discourse.joplinapp.org/t/unofficial-alternative-joplin-distributions/23703
https://discourse.joplinapp.org/t/alternative-distributions-wiki-list/23677/
Moved below the WebClipper section as this list could well include the webclipper if it was to be forked so should be at the bottom of the list.
> Docs: Removed unsupported methods + added link to community wiki page

- readme/gsoc2022/ideas.md
- readme/gsoc2022/index.md
- readme/gsoc2022/pull_request_guidelines.md
2022 GSoC is [open to anybody](https://opensource.googleblog.com/2021/11/expanding-google-summer-of-code-in-2022.html), not just students so most references to "student" have been replaced with "contributor" as per the [GSoC glossary](https://developers.google.com/open-source/gsoc/resources/glossary#gsoc_contributor).
> #### GSoC Contributor
> A GSoC Contributor is a person accepted into the Google Summer of Code program who will spend their summer coding on a project under the guidance of mentors from an open soure(sic) organization.
(Yes "open soure" is in the official documentation, wonder if GSoC accepts PRs).
Also fixed one or two formatting/grammar issues.
> Docs: Updated GSoC to replace student refs with contributor

- readme/welcome/5_privacy.md
The Privacy note included in the "Welcome!" notebook was similar to but not identical to the website one. I've simply replaced the Markdown entirely with the (newer) note from the website.
Alternatively the two should be kept in sync automatically from the master website readme doc.
> All: Replaced "Welcome! 5. Privacy" md with website privacy md

- packages/app-mobile/components/screens/NoteTagsDialog.js
This PR adds a tag filter (the "Filter tags" input box in the screen recording below) for mobile app's note tag dialog. It helps the user search for a particular tag in the tags list. 
https://user-images.githubusercontent.com/3250983/156068396-e6b74860-78ec-4411-9f92-42f785899c43.mp4
> Mobile: add tags filter to note tags dialog

- packages/app-clipper/popup/src/App.js
- packages/app-clipper/popup/src/bridge.js
This PR adds a button after you click "Confirm" in the clipper. This button allow you to open the newly created note in Joplin using the `joplin://` link. This streamlines the clipping process because the user no longer need to switch to the Joplin Desktop app and search for the new note.
> Clipper: add an open newly created note button

- packages/app-desktop/gui/MainScreen/commands/setTags.ts
- packages/app-desktop/gui/TagList.tsx
- packages/lib/components/shared/side-menu-shared.js
- packages/lib/models/Tag.test.js
- packages/lib/models/Tag.ts
This fixes the bug #5686; The tag order between left panel and windows tag is different.
Whenever tags starting with emoji, #, @ were added then the order for tags in the promptDialog dropdown menu and sidebar TAGS section were different.
The cause of the bug was that different sorting logic was used in the sidebar tags section and setTags.ts (the sort method in this file is used to sort tags in the promptDialog dropdown menu).
To fix this I did the following, removed the old sort method in setTags.ts and added the sort method which was used in the side-menu-shared.js (this sort method is used to sort tags in the sidebar). As the sort methods are same the outputs are also the same. I have also added the unit test.
> Desktop: Fixes #5686: Fixed Tags Order

- readme/gsoc2022/index.md
- readme/gsoc2022/pull_request_guidelines.md
This years themes are in the index as well as the ideas page so I've copied the themes from ideas to index to keep them consistent.
Also corrected a small typo in the guidelines.
> Docs: Update themes in GSoC index.md and a typo correction

- readme/gsoc2022/ideas.md
changed  [general Summer of Code introduction](https://joplinapp.org/gsoc2022/index/) to [general Summer of Code introduction](https://joplinapp.org/gsoc2022/)
> fixed link to general Summer of Code introduction

- packages/app-mobile/components/SelectDateTimeDialog.tsx
I have changed the `renderContent` method in file `components/SelectDateTimeDialog.tsx`. Date-time text now receives the color prop from global theme to handle changes in color as per the app theme.
Fixes #6234 
- Code
- Quality Assurance
- User Interface
**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
> Color of date-time text in "Set Alarm" changed to match theme

- .eslintignore
- .gitignore
- packages/lib/services/searchengine/SearchFilter.test.js
- packages/lib/services/searchengine/SearchFilter.test.ts
- packages/lib/services/searchengine/filterParser.ts
Fixes #6266 that only lowercase keywords work in the search filters. 
I wanted also convert the `SearchFilter.test.js ` to TypeScript, but unfortunately I can't manage the following line.
`Parameter 'a' implicitly has an 'any' type.ts(7006)` [const ids = (array) => array.map(a => a.id); ](https://github.com/JackGruber/joplin/blob/2ecdc3596a4f74114a946b720b22cdc2c2aac7ca/packages/lib/services/searchengine/SearchFilter.test.js#L15)
> All: Resolves #6266: Filter keywords casesensetive

- packages/app-desktop/package.json
Disallow changing the installation directory during updates (still allowed on fresh installs). This setting removes existing shortcuts, and unpins Joplin from Start, taskbar, and other surfaces in Windows.
Here’s the relevant code from electron-builder:
https://github.com/electron-userland/electron-builder/blob/2dda5fcb45d99a0a991d195a2f577e3dbca775eb/packages/electron-builder-lib/templates/nsis/include/installer.nsh#L252-L257
Resolves 4155.
> Desktop: Resolves 4155: Don’t unpin from taskbar on update
