laurent22/joplin

CliClient/locales/es_419.po
=> adding translate spanish Latin America

CliClient/locales/de_DE.po
This is a WIP to add German localisation to Joplin. It's currently like ~35% done, however, I don't know electron apps too well, so I'll count on someone else to actually do the necessary changes to integrate it into Joplin ( which is required before this is merged, so that we can proofread  it in the actual application ).
=> WIP: Add German (Germany) locale

CliClient/locales/ru_RU.po
Russian localisation for Joplin. 100% done, but some corrections may be required.
=> Russian localisation

CliClient/app/app-gui.js, CliClient/app/autocompletion.js, CliClient/app/gui/StatusBarWidget.js
Inteligent command based autocompletion (i.e. autocompleting notes for `rmnote`)  is not yet implemented. This will require knowledge of the command, and it's parameters. The autocomplete feature is pretty powerful however, so this should not be very difficult to add. But I think this is still better than nothing!
=> Added auto complete

CliClient/locales/ja_JP.po
Added: Japanese language file
追加：日本語の言語ファイル
=> Japanese localization

ReactNativeClient/lib/components/screens/note.js
Hi, 
I have fixed the issue that not permit the user to view edited text when keyboard is opened.
I try both on IOS and Android.
Tell me if it's right
Thanks
=> Fix scroll note keyboard on IOS

CliClient/locales/nl_BE.po
All EN keys are translated to nl_BE.
=> Dutch translation

ElectronClient/app/gui/ConfigScreen.jsx, ElectronClient/app/theme.js, ReactNativeClient/lib/models/Setting.js
Adds a setting to easily adjust the font size in the desktop app. Fixed code from https://github.com/laurent22/joplin/pull/126.
=> Add font size settings

CliClient/app/autocompletion.js
Implement features mentioned #81.
Here is demo
Autocompletion for files only suggest files in the current directory.
=> Autocompletion for files and items

CliClient/locales/de_DE.po
Grammar and wording fixes, translating new strings.
=> Update German translation

CliClient/locales/es_ES.po, README.md
=> Fixed and updated Spanish translation

CliClient/locales/es_ES.po
=> Improved Spanish translations

README.md
just a quick fix for the docs 🙂
=> correct the documentation about adding checkboxes

BUILD.md
Adds build instructions for machine running Windows.
=> Add build instructions for Windows

CliClient/locales/es_ES.po
=> Updated Spanish translation

CliClient/locales/de_DE.po
I've completed the german translation. Maybe it needs a few minor changes in the future, but first of all it is completed right now.
=> Updated german translation de_DE

CliClient/locales/cs_CZ.po
Adding Czech language translation.
Thanks for Joplin!
=> adding Czech translation

ReactNativeClient/lib/models/Setting.js
Common EU Date format DD.MM.YYYY added, issue #405
=> Common EU Date format DD.MM.YYYY added, issue #405

ReactNativeClient/lib/MdToHtml.js
Checkboxes can now be checked with X and x.
=> Fix for Issue #430

CliClient/locales/es_ES.po
=> Spanish translation updated

CliClient/app/autocompletion.js, CliClient/app/command-help.js, CliClient/locales/cs_CZ.po, CliClient/locales/da_DK.po, CliClient/locales/de_DE.po, CliClient/locales/en_GB.po, CliClient/locales/es_ES.po, CliClient/locales/eu.po, CliClient/locales/fr_FR.po, CliClient/locales/gl_ES.po, CliClient/locales/hr_HR.po, CliClient/locales/it_IT.po, CliClient/locales/ja_JP.po, CliClient/locales/joplin.pot, CliClient/locales/nl_BE.po, CliClient/locales/pt_BR.po, CliClient/locales/ru_RU.po, CliClient/locales/zh_CN.po, README.md, ReactNativeClient/lib/file-api-driver-webdav.js, ReactNativeClient/lib/layout-utils.js, ReactNativeClient/lib/synchronizer.js, docs/index.html, docs/terminal/index.html, readme/terminal.md
All of them were found by codespell.
=> Fix some typos

CliClient/locales/ca.po
=> Add Catalan Translation

CliClient/locales/nl_NL.po
=> Added Dutch (Netherlands) translation

README.md
=> Add fastmail WebDAV synchronisation list

README.md
Add script to install on Ubuntu or Debian with Gnome Shell Icon
=> Script to install on Ubuntu with Gnome Shell

ReactNativeClient/lib/folders-screen-utils.js
Just simply added options to retreive list of folders alphabetically rather than without ordering.
Related issue: #206
=> Notebooks list is sorted alphabetically as default

CliClient/locales/ro.po
My first pull request ever :)  . Love your app and thought of starting to translate it in Romanian too.
=> Romanian translation added

install_ubuntu.sh
Comments, presentation title, final informative text have been added and temporary variable is deleted.
=> Added comments and information texts

CliClient/locales/ja_JP.po
I've finished to translate into Japanese.
=> Update Japanese Translations.

CliClient/locales/de_DE.po
Fixed some typos and inconsistencies in the german language file and added missing translations.
=> German language file

ReactNativeClient/lib/models/Resource.js
=> add support for webp images

ReactNativeClient/lib/components/screens/note.js
=> Mobile: Fixes #856: Add option to open source url

ReactNativeClient/lib/shim.js
=> Support FreeBSD in terminal

ReactNativeClient/android/app/build.gradle, ReactNativeClient/android/app/src/main/java/net/cozic/joplin/MainApplication.java, ReactNativeClient/android/settings.gradle, ReactNativeClient/ios/Joplin.xcodeproj/project.pbxproj, ReactNativeClient/lib/components/screens/config.js, ReactNativeClient/package-lock.json, ReactNativeClient/package.json
This change adds the application version to the `Configuration` screen.
/ref #233
=> mobile: add version info

CliClient/locales/de_DE.po
=> fixed typo in Aktualsierungsdatum to Aktualisierungsdatum

CliClient/locales/zh_CN.po
=> Add more Chinese translation

ElectronClient/app/gui/NotePropertiesDialog.jsx
I recently learned that there was an information popup, and unfortunately it didn't have the theme.
Fixes #990
=> Add dark theme to note properties dialog

Joplin_install_and_update.sh
=> Fix name in Linux Desktop

README.md
I've added Apache's WebDAV module to the list of WebDAV-compatible services.
=> add Apache WebDAV Module to WebDAV-compatible services

CliClient/locales/nb_NO.po
Complete the three new entries + change my e-mail
=> Update Norwegian translation

CliClient/locales/zh_CN.po
=> Update zh_CN translations

CliClient/locales/ru_RU.po
=> Update ru_RU translation

ReactNativeClient/lib/MdToHtml.js
=> fix markdown code for checked checkbox

docs/PULL_REQUEST_TEMPLATE
If someone does not delete the 'Attention' line, it will show up in the pull request.
Comments and information should be enclosed in comment markers.
=> fix PR template

CliClient/locales/nb_NO.po
Complete missing translations and minor corrections
=> All: Update norwegian translations

CliClient/locales/ko.po
Filled empty messages and corrected fuzzy translations.
=> All: Update Korean translations

CliClient/locales/ru_RU.po
=> Fixed and updated translation to Russian language

ElectronClient/app/theme.js, ReactNativeClient/lib/MdToHtml.js
This updates tables and blockquotes to have a bit more style. I guess that a designer could come up with something better, but I feel these are an improvement on the current styles.
=> Add new styling to tables and blockquote

ElectronClient/app/theme.js
Some people on the forum had complained about the sidebar colour in the dark theme. This updates it to remove the blue and make it a slightly darker grey.
=> Desktop: Minor update to dark theme

Clipper/joplin-webclipper/content_scripts/index.js, Clipper/joplin-webclipper/popup/src/App.js
Clipper: The clipper offers now the base functionality to store a URL without any additional content
The note includes:
Title: Title of webpage
Content: URL of the webpage
=> Clipper: Feature added for storing urls

CliClient/locales/tr_TR.po
Improved Language, some wrong words corrected. added new " #, fuzzy " lines again with correct translation.
=> Turkish Language Improving

Joplin_install_and_update.sh
=> Desktop:  Linux Installer less verbose and visually more informative

CliClient/locales/zh_CN.po
I found there're some unclear translations and fixed them.
=> [Mobile] Fix unclear Chinese translation.

ElectronClient/app/app.js, ElectronClient/app/gui/SideBar.jsx
see https://github.com/laurent22/joplin/issues/1151#issuecomment-463845158
=> add shortcut to start a sync

ElectronClient/app/gui/MainScreen.jsx, ElectronClient/app/gui/NoteText.jsx
change the notebook icon consistently
see https://github.com/laurent22/joplin/commit/f6f0bcf1c3a351e5dcaf76e7edba4b61fba3c06a
=> change notebook icon in toolbar and search result

README.md
"한국말" -> "한국어"
Korean translation error update.
=> 한국말 -> 한국어

CONTRIBUTING.md
=> fix spelling mistake

Joplin_install_and_update.sh
- Added check for VERSION file to remove error message during fresh install
- Turned on wget progress bar so script shows progress during lengthy download
- Improved grammar and information in status messages
=> Desktop: Adding progress bar and text changes to install script.

CliClient/locales/ja_JP.po
=> Desktop: update jp translation

CliClient/locales/zh_CN.po
=> update zh-CN translation

CliClient/locales/pt_BR.po
=> CLI: Update pt_BR.po

Joplin_install_and_update.sh
fixes #1255 
fixes #338 by adding StartupWMClass to the default joplin.desktop file (note that the integration prompt also does this as of some time ago)
partially fixes #403 , When systems install the default joplin.desktop file they won't be prompted by appimagekit
This pull request does a couple of small things. First it adds X-AppImage-BuildId to the default joplin.desktop file, this prevents the system integration prompt if the file already exists.
Second it renames the default joplin.desktop file to appimagekit-joplin.desktop, this is also needed to prevent the prompt, and provides integration with appimage tools.
And lastly at the beginning of the script we delete any existing joplin.desktop files or appimagekit-joplin.desktop files, this prevents duplicate entries in menus.
=> Prevent appimage integration prompt when joplin.desktop already exists

CliClient/locales/en_US.po
I've currently only added the differences, since it will use the default (which is English) otherwise anyway.
So the statistics for this language will be wrong. However, I don't think that it makes sense to copy all entries. But I can do it, if you want. Just let me know.
=> add localization for English (United States) en_US

ElectronClient/app/app.js, ElectronClient/app/plugins/GotoAnything.jsx
```
Print            Command/Control + P
Goto Anything    Command/Control + G
```
closes #1413
=> change shortcuts for 'Print' and 'Goto Anything'

CliClient/locales/de_DE.po
=> update localization de_DE.po

README.md
=> Readme: Change Download links from 1.0.142 to 1.0.143

ElectronClient/app/gui/Header.jsx, ElectronClient/app/gui/SideBar.jsx, ElectronClient/app/style.css, ElectronClient/app/theme.js
- Added animation to icon in synchronize button
- Moved sync report above button, which prevents the sync button from moving from its place when the report has text.
- Added animation to icon in Toggle Sidebar button, using the css transition property.
- Reduced font size for text and icons in header and sidebar
- Changed theme color2 from white to a very light grey. It is barely noticeable, but reduces contrast a bit, improving readability.
=> Desktop: UI updates to sidebar and header, changing icon sizes and animations

CliClient/locales/cs_CZ.po
I've made an update to the czech translation .po file.
=> CLI: CZech translation updated

CliClient/locales/ar.po, CliClient/locales/ca.po, CliClient/locales/cs_CZ.po, CliClient/locales/da_DK.po, CliClient/locales/de_DE.po, CliClient/locales/en_GB.po, CliClient/locales/en_US.po, CliClient/locales/es_ES.po, CliClient/locales/eu.po, CliClient/locales/fr_FR.po, CliClient/locales/gl_ES.po, CliClient/locales/hr_HR.po, CliClient/locales/it_IT.po, CliClient/locales/ja_JP.po, CliClient/locales/joplin.pot, CliClient/locales/ko.po, CliClient/locales/nb_NO.po, CliClient/locales/nl_BE.po, CliClient/locales/nl_NL.po, CliClient/locales/pt_BR.po, CliClient/locales/ro.po, CliClient/locales/ru_RU.po, CliClient/locales/sl_SI.po, CliClient/locales/sv.po, CliClient/locales/tr_TR.po, CliClient/locales/zh_CN.po, CliClient/locales/zh_TW.po
=> add /%d to Fetching resources: %d

README.md, Tools/build-website.js
https://discourse.joplin.cozic.net/ -> https://discourse.joplinapp.org/
=> use new forum link

CliClient/locales/fa.po
=> Improved and fixed Persian (fa) translation

CliClient/locales/it_IT.po
=> Translation: update it_IT.po

ElectronClient/app/package-lock.json, ElectronClient/app/package.json, ReactNativeClient/package-lock.json, ReactNativeClient/package.json
=> Desktop/Mobile: Bump markdown-toc plugin version to 4.0.0

CliClient/locales/pl_PL.po
Addition of strings and correction of mistakes.
=> [Update] Language file: pl_PL.po

ElectronClient/app/app.js
=> add shortuct for tags (`Cmd+Opt+T` / `Ctrl+Alt+T`)

CliClient/locales/bg_BG.po
Here is a localization for Bulgarian that I made.
=> Localization: add bulgarian

CliClient/locales/it_IT.po
=> Update Italian translation

CliClient/locales/ko.po
Korean Language 100% Translated, but something is roughted. soon fix it ;)
also, 한국어 is right, 한국말 is 'korean language language' so need fix it
=> Trans: Korean Language Support

CONTRIBUTING.md
Clarify docs to reflect answer in https://github.com/laurent22/joplin/issues/71
=> CLI: Add docs to clarify how to test

CliClient/locales/pt_BR.po
=> Translation: Translation Update pt_BR

README.md
adding a new community entry point for the users looking for live chat ;)
=> Discord Community Server

CliClient/app/app-gui.js, CliClient/package.json
- updated terminal-kit to 1.30.0
- do not call method, if object does not exist
fixes #1778
=> CLI: fixes potential fatal error on start

Tools/build-translation.js
=> Infrastructure: build-translation.js - add support for macOS 

ReactNativeClient/lib/TemplateUtils.js
=> Desktop: Use correct date format for templates

CliClient/locales/zh_CN.po
Cli: Update zh_CN.po Chinese translation
=> Update zh_CN.po Chinese translation

CliClient/locales/ko.po
Fix & added to several korean language
=> Translation - Korean Language Support

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, .github/stale.yml
=> drop emoji in tag name

Joplin_install_and_update.sh
Hello,
I just push on a little modification to the Joplin Linux install script to implement desktop icon on Deepin.
Thanks
=> Desktop: Add support for Deepin desktop environment

CliClient/locales/ja_JP.po
* Translate new strings.
* Check and update 'fuzzy' strings.
=> Update ja_JP.po Japanese translation

BUILD.md
I've modified the `BUILD.md` instructions to reflect minor React Native documentation change from:
to:
=> Update React Native build documentation

CliClient/locales/es_ES.po
I added some translations and change a couple more in order to improve there meaning in Spanish.
I am a native spanish speaker so I could help with some more translate if you want.
=> CLI: Added some translations to es_ES.po

CliClient/locales/nb_NO.po
Updated the existing nb_NO translation to be 100% complete.
Happy #hacktober2019 :)
=> Translation: update nb_NO

ReactNativeClient/lib/models/Setting.js
follow up to #1924 
The Dracula theme should not be shown on mobile.
=> Mobile: no Dracula on mobile

ReactNativeClient/lib/components/screen-header.js, ReactNativeClient/lib/models/Note.js
**Related issue:**
- https://github.com/laurent22/joplin/issues/545
=> Mobile: Adding duplicate option when selecting notes.

ElectronClient/app/checkForUpdates.js
The changelog text is truncated if it's longer than 1000 characters,
but avoids cutting off a partial line, unless that would lead to cutting
off too much of the text. An ellipsis is added to mark the truncation.
Additionally, when the changelong is truncated, it adds a "Full Release Notes"
button that opens the GitHub release page in a browser window.
=> Desktop: Truncate update changelog when it's too long (#1222)

ElectronClient/app/gui/NoteText.jsx, ReactNativeClient/lib/models/Setting.js
adds a setting to specify the page size for exporting notes to PDF
=> add setting: export.pdfPageSize

CliClient/locales/el_GR.po
Hey, this is the Greek Translation of the Joplin app.
I suppose minor changes could occur due to gender translations.
=> Translation Greek (el_GR)

ElectronClient/app/app.js, ElectronClient/app/gui/MainScreen.jsx, ElectronClient/app/gui/SideBar.jsx
closes #1978 (create sub-notebook by right-clicking on notebook)
=> Desktop: add context menu and menu item to create sub-notebook

CliClient/locales/cs_CZ.po
Update for existing Czech translation:
- Translate new strings.
- Improve existing strings.
=> Update Czech translation

CliClient/locales/da_DK.po
Translation is at 99%
In the case that i was unsure of the translation or the wording was bad i have marked the strings as needing work.
=> Extended the danish translation

.github/PULL_REQUEST_TEMPLATE, CliClient/app/app.js, CliClient/app/autocompletion.js, CliClient/app/command-sync.js, CliClient/app/onedrive-api-node-utils.js, CliClient/tests/html_to_md/table_no_header.html, CliClient/tests/html_to_md/table_no_header.md, CliClient/tests/markdownUtils.js, CliClient/tests/test-utils.js, CliClient/tests/urlUtils.js, ElectronClient/app/ElectronAppWrapper.js, Tools/buildReactNativeInjectedJs.js, docs/spec/index.html, docs/terminal/index.html, readme/spec.md, readme/terminal.md
=> Misc. documentation and source comment typos + whitespace fixes 

CliClient/app/autocompletion.js, CliClient/app/command-tag.js
=> CLI: Add command to list all tags for a note

ElectronClient/app/gui/NoteText.jsx, ElectronClient/app/gui/style/theme/nord.js, ElectronClient/app/theme.js, ReactNativeClient/lib/models/Setting.js
code by vzsky (PR was abandoned)
closes #1903
---
The last OP did move the theme to its own file. I would like to do that for the other themes as well.
=> Desktop: add Nord theme

CliClient/locales/eo.po
=> Esperanto language 51% completed

CliClient/locales/pt_BR.po
=> Translation: pt_BR.po

ReactNativeClient/lib/WebDavApi.js
closes #2042
next attempt.... ;-)
=> All: set user-agent header to Joplin/1.0

CliClient/locales/cs_CZ.po
=> Updated Czech translation

CliClient/locales/sv.po
Added missing translations
Made adjustments to previous translations.
=> Updated translation

CliClient/locales/ru_RU.po
Filled untranslated string and correct some sentencies.
=> Russian translation update

readme/gsoc2020/ideas.md
Just fixing a few typos in the GSoC thing.
=> Fixng a couple typos

CliClient/locales/pt_PT.po
=> Portuguese translation

ElectronClient/app/package-lock.json, ElectronClient/app/package.json, ReactNativeClient/package-lock.json, ReactNativeClient/package.json
see https://discourse.joplinapp.org/t/katex-text-textasciicircum-does-not-work/4750?u=tessus
=> Desktop, Mobile: update Katex to 0.11.1

CliClient/locales/zh_TW.po
I already update Traditional Chinese (Taiwan) translate.
=> Traditional Chinese translate

CliClient/locales/ko.po
=> translate_korean

readme/gsoc2020/index.md
The folder is `gsoc2020`, not just `gsoc`
=> Fix broken link

CONTRIBUTING.md, CliClient/package-lock.json, CliClient/package.json
Updates SQLite and adds a bit more info for running the tests to the docs.
=> CLI: Upgrade sqlite

CliClient/locales/tr_TR.po
=> Translation: completed Turkish translation and fixed minor errors

ElectronClient/app/package-lock.json, ElectronClient/app/package.json
This is only a minor bump but several issues have been fixed since 7.1.5.
The most pressing one that we've experienced for a long time:
default button in dialog not working on macOS
https://github.com/electron/electron/issues/21633
=> update Electron to 7.1.9 - fix default button in dialog not working on macOS

ReactNativeClient/lib/shim-init-node.js, ReactNativeClient/lib/shim-init-react.js, ReactNativeClient/lib/shim.js
Addresses #2317 
Tested:
Comment: `package.json` exists for both command-line and desktop builds. However here we implemented it to use `packageInfo.js` for desktop builds, as requested.
=> Cross-platform version number retrieval

ElectronClient/app/gui/NoteText.jsx
=> Desktop: Fix empty pdf export

ReactNativeClient/lib/models/Setting.js, docs/terminal/index.html, readme/terminal.md
Adding a new date format "YYYY.MM.DD." which may be more pleasing to some eastern languages speakers' eyes...
=> All: Added new date format YYYY.MM.DD

BUILD.md
Minor update to the build command for Tools in response to the question in this [post]( https://discourse.joplinapp.org/t/gsoc2020-introduction-to-community/5571/9)
=> Documentation: Update build instruction for Tools

ElectronClient/app/gui/MainScreen.jsx
see https://discourse.joplinapp.org/t/request-better-tag-organisation/5662?u=tessus
Tags are now sorted properly in the drop-down list:
=> Desktop: sort tags in drop-down list (when adding tags)

ReactNativeClient/lib/WebDavApi.js
see https://discourse.joplinapp.org/t/joplin-terminal-question-sync/5700?u=tessus
=> comment out console messages in WebDavApi.js

ElectronClient/app/app.js
=> use current year in About box (in the copyright text)

CliClient/locales/nl_NL.po
I felt like improving some of the Dutch translation work for Joplin so here are some more and improved translations
(not all that many but more may come)
=> Add & Edit translations (nl_NL)

CliClient/locales/et_EE.po
=> Estonian lang

CliClient/locales/nl_NL.po
I added missing translations and improved the overall quality for nl_NL.
=> Improve nl_NL Translation

CliClient/locales/zh_CN.po
I have made some minor modifications to the Simplified Chinese translation.
=> Improve Simplified Chinese translation

CliClient/locales/ko.po
Hello!
Thanks for letting me use Joplin! :) 
I updated some translation for Korean.
Signed-off-by: Ji-Hyeon Gim <potatogim@gluesys.com>
=> Translation: update Korean translation

BUILD.md
I've made some changes to the build guide. This should make it easier to follow.
=> Made some changes to BUILD.md have better readability

CliClient/locales/de_DE.po
=> Added missing translations and improved language (DE)

CliClient/locales/it_IT.po
Translated the remaining lines.
=> Italian translation Update

ReactNativeClient/lib/geolocation-node.js
Change geo-location service to `freegeoip.app` (https).
removed unnecessary request to `api.ipify.org`
closes #2469
=> change geolocation service to freegeoip.app

ElectronClient/gui/TagList.jsx
=> Desktop : Tag Wrap Disabled

CliClient/locales/th_TH.po
=> Translation: Add Thai language

CliClient/locales/sr_RS.po
=> Update: updated Serbian translation sr_RS

CliClient/tests/integration_ShowAllNotes.js, CliClient/tests/models_BaseItem.js, CliClient/tests/models_Note.js, ReactNativeClient/lib/models/Note.js
Fixes simple typo in function name.
=> All: Fix calls to non-existent function

CliClient/app/cli-integration-tests.js, CliClient/tests/feature_ShowAllNotes.js, CliClient/tests/feature_TagList.js, CliClient/tests/services_Revision.js, CliClient/tests/test-utils.js, ReactNativeClient/lib/BaseApplication.js, ReactNativeClient/lib/BaseModel.js, ReactNativeClient/lib/registry.js, ReactNativeClient/lib/services/ResourceFetcher.js, ReactNativeClient/lib/services/ResourceService.js, ReactNativeClient/lib/services/RevisionService.js, ReactNativeClient/lib/services/SearchEngine.js, ReactNativeClient/root.js
Some devs are reporting spurious errors when running integration tests.
https://discourse.joplinapp.org/t/integration-showallnotes-test-failing-randomly/6664
https://discourse.joplinapp.org/t/automated-testing-framework/6705
This PR contains modifications to resolve the issues.
These issues are due to using timeouts to wait for asynchronous processing to complete in response a test action. On some devs PCs it seems these timeouts are not big enough, so the action is incomplete and the test fails. The modification is to wait for middleware processing to complete before proceeding with the tests. This is achieved by replacing the sleeps with with calls to `TestApp.waitForProcessing()`.
A second issue is due to notes having identical timestamps which can affect the sorting order.  To fix, a …
=> Tests: Integration test harness fixes

CliClient/tests/reducer.js, ReactNativeClient/lib/reducer.js
=> Fix : Remember last selected note

CliClient/locales/de_DE.po
I just like to help the Project, so I updated some translation strings
=> Update: updated German translation de_DE

CliClient/locales/zh_CN.po
Windows Client Update zh_CN.po
Adjusted and added some Chinese simplified translation text
I like Joplin very much and hope to do my best
------------
Windows客户端更新 zh_CN.po
调整和新增了部分简体中文翻译文本
非常喜欢Joplin，希望能尽绵薄之力
=> Windows Client Update Chinese simplified translation zh_CN

CliClient/locales/ru_RU.po
Finished translation to Russian language and fixed existing mistakes.
=> Translation: Update ru_RU.po

CliClient/locales/pt_BR.po
I've improved translation for brazilian portuguese.
=> Improves brazilian portuguese translation

CliClient/locales/pl_PL.po
=> completed empty to 100%

readme/prereleases.md
=> Update to match Desktop text

CliClient/locales/ja_JP.po
=> Translation: Update ja_JP.po

ReactNativeClient/lib/components/screens/config.js
**Android Joplin app**
- This PR makes the "Path:" text visible properly  
- Reference of issue #2867
=> Mobile: fixes the visiblity of "Path:" text

ReactNativeClient/lib/components/global-style.js, ReactNativeClient/lib/joplin-renderer/noteStyle.js
closes #2900 
@PackElend  please label my PR.
Before:
After:
=> Mobile: fixed bold text not visible in dark theme

ElectronClient/gui/NoteText.jsx
Fixes #2917 
Added rule to prevent overflow of title input field
=> Desktop : Prevent overflow on small window size

ElectronClient/plugins/GotoAnything.jsx
=> Desktop: Fix a blank Goto Anything screen

ReactNativeClient/lib/components/global-style.js, ReactNativeClient/lib/components/screens/config.js
closes #2847 
I changed the default font of those missing text to Roboto and tested the build apk on my phone and now the text is shown properly and everything is fixed. Please have a look.
@PackElend  please label me.
=> Mobile: fixed text issue on some devices

CliClient/locales/ko.po, README.md
=> Translation: Update ko.po

ElectronClient/app.js, ElectronClient/gui/ResourceScreen.tsx, ElectronClient/gui/Root.jsx
Here's an initial stab at #2639.
=> Resource screen improvements

CliClient/locales/sv.po
=> All: Translation: Update sv.po

ElectronClient/gui/NoteList.jsx, ElectronClient/style.css
=> Desktop: Fixes todo-hover behaviour

CliClient/locales/pt_BR.po
=> Update translation pt_BR

CliClient/tests/feature_ForwardBackwardNoteHistory.js, CliClient/tests/feature_ShowAllNotes.js
This PR fixes feature tests according to recent test harness fixes. (#2723)
These changes reduce the chance of random (false) failures due to timing / race conditions.
=> Tests: Fix random failures

CliClient/locales/tr_TR.po
Hello, 
This PR includes further updates for Turkish translations, in addition to #2880 which I've made earlier.
I've translated the new strings since my last translation, and have updated some old translations which I've missed earlier.
=> Turkish translations updated

ElectronClient/plugins/GotoAnything.jsx, ElectronClient/theme.js
Fixes #3095 
**Before Changes:**
**After Changes:**
=> Desktop: Fixed the Goto Anything item list overflow

readme/e2ee.md
=> little typo correction in e2ee doc

CliClient/locales/fr_FR.po
My first contribution to this fantastic project I was waiting from a long time. Thanks!
=> Partial translation in French

CliClient/locales/el_GR.po
Hey
I just updated el_GR.po for current version.
Thanks
=> Update Greek translation

CliClient/locales/pt_BR.po
Updated locale for Brazilian portuguese.
Just fixed Poedit flags and added empty/placeholder strings.
Hope it helps.
Cheers,
Renato.
=> Update locale: pt_BR

CliClient/locales/it_IT.po
=> Update italian locale

ElectronClient/app.js
=> Add search feature in Help Menu (for mac users)

ReactNativeClient/lib/joplin-renderer/MdToHtml/rules/mermaid_render.js
Fixes #3109 
**Before changes:**
**After changes:**
=> Fixed the mermaid graph width 

ElectronClient/gui/NoteEditor/NoteBody/AceEditor/AceEditor.tsx, ElectronClient/gui/style/theme/nord.js, ElectronClient/gui/style/theme/solarizedDark.js, ElectronClient/gui/style/theme/solarizedLight.js
conflicts were fixed and changes were added to AceEditor.tsx
=> Desktop: closes#2894

ReactNativeClient/lib/components/screens/notes.js
Fixes https://github.com/laurent22/joplin/issues/2327
=> Mobile: Handle back button press when sort popup is open

ElectronClient/gui/NoteEditor/NoteBody/AceEditor/AceEditor.tsx, ElectronClient/gui/style/theme/nord.js, ElectronClient/gui/style/theme/solarizedDark.js, ElectronClient/gui/style/theme/solarizedLight.js
final commit. there was a slight path issue in #3188. this'll do it.
=> Desktop: Resolves #2883: themes switched for more appealing text highlighting.

CliClient/locales/de_DE.po
- Changed translation for Fail-safe from Störsicher to Fehlersicher
=> Updated German translation

CONTRIBUTING.md
Fixes some typos and a broken anchor link in `CONTRIBUTING.md` file
=> Fixes some typos in CONTRIBUTING.md

CliClient/locales/zh_CN.po
Translation added, error fixed & expression improved.
=> Translation: Update zh_CN.po

CliClient/locales/id_ID.po, completer.hist
Here im adding translation into bahasa indonesia (id)
=> Translation : translate to bahasa indonesia

.travis.yml, ElectronClient/package.json
=> Trying to fix CI

CliClient/locales/id_ID.po
- Added new translations.
- Fixed some grammar & spelling mistakes.
- Fixed some typos.
- Improved sentence structure to be more formal, standardized,
and easier to understand.
- Improved translation consistency for some words/phrases.
=> Translation: Update id_ID.po

CliClient/locales/ja_JP.po
* Translate new strings
* Explicitly specify an access key for menu items
=> All: Translation: Update ja_JP

CliClient/locales/de_DE.po
Added missing German translations and update a few existing ones.
=> All: Translation: Update de_DE

CliClient/locales/es_ES.po
- Added spanish translations 
- Corrected translations marked as 'Needs work'
=> All: Translation: Update es_ES

ElectronClient/gui/NoteEditor/NoteBody/AceEditor/AceEditor.tsx, ElectronClient/gui/NoteEditor/NoteBody/AceEditor/utils/useListIdent.ts
=> Desktop: Unindent empty list markup on Enter

CliClient/tests/feature_NoteHistory.js
https://github.com/laurent22/joplin/pull/2819#issuecomment-636551313
=> All: Rewrite randomly failing test

CliClient/locales/pt_BR.po
=> Updated pt_BR translation

CliClient/locales/pt_BR.po
Portuguese translation update.
=> Update pt_BR.po (portuguese translation)

CliClient/locales/bs_BA.po
Finished translating new strings. Corrected the old ones that have changed since the last translation update.
=> Translation Update: bs_BA.po

CliClient/locales/ja_JP.po
=> All: Translation: Update ja_JP.po

CliClient/locales/tr_TR.po
Hello,
In this pull request, you can find the Turkish translations which have the latest changes implemented.
Thanks,
=> Turkish locales updated

CliClient/locales/zh_CN.po
Update translation: Update zh_CN.po
=> All: Translation: Update zh_CN.po

CliClient/locales/fr_FR.po
I completed some strings in the french translation.
=> Updates to the french translation

CliClient/locales/zh_TW.po
=> All: Translation: Update zh_TW.po

CliClient/locales/zh_CN.po
=> All: Translation: Update(improve) zh_CN.po

CliClient/locales/zh_TW.po
=> Translation: Update zh_TW.po

CliClient/locales/zh_CN.po
1. Remove 'fuzzy' tag where translation is good enough.
2. Remove trailing spaces.
3. Update translation for sentence
```text
"Remove tag \"%s\" and its descendant tags from all notes?"
```
4. Add translation for sentences
```text
"Read time: %s min"
"Tag name cannot start or end with a `/`."
"Tag name cannot contain `//`."
```
=> Translation: update zh_CN

CliClient/locales/de_DE.po
- consistent usage of du/Sie
- added missing entries
- grammar and spelling
- some rewording to make it more German and less English
- replaced Eintrag/Objekt with Element (item)
- fixed some wrong translations
- etc
=> All: revised German translation

ReactNativeClient/lib/SyncTargetAmazonS3.js
linter error breaks CI pipeline
=> fix linter error and thus CI pipeline

ReactNativeClient/lib/services/rest/Api.js
=> Api: Fixes #3539: Fixes nested tag API to handle calls with no 'fields' query key

CliClient/locales/ru_RU.po
Updating Russian translation. Multiple errors fixed, new translations added.
=> All: Fixing and expanding Russian translation

ElectronClient/plugins/GotoAnything.jsx
If the "showCompletedTodos" setting is `false`
=> Desktop: Hide completed to-dos in GotoAnything results

CliClient/locales/es_ES.po
=> Add and fix some Spanish translations

CliClient/locales/fa.po
- translation added
- errors fixed
=> Translation: Update fa.po

CliClient/locales/ru_RU.po
=> All: Fix typos and punctuation in Russian translation

CliClient/locales/pt_BR.po
=> Translation: Update pt_BR.po

README.md
=> Fixed 404  e2ee spec link

CliClient/locales/ro.po
Updated Romanian translation. New translations added and some errors fixed.
=> All: Translation: Update ro.po

CliClient/locales/de_DE.po
This patch includes the translation of missing strings, the improvement of the existing translation and the replacement of Anglicisms by German words.
=> All: Update German translation

CliClient/locales/ko.po
This PR includes some improvements about Korean translations.
=> All: Translation: Update ko.po

ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/utils/useEditorSearch.ts
Fixes https://discourse.joplinapp.org/t/bug-joplin-1-1-4-unable-to-edit-a-note-found-after-a-search/11157/5
ps: I got a peek at the new style updates, they're looking really good :)
=> Desktop: Fix bug where editor would scroll to focus global search

CliClient/locales/ca.po
Reviewed and completed the catalan translation.
=> Full review of catalan translation

CliClient/locales/fa.po
Updated some existing Persian translations and added some new translations.
@mmahmoudian please feel free to check the translations!
=> Update existing Persian translations and added some missing translations

ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/utils/useJoplinMode.ts
<!--
Please prefix the title with the platform you are targetting:
Here are some examples of good titles:
- Desktop: Fixes#3796 : Fixed emoji highlighting bug
=> disabled emoji highlighting to fix bug

CliClient/locales/ko.po
It updates fuzzy/missing translations for Korean.
Signed-off-by: Ji-Hyeon Gim <potatogim@gluesys.com>
=> Update KR Translation

readme/api/get_started/plugins.md
The link to the plugin tutorial was broken.
=> Fixed broken link in plugins.md

ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/utils/useListIdent.ts
[ref](https://github.com/laurent22/joplin/pull/3823#issuecomment-706603019)
fixes #3898
=> Actually enter insert mode after pressing o/O

CliClient/locales/es_ES.po
If accepted, could the tag be added #hacktoberfest-accepted ?
=> Translate Spanish

ReactNativeClient/lib/joplin-renderer/MdToHtml/rules/image.js, ReactNativeClient/lib/joplin-renderer/MdToHtml/rules/link_open.js
Also note that I was unable to build the android version without adding back `ReactNativeClient/lib/rnInjectedJs/webviewLib.js`
=> Android: do not show long press menu on press and drag

ReactNativeClient/lib/services/searchengine/queryBuilder.ts
#3934 
The notebook should not be included in the "union" created by the "any:" operator
=> All: Resolves #3934 fix notebook filter

CliClient/locales/es_ES.po
Several corrections in spanish language
=> All: Update es_ES.po language file

CliClient/locales/nl_NL.po
Add missing translations and update a few existing translations marked as "Needs Work"
=> Dutch translation updates

README.md, packages/tools/build-translation.js
=> Tools: Fix incorrect localization URLs

packages/tools/update-readme-contributors.js
This PR fixes the README.md path in the update-readme-contributors.js script
It also changes the link to the contributor to the users GitHub page instead of the GitHub API url
=> Tools: Contributor fixes

packages/app-mobile/android/app/src/main/AndroidManifest.xml
Follow-up on pull https://github.com/laurent22/joplin/pull/787
Fixes regression introduced by https://github.com/laurent22/joplin/commit/cb3e1cf1e956e9921cc698b510eed3ac5500d402#diff-60aa334fa21790107dce7a4dd1b69c087282a1d24f2eac559fa0c031af429425
Signed-off-by: Atrate <Atrate@protonmail.com>
=> Android: Make app movable to SD card again

packages/app-mobile/components/BackButtonDialogBox.ts
Fixes https://github.com/laurent22/joplin/issues/4071
=> Android: fix sharing

packages/tools/locales/da_DK.po
Updating the translation file for danish.
This is a retry on the pull request, last pull request was with an old version of Joplin.
=> Updating translation of "da_dk.po"

packages/lib/file-api-driver-amazon-s3.js
When the mobile application tries to synchronize a note with attached
resource files, e.g. from the notebook "Welcome! (Mobile)", readFile()
is called to return a Buffer although that isn't implemented in
FsDriverRN.readFile(). This is changing the code to return base64
encoded content from react-native and turn it into a Buffer before the S3
putObject() API call is used to create the remote object.
Tested with AVD Android 10.0 target.
=>  Mobile: Fixes #3601: Fix uploading resource files to S3 with RN

fi_FI.po
=> All: Translation: Add Finnish fi_FI.po

packages/tools/locales/de_DE.po
=> All: Updated german translations

packages/tools/locales/zh_CN.po
=> Update zh_CN translation w.r.t latest pot

packages/tools/locales/ru_RU.po
=> All: Translation: Update ru_RU.po

readme/faq.md
=> Documentation: Add tip to pass arguments to the installation script

packages/tools/locales/zh_CN.po
This PR updates zh_CN translation so that it is 100% complete now.
Is is possible that the translation strings in the json files get updated each time when a translation PR is merged? It seems that the strings on the UI often lags behind the merge of translation.
=> Update zh_CN translation (2020-12-29)

packages/tools/locales/zh_TW.po
Include new strings and fuzzy translated strings
=> Fix a few translation in zh-TW

packages/app-mobile/android/app/src/main/AndroidManifest.xml
=> Android: enable backup

readme/clipper.md
=> Update clipper.md interfer -> interfere

packages/generator-joplin/README.md
Fix missing `"` on json array name definition
=> Fix typo on json array definition

packages/app-desktop/app.ts
I imagine you have this working on your own branch, but I figured I'd make this available here just in case.
=> SideBar -> Sidebar in app.ts

packages/tools/locales/id_ID.po
=> Update Indonesian translation

packages/generator-joplin/generators/app/templates/src/index.ts
=> Chore: Updating template to match docs

packages/tools/locales/pl_PL.po
- complete translation
- minor corrections
=> Translation: Update pl_PL.po

packages/tools/locales/ru_RU.po
=> Russian translation

readme/changelog_server.md
=> Fix the link error, there is no server-v1.7.4

readme/api/get_started/plugins.md
=> Plugin: Docs: Clarifying how to get/test the hello world plugin via scaffolding

readme/api/references/development_mode.md
=> Desktop: Development: Clarifying that dev mode is started from CLI

packages/tools/locales/hu_HU.po
Hello,
I have started to translate Joplin into Hungarian. Currently ~93% is done.
Would you be so kind to merge it?
Thanks
I have questions regarding translation:
1. I think I get the meaning, but really is the 't' and 'd' are mixed a bit in the following string?
Displays only the items of the specific type(s). Can be `n` for notes, `t` for to-dos, or `nt` for notes and to-dos (eg. `-tt` would display only the to-dos, while `-ttd` would display notes and to-dos.
2. can the eg. strings be localised? I could not find them.
Sorts the item by <field> (eg. title, updated_time, created_time).
Sandor
=> Adding Hungarian translation

packages/tools/locales/hr_HR.po
- minor changes/corrections
- complete translation
- removed unused strings
Is there anything else which needs to be translated? I found: [joplin/packages/lib/locales/hr_HR.json](url), but I don't know if this is being translated automatically ...
Also, please add some information about "localisation/internationalisation" in the general description of the app ... for instance, by adding the term **multilingual** with a link ... Maybe something like:
_Joplin is a free, <a href="https://joplinapp.org/#localisation">multilingual</a>, open source note taking and to-do application, which can handle a large number of notes organised into notebooks._
=> Update Croatian translation

packages/tools/locales/pt_PT.po
- 100% translation
- Fixed and improved some older translations
- Kept the translation consistency
=> Locale PT-PT Update

packages/tools/locales/uk_UA.po
=> Added Ukrainian translation

packages/tools/locales/pl_PL.po
=> All: Translation: Update pl_PL.po

packages/app-desktop/gui/ConfigScreen/controls/plugins/PluginBox.tsx
=> Make plugin links clickable from search

packages/app-desktop/plugins/GotoAnything.tsx, packages/lib/BaseApplication.ts, packages/lib/JoplinDatabase.ts, packages/lib/services/searchengine/SearchEngine.ts, packages/lib/services/searchengine/queryBuilder.ts
=> All: Clean up unused fuzzy search code

packages/app-mobile/android/app/src/main/AndroidManifest.xml
Resolves #3547
With this flag Joplin can now be resized.
=> Android: make Joplin resizeable

README.md
Not sure if this is really needed, adds some info on setting up S3 for synchronization.  
Thanks!
=> Readme: Adds S3 Synchronization Info 

readme/conflict.md, readme/debugging.md, readme/gsoc2021/ideas.md, readme/gsoc2021/index.md, readme/nextcloud_app.md, readme/plugins.md, readme/rich_text_editor.md
Some spelling errors and grammatical mistakes have been corrected in the readme files wherever necessary.
=> Readme : Fixed typos and grammatical errors in the readme files

packages/tools/locales/it_IT.po
I have reviewed and completed the Italian translation.
=> All: Translation: Updated and completed Italian translation it_IT.po

packages/tools/locales/fi_FI.po
Updated all and corrected a few errors in the previous translation.
=> All: Translation: Update fi_FI.po

BUILD.md
Based on issues some people were having, e.g. https://discourse.joplinapp.org/t/build-error-on-windows-linux-arch/16104/2
=> Change windows build tools install command

packages/tools/locales/zh_CN.po, packages/tools/locales/zh_TW.po
zh_CN.po ---Correct a translation error and optimize some expressions
zh_TW.po ---Add some translations , correct some errors, optimize some translations
=> All: Translation: Update zh_CN.po and zh_TW.po

readme/welcome/1_welcome_to_joplin.md
"Applications" is confusing, it should be singular.
=> Correct typo in Welcome

packages/lib/models/Setting.ts
ref [forum](https://discourse.joplinapp.org/t/testing-v1-8-1-editor-font-editor-font-settings/16233)
The current wording is a bit confusing.
=> Update wording for font settings

README.md
A minor improvement in ReadMe.
=> Updating the kbd shortcut from the old ctrl+g to tne current ctrl+p

packages/tools/locales/sl_SI.po
I have added the remaining translations for the Slovenian language. 
Cheers :)
=> All: Translation: Added Slovenian translation sl_SI.po

packages/tools/locales/ar.po
Hello! I noticed there's a few new lines that needed an Arabic translation, fresh off the oven!
- Added in all the missing entries I could see
- Updated a few strings that had a very poor translation
=> Translation: Update ar.po

packages/tools/locales/de_DE.po
This patch translates newly added strings and improves the existing translation.
=> All: Translation: Update German translation

packages/tools/locales/nl_NL.po
I added some missing dutch translation. Also modified some that didn't really make much sense.
=> Added missing dutch translation

packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/index.ts
Resolves https://github.com/laurent22/joplin/issues/4797
=> Desktop: Skip invalid scroll positions when receiving CodeMirror scroll updates

packages/tools/locales/ko.po
in 'packages/tools/locales/ko.po' file translated completed. some modified (렌더된 -> 렌더링된) included
=> All: Korean Language translation

.eslintignore, .gitignore, packages/app-cli/tests/dateFormats.ts, packages/app-cli/tests/dateTimeFormats.ts, packages/lib/models/Setting.ts, readme/terminal.md
/ref https://discourse.joplinapp.org/t/note-overview/13962/130?u=tessus
=> All: add new date format YYMMDD

.eslintignore, .gitignore, packages/app-cli/tests/services_SearchEngineUtils.ts, packages/lib/services/searchengine/SearchEngineUtils.ts
When searching show the completed todos based on the showCompletedTodos setting.
=> Desktop: Fix #4581: Show completed todos based on showCompletedTodos setting

packages/tools/locales/el_GR.po
=> All: Translation: Update el_GR.po

README.md
I find an error in the S3 Bucket Policy on README.md, so I send a PullRequest.
=> Doc:Fixed s3 bucket policy

packages/tools/locales/it_IT.po
=> Updated Italian translation

packages/server/src/routes/index/privacy.ts, packages/server/src/routes/index/terms.ts
issues commented on here: https://github.com/laurent22/joplin/commit/db7b802803950922b4f3658449a82b3ba3afee13
=> fix text of terms and privacy

packages/app-desktop/gui/MenuBar.tsx
/ref https://discourse.joplinapp.org/t/hide-others-hide-other-applications-option/17651
=> macOS: add 'Hide Others' and 'Show All' menu items

packages/lib/shim-init-node.js
Fixes https://github.com/laurent22/joplin/issues/5014
=> Desktop: recreate http agent when the protocol changes

packages/tools/locales/cs_CZ.po
=> All: Translation: Update cs_CZ.po

packages/tools/locales/es_ES.po
=> Translate es_ES.po to 100%

packages/tools/locales/ko.po
It updates some Korean translation.
=> All: Update Korean Translation

packages/app-mobile/android/app/src/main/AndroidManifest.xml
Ref: https://discourse.joplinapp.org/t/cant-do-a-clean-re-install-on-android-using-joplin-cloud
=> Android: disable backup to Google Drive

packages/app-desktop/gui/ResizableLayout/ResizableLayout.tsx
Fixes #5111 
I added the null check as discussed in the issue.
=> Desktop: Fixes #5111: Joplin crashes when trying to Change application layout

packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx
See https://github.com/laurent22/joplin/issues/4243.
Tested that it fixes the issue on Linux Mint with KDE.
=> Desktop: Fixes #4243: Fix double-paste also on Linux

readme/donate.md
cross-plaform --> cross-pla**t**form
=> Website: Fix typo in donate section

packages/tools/locales/de_DE.po
=> Update German translation file

packages/tools/locales/hu_HU.po
Hi. I found some syntax errors and I fixed them.
=> All: Hungarian language file correction

packages/tools/locales/sv.po
=> Update Swedish translation

packages/turndown-plugin-gfm/package.json, packages/turndown/package.json
Remove es module entry points from Turndown packages, as they are not being included in the dist
=> Remove es module entry points

packages/tools/locales/id_ID.po
=> Translation: Update id_ID.po (thanks to eresytter)

packages/tools/locales/nb_NO.po
Just a small update to the nb_NO.po file. Hope it helps.
=> All:Updated norwegian translation

packages/app-cli/tests/MdToHtml.ts, packages/app-cli/tests/md_to_html/code_block.html, packages/renderer/assets/highlight.js/atom-one-dark-reasonable.css, packages/renderer/assets/highlight.js/atom-one-light.css, packages/renderer/package-lock.json, packages/renderer/package.json
Fixes https://github.com/laurent22/joplin/issues/5245
=> Bump hightlight.js to the latest version

README.md
small grammatical changes to the README.md file
=> modified README.md file providing better readability

packages/tools/locales/pt_BR.po
=> Update PT-BR Translate

readme/conflict.md
=> All: fix grammar in documentation

readme/changelog_server.md
=> Doc: Fix committer name in Joplin Server changelog

packages/tools/locales/zh_TW.po
=> Update Traditional Chinese translation

Joplin_install_and_update.sh
CentOS 7 doesn't support sandbox function
=>  Add Centos 7 for no sandbox

readme/rich_text_editor.md, readme/welcome/4_tips.md
Outdated since the website homepage redesign, I guess.
=> Update doc links

packages/tools/locales/ar.po
Hi there :-)
This substitutes PR #5459 .  Here is a complete Arabic translation of Joplin in a PO file.
=>  Translation: Update ar.po

packages/tools/locales/ru_RU.po
Here is updated Russian translation. I tried to fix all empty or untranslated strings.
=> Update for Russian translation

packages/tools/locales/es_ES.po
=> Update translations es_ES

packages/app-desktop/gui/utils/NoteListUtils.ts, packages/app-mobile/components/screen-header.js, packages/lib/models/Note.ts
=> Mobile: improve delete dialog

readme/debugging.md
Hello! The instructions on enabling dev tools seem to be outdated.
=> Website: Fix path for dev tools (debugging instructions)

readme/api/get_started/plugins.md, readme/api/references/rest_api.md, readme/clipper.md, readme/config_screen.md, readme/donate.md, readme/gsod2020/ideas.md, readme/gsod2020/index.md, readme/prereleases.md, readme/spec/clipper_auth.md, readme/spec/e2ee.md, readme/spec/server_delta_sync.md, readme/spec/server_sharing.md, readme/spec/sync_lock.md, readme/terminal.md
=> All: Fixing typos

packages/tools/locales/pt_BR.po
=> Updates on pt_BR.po file.

.github/scripts/run_ci.sh, .github/workflows/github-actions-main.yml, packages/tools/build-translation.js
=> Lost translations

packages/server/README.md
update  `STORAGE_DRIVER` type . From `File` to `Filesystem`
=> Update server README.md . From File to Filesystem

Joplin_install_and_update.sh
See the discussion in https://github.com/laurent22/joplin/pull/5302
=> Linux: Fix .desktop file to make external links work on Ubuntu

packages/app-mobile/android/app/build.gradle
This disables certain features for the camera, but it allegedly affects the test suite only.
This will hopefully remove non-free dependencies so that the app can be shipped by F-Droid: https://gitlab.com/fdroid/rfp/-/issues/434
=> android: remove non-free dependencies

packages/tools/locales/zh_CN.po
=> Desktop: complete Chinese translation

packages/app-desktop/gui/Dialog.tsx
=> Desktop: Fixes #5373: changed position absolute to fixed

packages/lib/models/Setting.ts, packages/lib/models/dateTimeFormats.test.ts
/ref https://discourse.joplinapp.org/t/request-to-add-date-format-yyyy-mm-dd/21845
=> All: add date format YYYY/MM/DD

readme/gsoc2022/ideas.md
Added ideas about improving the richtext editor.
I ended up not adding the bit about theming as its an area I've not actually touched upon, feel free to add it or let me know what to add. Also have a look at the skills required and difficulty level which have just been estimated based on other items.
=> Docs: Added richtext editor improvement ideas

packages/app-desktop/gui/NoteListControls/NoteListControls.tsx
Ref:
- https://discourse.joplinapp.org/t/sort-order-buttons-and-per-notebook-sort-order/20013/38
- https://github.com/laurent22/joplin/pull/5437#issuecomment-992379563
=> Desktop: Detailed Tooltip for Toggle Sort Order Field Button

packages/server/README.md
Fixes https://github.com/laurent22/joplin/issues/5386
Fixes https://github.com/laurent22/joplin/issues/4400
=> Server: Add instructions for Docker on Linux

BUILD.md
Although it obvious to Node.js developers how to install yarn, people from other languages might need a little hint.
=> All: Documentation: Add yarn installation instruction

packages/tools/locales/ca.po
=> All: Update Catalan translation

packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx, packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useScrollHandler.ts, packages/lib/components/shared/note-screen-shared.js
This PR fixes #5890. The detail is there.
=> Desktop: Fix #5890: Scroll jump when checkbox is toggled in Viewer

packages/tools/locales/nl_BE.po
Updated some translated strings, did it as long as I could before going insane.
=> All: Translation of nl_BE.po

packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useEditorSearch.ts, packages/app-desktop/gui/NoteEditor/utils/useNoteSearchBar.ts, packages/app-desktop/gui/NoteEditor/utils/useSearchMarkers.ts
This is just a combination of #6038 and #6037 and with b98e64c881063be1b871acb2ea9dc71d1af6ae39 restored.
fixes #6037 
fixes #6038
=> Desktop: Resolves #6035: Search selection fixes

packages/tools/locales/tr_TR.po
Hey there,
Apologies for the delay. Please find the updated Turkish translations in this pull request.
Thanks once again!
=> Updated Turkish Translations

.eslintignore, .gitignore, packages/app-desktop/bridge.ts, packages/app-desktop/gui/EditFolderDialog/Dialog.tsx, packages/app-desktop/gui/EditFolderDialog/IconSelector.tsx, packages/app-desktop/gui/EditFolderDialog/style.scss, packages/app-desktop/gui/FolderIconBox.tsx, packages/app-desktop/gui/Sidebar/Sidebar.tsx, packages/app-mobile/components/side-menu-content.js, packages/lib/models/Folder.ts, packages/lib/services/database/types.ts, packages/lib/shim-init-node.js, packages/lib/shim.ts
- Works on desktop for now
- Still need to get it working on mobile
=> Add support for custom notebooks icons

packages/tools/locales/zh_CN.po
Added missing translations; fixed fuzzy results; improved translation coherency; polished and rephrased some wordy or confusing pieces
=> All: Updated translations for zh_CN.po

packages/tools/locales/fi_FI.po
Fixed some typos and added a few new translations
=> Update Finnish translation

packages/tools/locales/sv.po
=> Update the Swedish translation

packages/tools/locales/nb_NO.po
Update nb_NO.po
Fixed some typos, improved some translations, and added new translations.
=> Update translation [nb_NO]

BUILD.md
Add a note that the path may not contain spaces
This came up a few times already on the forum and on discord so I think it's good to have it the docs.
=> Update BUILD.md 

packages/app-mobile/components/CameraView.tsx
1. Fixed a bug in the camera that allows the camera button to be pressed repeatedly, causing multiple photos to be taking in a short period of time.
2. Add an alt text for the newly taken photo `Photo taken at <localized date time>`. This gives a more meaningful title for a new note. In the past the alt text is empty so the title will become the note ID (see attachment).
https://user-images.githubusercontent.com/3250983/156072655-aa91f4e1-6008-40d6-a741-b25c590303a0.mp4
(The camera is blacked out for privacy)
=> Mobile: improved photo taking experience
